### ISSUE TITLE
Swift Compiler Error - Installing via Cocoapods

### ISSUE THREAD

**Issue by mikehobi** [rechsteiner/Parchment#121]
Hello.

I just installed this module via Cocoapods and keep getting `No such module 'Parchment'` error, when importing in my ViewController.

I also get 4 errors within the Parchment lib itself:

![screen shot 2018-01-29 at 10 59 54 am](https://user-images.githubusercontent.com/3231913/35528714-9ec4f8b8-04e3-11e8-81a5-ad54dd23674a.png)

I haven't made any changes to the files. I've cleaned out and reinstalled my pods as well. Willing to try out the carthage install too, but figured I should file an issue ticket.

I'm using xcode 9.2 and swift 4.

Thanks for this project and your support!

**Comment by rechsteiner** [comment]
Hi! I was just releasing a new version, so maybe it could be related to that? I just tried setting up a new project with CocoaPods and seems to work fine. Can you try to run `pod repo update` before running `pod install` again?

**Comment by mikehobi** [comment]
Ah cool. Perfect timing.

Looks like it's working, thanks!

**Comment by rechsteiner** [comment]
Awesome 👌
