### ISSUE TITLE
How to programmatically select item?

### ISSUE THREAD

**Issue by saldous** [rechsteiner/Parchment#123]
Take the storyboard example project, if I want to programmatically select the secondVC, how do I do it?

If I do:
`pagingViewController.select(index: 1)`

When I run the app, secondVC isn't shown and the top menu still shows the first one and can't navigate anymore. What am I missing?

Sorry if this is a stupid question, I just can't figure it out!

**Comment by rechsteiner** [comment]
Looks like there is a bug in Parchment. For now, it should work to select items in `viewDidAppear`. Will get a fix out shortly!

**Comment by rechsteiner** [comment]
Should be fixed in #125 now. Will release a new version very soon!

**Comment by rechsteiner** [comment]
Just released version 1.0.1 with a fix for this. Thanks for catching that 🙌
