### ISSUE TITLE
How I can use it with objc?

### ISSUE THREAD

**Issue by ahmetalsan** [rechsteiner/Parchment#133]

**Comment by rechsteiner** [comment]
Hi! Sorry, Parchment only works with Swift. It relies pretty heavily on generics, so it would require a substantial rewrite to get it working for Objective-C. I don't have any plans to support objc at the moment, but I might consider that in the future.

**Comment by ahmetalsan** [comment]
@rechsteiner thanks. Thank you btw. It's a great library.

**Comment by rechsteiner** [comment]
Thanks 🙌
