### ISSUE TITLE
Delegate not working in infinite case

### ISSUE THREAD

**Issue by Narek1994** [rechsteiner/Parchment#134]
Hi, i just tried to use self size logic in calendar example, I mean use approach in delegate example to have cell size fit to text, but my delegate functions dont fire.
Is it possible to have self size cells for infinite usage?

**Comment by Narek1994** [comment]
and second question, if I have a fixed data,I mean for example for 5 items, can I have an infinite logic?
becuase as I understood infinite example is really relays on infinite data, but can we achive same logic none infinite data?

**Comment by rechsteiner** [comment]
Yeah, turns out there was a bug with the way I registered the size delegate. Should be fixed in #135. Will have a new release out shortly ✌️

As for the infinite behavior you’re describing it is _kind of_ possible. Items in Parchment have to be unique so you can’t rely solely on the title, but you can create a data source that subtracts or adds to an index and take the modulo of that index to get the title. Here's an example using the `DelegateExample` target:

```Swift
extension ViewController: PagingViewControllerInfiniteDataSource {
  
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemAfterPagingItem pagingItem: T) -> T? {
    let item = pagingItem as! PagingIndexItem
    let index = item.index + 1
    let title = cities[abs(index % cities.count)]
    return PagingIndexItem(index: index, title: title) as? T
  }
  
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemBeforePagingItem pagingItem: T) -> T? {
    let item = pagingItem as! PagingIndexItem
    let index = item.index - 1
    let title = cities[abs(index % cities.count)]
    return PagingIndexItem(index: index, title: title) as? T
  }
  
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {
    let item = pagingItem as! PagingIndexItem
    return CityViewController(title: item.title)
  }
  
}
```

This will create the illusion of scrolling infinitely with just those items. The problem with this approach is that it will not update the selected cell indicator as you scroll in the header, as each item is unique. I’m not sure how to best add support for this. Either we can add a specific option for a «looping scroll mode», or support having multiple items with the same paging item. I need to get back to you on that.

**Comment by rechsteiner** [comment]
Released v1.0.3 with the fix now!

**Comment by Narek1994** [comment]
First of all thanks for help, this is what I need.
in my case I dont have a scroll option in header, so its fully ok for me ) but I guess it would be nice to have that option.
Thanks a lot

**Comment by rechsteiner** [comment]
Awesome! I'll create another issue for the looping scrolling 👍

**Comment by Narek1994** [comment]
Thanks, also I would suggest in this type of implementation to have an option to use already created controllers in list, I mean 
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {
        let item = pagingItem as! PagingIndexItem
        return controllers[item.index]
    }
to not create each view controller every time
Problem I faced here, that I dont have real index of the item, item.index can be everything, even -1,-2...
Thanks

**Comment by rechsteiner** [comment]
You could use the same approach as above where you take the modulo of the index:

```Swift
return controllers[abs(item.index % controllers.count)]
```

**Comment by Narek1994** [comment]
Yea I have tried it, but its not working properly 
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {
        let item = pagingItem as! PagingIndexItem
        let index = item.index
        print(abs(index % cities.count))
        return controllers[abs(index % cities.count)]
    }
in this case when I am swiping to right(to view previus one) its shows me white empty view controller, and my collectionView dataSource also shows wrong title
in our example if I have a this list of titles
fileprivate let titles = [
        "SHOWS",
        "CHATS",
        "COMICS",
        "PLAYLISTS",
        "CONTINUE"
    ]
should I select it like this in viewDidLoad
 pagingViewController.select(pagingItem: PagingIndexItem(index: 0, title: "SHOWS"))
I dont get this select logic, or should I set this index to be 0, something like 
 pagingViewController.select(pagingItem: PagingIndexItem(index: titles.count, title: "SHOWS"))
Thanks.

**Comment by rechsteiner** [comment]
The white empty view controller sounds like you are trying to navigate to the same view controller that you are currently on. I'm not sure exactly what's causing this for you, but here is an example of how you could achieve this:

```Swift
class ViewController: UIViewController {
  
  let viewControllers: [UIViewController] = [
    CityViewController(title: "Oslo"),
    CityViewController(title: "Shanghai"),
    CityViewController(title: "Mumbai"),
    CityViewController(title: "Amsterdam"),
    CityViewController(title: "Sydney"),
  ]
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let pagingViewController = PagingViewController<PagingIndexItem>()
    pagingViewController.infiniteDataSource = self
    
    addChildViewController(pagingViewController)
    view.addSubview(pagingViewController.view)
    view.constrainToEdges(pagingViewController.view)
    pagingViewController.didMove(toParentViewController: self)
    
    let item = PagingIndexItem(index: 0, title: viewControllers[0].title ?? "")
    pagingViewController.select(pagingItem: item)
  }
  
}

extension ViewController: PagingViewControllerInfiniteDataSource {
  
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemAfterPagingItem pagingItem: T) -> T? {
    let item = pagingItem as! PagingIndexItem
    let index = item.index + 1
    let title = viewControllers[abs(index % viewControllers.count)].title ?? ""
    return PagingIndexItem(index: index, title: title) as? T
  }
  
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemBeforePagingItem pagingItem: T) -> T? {
    let item = pagingItem as! PagingIndexItem
    let index = item.index - 1
    let title = viewControllers[abs(index % viewControllers.count)].title ?? ""
    return PagingIndexItem(index: index, title: title) as? T
  }
  
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {
    let item = pagingItem as! PagingIndexItem
    return viewControllers[abs(item.index % viewControllers.count)]
  }
  
}
```

Here I've replaced the titles array with just an array of view controllers and then use the `title` property for the menu items. Does that work for you?

**Comment by Narek1994** [comment]
Unfortunately no, if you try this code in that example, and change CityViewController view background color for example to black, and swipe to right, you will see that bug when it shows white screens.
I dont know how to upload recorded video here

**Comment by rechsteiner** [comment]
Oh okay. I’ll take look and see if I can find a solution 👍

**Comment by Narek1994** [comment]
Its correctly working when you are swiping to left(viewing next items), and its starting to work correctly if we swipe right few items(I guess after 5 or 6 items) but when you are swiping previus 6 items it has this bug

**Comment by Narek1994** [comment]
ok Thanks a lot

**Comment by Narek1994** [comment]
I just find the way to fix this, very hacky way, just putted first selected item index to be Int.max/2 ))
the problem is with -index 0 and +index,when I put selected item to be Int.max/2 I just dont have that problem with -index))

**Comment by Narek1994** [comment]
Just wanted to know,if in this case will I have increasing memory usage? or its reuse already created viewcontrollers and cells?

**Comment by rechsteiner** [comment]
Ah yeah that makes sense. There shouldn’t be any increased memory usage of that approach, so that sounds like a good solution for now. The only thing you need to think about is how many view controllers you are allocating up-front by storing it in an array. But it shouldn’t be an issue with the number of view controllers you’re having.

I’ll explore some ways of making this easier in the future 👍

**Comment by Narek1994** [comment]
great, thanks a lot
