### ISSUE TITLE
Doesn't compile because of inner library error

### ISSUE THREAD

**Issue by Gargo** [rechsteiner/Parchment#137]
Added via cocoapods
Version: 0.9.x and 1.0.3
.../Pods/Parchment/Parchment/Classes/PagingOptions.swift:76:50: Type 'UIFont' has no member 'Weight'

In the same time on another pc downloaded this repo and ran examples - they work

**Comment by rechsteiner** [comment]
Which version of Swift are you using?

**Comment by Gargo** [comment]
@rechsteiner 
xcode 9.2 so the swift should be the latest. Maybe you are using beta xcode?

**Comment by rechsteiner** [comment]
Hmm, no I’m also using 9.2 and Swift 4. Are you sure you are using v1.0.3? Can you try to run `pod repo update` before running `pod install` again?

**Comment by Gargo** [comment]
@rechsteiner I don't sure with Swift 4 only (if it has a separate switch).

I didn't try your pod combinations. Instead I used even better ones:
```
pod repo remove
pod update
pod install
```
The only change is it downloaded 1.0.3 instead of 0.9.x

**Comment by rechsteiner** [comment]
Okay. But it still doesn’t work for you? Are you using Swift 4? Parchment only works with the latest version of Swift. You could try out v0.5.0, but it’s quite an old version.

**Comment by Gargo** [comment]
My mistake is I thought swift version is automatically updated with xcode

**Comment by gmogames** [comment]
Doesn't UIFont.Weight only works on ios 11+ so even if using Swift 4 but targeting ios 10, it does not work @rechsteiner

**Comment by gmogames** [comment]
https://developer.apple.com/documentation/uikit/uifont.weight for reference

**Comment by rechsteiner** [comment]
@gmogames I think it's still backwards compatible with older versions though. It works just fine when I'm running on a device with iOS 10.2, and it also works when running 8.2 in the simulator. Are you seeing any crashes on older devices?
