### ISSUE TITLE
Can I use only "highly customizable menu"?

### ISSUE THREAD

**Issue by chapayGhub** [rechsteiner/Parchment#139]
In some cases I need only top part of Parchment (show only possible options and get user choice)
Is it possible?

**Comment by rechsteiner** [comment]
No, sorry this isn’t possible at the moment. But I’m planning on adding it in the next version 👍

**Comment by chapayGhub** [comment]
Thank you!

**Comment by chapayGhub** [comment]
Hey

" But I’m planning on adding it in the next version 👍"

Did you added this feature?

**Comment by rechsteiner** [comment]
Hi @chapayGhub! No, this turned a to be a bit more work that I originally thought. I will try to get something out over the next weeks 🙂

**Comment by chapayGhub** [comment]
Thanks
Good luck

**Comment by chapayGhub** [comment]
If you create standalone ui component from "highly customizable menu" with delegates/callbacks
Others can implement any ui logic for user selection in it 
- one UITableView with different content
- collection of separate view controllers like now
- show/hide subviews
- ....

"highly customizable menu" should be really helpfull ui component!

**Comment by rechsteiner** [comment]
Yeah, I totally agree 😄
