### ISSUE TITLE
Hashable and Comparable protocols built-in into PagingItem?

### ISSUE THREAD

**Issue by gerchicov-bp** [rechsteiner/Parchment#141]
In general `PagingItem` is a bad choice for protocol name but ok. As I understand `PagingItem` can't be used without `Hashable` and `Comparable`. Why not to use inheritance between protocols?
Or you could create a proxy class which implements these methods by default (for example hash and comparison using "index").

**Comment by rechsteiner** [comment]
Hi! Thanks for the feedback. There is a default implementation called `PagingIndexItem` that is used for the default behaviour that you can use if you only need to display a title.

If you need anything else you need to create your own model that conforms to `Hashable` and `Comparable`. The reason for this that we want the data for the menu items to be completely flexible and possible to use with simple value-types. Having it as a protocol means you can for instance conform your existing data models to this protocol and use them with Parchment. That said, the currently implementation means we need to rely heavily on generics, which makes the data source/delegate a bit messy. Changing `PagingItem` to a base class would make this a bit cleaner and would also make it easier to add compatibility with objc/Xamarin etc. But again, we would loose some flexibility as you would be required to subclass `PagingItem`.

**Comment by rechsteiner** [comment]
Closing this for now, but let me know if you have any other questions ✌️
