### ISSUE TITLE
Overlay instead of pushing childviews down

### ISSUE THREAD

**Issue by hdmoncue** [rechsteiner/Parchment#144]
Question - right now it would appear that Parchment pushes its children viewcontrollers down by an amount equal to the size of its height.  Is it possible to, instead of pushing those viewcontrollers down to instead overlay itself on top of the child viewcontrollers without pushing them down?

**Comment by rechsteiner** [comment]
Not sure if I understand exactly what you mean. Do you mean showing the menu items overlayed on top of the view controllers?

**Comment by hdmoncue** [comment]
Yes that is exactly what I’m looking to do. Ultimately I want a transparent background for the menu items so you can see the view controller underneath.

- Tharp

**Comment by rechsteiner** [comment]
Okay, that's definitely possible! You can completely customize how to display the menu items by subclassing `PagingView` and override `setupConstraints` like this:

```Swift
class CustomPagingView : PagingView {
  override func setupConstraints() {
    pageView.translatesAutoresizingMaskIntoConstraints = false
    collectionView.translatesAutoresizingMaskIntoConstraints = false
    
    NSLayoutConstraint.activate([
      pageView.leadingAnchor.constraint(equalTo: leadingAnchor),
      pageView.trailingAnchor.constraint(equalTo: trailingAnchor),
      pageView.topAnchor.constraint(equalTo: topAnchor),
      pageView.bottomAnchor.constraint(equalTo: bottomAnchor),
      
      collectionView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 20),
      collectionView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -20),
      collectionView.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -20),
      collectionView.heightAnchor.constraint(equalToConstant: options.menuItemSize.height),
    ])
  }
}

class CustomPagingViewController: FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      options: options,
      collectionView: collectionView,
      pageView: pageViewController.view)
  }
}
```

Then you can make the menu items completely transparent by setting these values:

```Swift
pagingViewController.headerBackgroundColor = .clear
pagingViewController.backgroundColor = .clear
pagingViewController.selectedBackgroundColor = .clear
```

Let me know if that works for you!

**Comment by rechsteiner** [comment]
@hdmoncue did you manage to get it working?

**Comment by hdmoncue** [comment]
Yes that worked swimmingly!

**Comment by igorkaryi** [comment]
I want to put menu items to the screen down. I'm use PagingViewControllerDelegate
