### ISSUE TITLE
Feature request: Menu can sticky

### ISSUE THREAD

**Issue by wanhmr** [rechsteiner/Parchment#145]
Like twitter's profile page, the menu  can sticky.

**Comment by rechsteiner** [comment]
Hi! I don't think this is something that should be part of Parchment, but I'm pretty sure it should be possible to implement with the current version. It's possible  to subclass `PagingView` and override the default behaviour like this:

```
class CustomPagingView : PagingView {
  override func setupConstraints() {
     // Set up some constraints for the paging view that you can update on scroll
  }
}

class CustomPagingViewController: FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      options: options,
      collectionView: collectionView,
      pageView: pageViewController.view)
  }
}
```

Then you could listen for scroll events for the visible view controller and update the position of the menu when scrolling. Would that work for you?

**Comment by wanhmr** [comment]
Thx

**Comment by hosenja** [comment]
can anyone show me example code for this
