### ISSUE TITLE
Bug: Redundant move/ jump of a pagingViewController at the end of swipe scrolling

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#147]
Parchment v.1.0.3 / based on the IconsExample

When swiping left/right, there is a strange delay at the end of the horiz. scrolling and then sharp move of a pagingViewController to reach the necessary position.

Here is the video:

[parch.mov.zip](https://github.com/rechsteiner/Parchment/files/1831323/parch.mov.zip)

Apparently, this bug appears on more complex pagingViewControllers than in the example (bug can not be seen in the example), but we have it in our app, where we have heavy pagingViewControllers with collectionViews.

**Comment by rechsteiner** [comment]
Thanks for the report! I'll take a look and see if I can find a fix for that.

**Comment by rechsteiner** [comment]
Hi @IVANKRUPSKI! I've been looking a bit more into this and I'm not seeing any places in Parchment that are causing these performance issues. I would suggest looking into improving the rendering performance of your view controllers. It looks like there is too much happening on the main thread, causing the animation to stutter. If you still feel like there this is an issue with Parchment, please let me know 🙂
