### ISSUE TITLE
Need to change to next view controller programmatically.

### ISSUE THREAD

**Issue by leniyadav** [rechsteiner/Parchment#149]
I have used the storyboard example to set up pageviewer for two controllers.In first controller i have an button when on clicked it will be scrolled to next page.But i am not able to get set page index for FixedPagingViewController.How to move to next page on custom button click?

**Comment by rechsteiner** [comment]
Hi! You can select items programatically like this:

```Swift
pagingViewController.select(index: 1, animated: true)
```

**Comment by leniyadav** [comment]
Thanks @rechsteiner
Currently i have Maincontroller which has pagingViewController initialized. I have a button in Firstviewcontroller which i need to scroll to second view controller manually.How to call pagingViewController and set pagingViewController.select(index: 1, animated: true). 


    let pagingViewController = FixedPagingViewController(viewControllers: [
      firstViewController,
      secondViewController
    ])

**Comment by rechsteiner** [comment]
I guess that depends a lot on your implementation. You could have a delegate on the `firstViewController` class and trigger `select(index:)` from there. E.g. something like this:

```Swift
extension ViewController: FirstViewControllerDelegate {
    func firstViewController(firstViewController: FirstViewController, didSelectButton: UIButton) {
        pagingViewController.select(index: 1, animated: true)
    }
}
```

Then make sure you make `pagingViewController` an instance variable on `Maincontroller`, so you can access it from the delegate function.

**Comment by leniyadav** [comment]
Thanks for the help @rechsteiner. Will try and let you know.

**Comment by leniyadav** [comment]
@rechsteiner 
In delegate function i am not able access the  select function itself.  Can you please help on this i am totally new to Swift.

where should i set the instance variable and i am using the FixedPagingViewController to access viewcontrollers.

**Comment by rechsteiner** [comment]
Yeah, you need to store the `FixedPagingViewController` as an instance variable on your view controller. Something like this should work:

```Swift
class ViewController: UIViewController {
  var pagingViewController: FixedPagingViewController?

  override func viewDidLoad() {
    super.viewDidLoad()
    ...
    
    self.pagingViewController = pagingViewController
  }
}

extension ViewController: FirstViewControllerDelegate {
  func firstViewController(firstViewController: FirstViewController, didSelectButton: UIButton) {
    pagingViewController?.select(index: 1, animated: true)
  }
}
```

**Comment by leniyadav** [comment]
Thanks.In the delegate func i get this error "Extra argument 'animated' in call" 
    pagingViewController?.select(index: 1, animated: true)

**Comment by leniyadav** [comment]
can you please help on the above error

**Comment by rechsteiner** [comment]
Hmmm, no idea why you'd get that error 🤔 Are you using the latest version of Parchment? Could you provide some more details on your implementation?

**Comment by leniyadav** [comment]
yes from pods 
pod 'Parchment'
class RegisterController: UIViewController,RedirectProtocol  {
    
    var pagingViewController: FixedPagingViewController?

    func nextpage(){
        //this delegate function which will be triggered when the button from infocontroller is clicked
    pagingViewController?.select(index: 1, animated: true)
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let infoController = storyboard.instantiateViewController(withIdentifier: "BasicInfoController") as? BasicInfoController
        infoController?.delegate = self
        let addressController = storyboard.instantiateViewController(withIdentifier: "AddressController") as? AddressController
        self.pagingViewController = FixedPagingViewController(viewControllers: [
            infoController!,
            addressController!
            ])
        addChildViewController(self.pagingViewController!)
        view.addSubview((self.pagingViewController?.view)!)
        view.constrainToEdges((self.pagingViewController?.view)!)
        self.pagingViewController?.didMove(toParentViewController: self)
    }
}

protocol RedirectProtocol {
    func nextpage()
}

class BasicInfoController: UIViewController {
  var delegate: RedirectProtocol?
    @IBAction func redirecttoNextPage()
    {
        delegate?.nextpage()
    }
}

**Comment by rechsteiner** [comment]
Hmm, I just tried to run that exact code locally and it seems to work just fine. Can you double check in your `Podfile.lock` that you are using the latest version of Parchment? And maybe try to clean Xcode by running Product > Clean

**Comment by leniyadav** [comment]
It shows Using Parchment (0.9.0) 
even after pod install,it installs 0.9.0.Tried to even remove cache in pods but same version.

**Comment by rechsteiner** [comment]
You can specify which version you want to install in your Podfile like this:

```
pod 'Parchment', '~> 1.1.0'
```

**Comment by leniyadav** [comment]
Thanks @ rechstenir

It worked.The podfile was not updating had to pod  repo update and then tried installing again.Finally it installed the new version.

Code too worked.Thanks once again.

**Comment by rechsteiner** [comment]
Awesome 👍

**Comment by josipvukovic** [comment]
did the exact same but it doesn't work...code just doesn't reach main function("nextPage" - in his case). Could it be a problem with newer version of Parchment?

**Comment by Pavan96** [comment]
same here ?
