### ISSUE TITLE
Creating a Scrolling/Collapsing Menu?

### ISSUE THREAD

**Issue by mikehobi** [rechsteiner/Parchment#150]
Hello, first off I want to say this is great project!

I'm trying to recreate a "scrolling/collapsing" effect for my menu items, similar to this project: https://github.com/andreamazz/AMScrollingNavbar

I'm able to target `pagingViewController.collectionView` and animate it's frame/translation, but there is a gap of whitespace left behind. I'm guessing that I need to update the constraints, but I'm hitting a dead end.

Is there an example of this already being done? Thanks!

**Comment by rechsteiner** [comment]
Thanks! I guess one option would be to set collection view as the `titleView` on the navigation item and updating the frame of the navigation bar. You could probably even reuse that framework then. You can check out the `NavigationBarExample` target for an example.  

Does that work for you?

**Comment by mikehobi** [comment]
Ah sorry I didn't clarify, I actually have a separate nav bar that is fixed on top, and the pagingViewController is below it. And would like the collection view to translate behind my nav bar

**Comment by rechsteiner** [comment]
Ah okay, I guess that’s the same as this one: #145. Have you tried doing something like I suggested there?

**Comment by mikehobi** [comment]
Got it working using what you suggested in #145, the scrollView contentOffset updates the topAnchor constraint of the `collectionView`, working great! Also had to add a reveal function for when the user starts scrolling the pagingView

**Comment by rechsteiner** [comment]
Awesome 👌
