### ISSUE TITLE
Self-sizing PagingTitleCells

### ISSUE THREAD

**Issue by LinusGeffarth** [rechsteiner/Parchment#152]
Can we have self-sizing for cells of type `PagingTitleCell`s based on the title without resizing the collection view to full width?  
Ideally, that would be a `case` in `PagingMenuItemSize`, like: `case auto`.

Currently, I am using `PagingViewController` the following way:

    pagingViewController = PagingViewController<PagingIndexItem>()
    pagingViewController.menuItemSize = .sizeToFit(minWidth: 10, height: 40)
    // ...

`.sizeToFit(mindWidth:height:)` seems to distribute the collection view's width to all the cells. What I want, however, is the cell being only as wide as necessary.  
`.fixed(width:height:)` works better in this case, however, as it already says, it's fixed. That way I achieve a result closer to what I want, but it's not very dynamic and there's weird margins between items.

I am aware of `func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat?`, but I'm not really sure whether this is what I should be using to achieve my desired result of self-sizing cells. (It's not even being called, even when setting both the delegate and data source...)

Thanks!

<sub>[Sorry, if I missed that this already exists]</sub>

**Comment by rechsteiner** [comment]
Hey! This is definitely something I want to support add out of the box. I'm planning on adding `selfSizing(estimatedWidth: CGFloat)` as an option to `PagingMenuItemSize` like you suggested 🙂

For now though, you should be able to get the same behavior by using the `widthForPagingItem` delegate you mentioned. I'm not sure why it's not being called for you – it seems to work fine in the `DelegateExample` target. Could you provide some more details on your implementation?

**Comment by LinusGeffarth** [comment]
Sure!

This is the full code for initializing the paging view controller, and setting all the properties:

    pagingViewController = PagingViewController<PagingIndexItem>()
    pagingViewController.delegate   = self
    pagingViewController.dataSource = self
    pagingViewController.menuInteraction = .none
    pagingViewController.menuInsets = UIEdgeInsets(top: 40, left: 36, bottom: 0, right: 0)
    pagingViewController.textColor = .lightGray
    pagingViewController.selectedTextColor = .flatBlack
    pagingViewController.indicatorOptions = .hidden
    pagingViewController.borderOptions = .hidden


Here's the delegate / data source method:

    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat? {
        return Int.random(from: 20, to: 200).cgFloat
    }

I put a breakpoint on the `return` line, which isn't being hit.  
I tried several approaches regarding `pagingViewController.menuItemSize`:
   - `.sizeToFit(minWidth: 100, height: 40)`
   - `.fixed(width: 100, height: 40)`
   - uncommenting the line completely

No luck so far, am I missing something?

**Comment by rechsteiner** [comment]
Thanks for the detailed report! Are you using the latest version of Parchment? I fixed a bug with this in 1.0.3, but it could be that it’s still not working.

**Comment by LinusGeffarth** [comment]
Oh, umm it's 1.0.2... I'll update and report back!

**Comment by rechsteiner** [comment]
Just tried it with the same options you posted here and the delegate method seems to work just fine here. When are you adding the breakpoint? It will cache the result from `widthForPagingItem` so it will only be called when it renders the items initially. Could it be that you just added the breakpoint to late?

It does seem to be an issue with using `menuInsets` alongside the `delegate` though. I will see if I can find a fix as soon as possible 🙂

**Comment by rechsteiner** [comment]
Should be fixed in #155! Can you target the master branch to see if this is working for you locally before I release a new version? 🙏
