### ISSUE TITLE
Don't call viewDidLoad after selecting an item

### ISSUE THREAD

**Issue by LinusGeffarth** [rechsteiner/Parchment#158]
Can we please not call `viewDidLoad` on the view controller *every time* it is being presented?  
I have previously been using the default [`UITabBarController` which only called `viewWillAppear(_:)`](https://stackoverflow.com/a/26487504/3397217). After switching to Parchment, I was experiencing some weird UI issues. Now, I figured why that is (partially, can't blame Parchment for all my bugs, ha).

Would that be possible?  
I believe, not only could we prevent such issues, but also, we should be able to improve efficiency greatly, which would most likely cause a performance boost.

Let me know what you think about this. Thanks!

**Comment by rechsteiner** [comment]
Yeah, I wasn't sure this was the case. Added a fix for this in #160. Let me know if that works for you! Will release a new version over easter ✌️

**Comment by LinusGeffarth** [comment]
Awesome! Thanks so much!

**Comment by LinusGeffarth** [comment]
Awesome! Thanks so much!  
This certainly is an improvement already, however, it only seems to work with adjacent view controllers. 

To test this:
- open an app with the navigation and 3 or more items
- the first vc will be initialized automatically, tap the second, that one will be initialized as well
- tap on the first again, it won't be initialized again, same if you go back to the second again
- however, when going to the third (which will then be initialized), and then go back to the first, that one will be initialized again, which it shouldn't

**Comment by rechsteiner** [comment]
Yes, but that behavior is deliberate though. Parchment will only store the currently visible view controllers (the selected one, plus its two adjacent ones). We can’t really store all the view controllers we initialize, as that would quickly lead to memory issues if you had a lot of items.

In your case, if you have a fixed amount of view controllers that you don’t want to recreate when switching tabs, you can store a reference to them in an instance variable and return those from the data source. Does that make sense?

**Comment by LinusGeffarth** [comment]
Absolutely true, then this issue is just related to my project, really.

I think I get your point, almost. I currently put `storyboard?.instantiateViewController` to create the view controllers. Would I instead do this?

    strong var viewController = storyboard?.instantiateViewController(withIdentifier: "ViewController") as! ViewController

I know, `weak` is to prevent strong reference issue to keep the memory down. Do I have to use `strong var` or is just `var` sufficient?
