### ISSUE TITLE
Controller menu missing with different initial screen

### ISSUE THREAD

**Issue by kmyn** [rechsteiner/Parchment#16]
Hi,

In the Delegate Example (cities), I've added in a new controller (HomeViewController) as the initial view controller. From which, I need to navigate to the cities controller (ViewController). Layout as in screen shot

<img width="684" alt="ss" src="https://cloud.githubusercontent.com/assets/18484353/21371916/003eab7a-c6e2-11e6-80f1-c7c01d55e30b.png">
 
When I wire the "Go to cities" button to the cities controller (ViewController) or to the navigation controller attached to it, the top city selection menu bar (in cities controller) goes missing. But, the left/right swipe works taking to the new city. How do I fix this?

Thanks

**Comment by rechsteiner** [comment]
Sorry for the late response!

Did you figure this out? It sounds a bit like the menu items appear below the navigation bar. Just to validate, maybe try setting the navigation bar `translucent` property to false and see if the menu items appear.

**Comment by kmyn** [comment]
It works now after turning off translucent. Thanks!
