### ISSUE TITLE
RTL Support 

### ISSUE THREAD

**Issue by ahmedraad** [rechsteiner/Parchment#161]
Hi There
I've been used this amazing library, but i'm having a little issue with direction in Arabic localization, so it's there any method to make start index from right side ?

![screen shot 2018-04-01 at 4 03 09 pm](https://user-images.githubusercontent.com/17860965/38173372-3a890920-35c6-11e8-9a01-191c1004845b.png)

Thanks

**Comment by rechsteiner** [comment]
Hi! You can select items manually using the `select(index:)` method. In your case, you can probably do something like this:

```Swift
switch UIView.userInterfaceLayoutDirection(for: view.semanticContentAttribute) {
    case .leftToRight:
      pagingViewController.select(index: 0)
    case .rightToLeft:
      pagingViewController.select(index: 3)
}
```

Let me know if that works for you. I will also look into adding RTL support directly to Parchment 👍

**Comment by rechsteiner** [comment]
@ahmedraad did you get this working?

**Comment by Athenay** [comment]
Hi @rechsteiner ! 
Your answer works for changing selection of menu item in RTL views and for situation which the number of menu items cover entire of the screen, but i have just two tab and need to insert them on screen from right to left (i dont want to fix them to cover entire screen). do you have any idea about this situation ?

**Comment by ahmedraad** [comment]
Hi @rechsteiner 
sorry i was too busy, i've tried this way, it's work but i have a lot of filtering & inserting & removing data , so should i do more logic and i don't want that 
i hope you can fix the layout 
Thanks

**Comment by Pratik948** [comment]
Hey guys, I have workaround for this RTL languages. I am using datasource and delegates for `PagingViewController` and I have an array of titles for all items. when my app uses RTL semantics I reverse the array using something like this
```
if UIView.appearance().semanticContentAttribute == .forceRightToLeft {
        self.items.reverse()
}
```
 and when the paging controller is added to view controller I set its index to last like this
```
if UIView.appearance().semanticContentAttribute == .forceRightToLeft {
        self.pagingViewController.select(index: self.items.count - 1, animated: false)
}
```

I hope this helps other people too

And @rechsteiner thank you so much for your awesome contribution to community

**Comment by aerow69** [comment]
I have second workaround. You can transform PagingViewController, PagingCell and embeded view controllers by:
`view.transform = CGAffineTransform(scaleX: -1, y: 1)`

**Comment by rechsteiner** [comment]
The new version with proper RTL support is finally out now! https://github.com/rechsteiner/Parchment/releases/tag/v3.0.0
