### ISSUE TITLE
Presenting Parchment navigation as a Modal from main root view controller, will there be memory leak?

### ISSUE THREAD

**Issue by steve21124** [rechsteiner/Parchment#166]
Presenting Parchment navigation as a Modal from main root view controller, when dismissing it, will there be memory leak?

By looking at this line, it initialize it lazily. If the Parchment dismissed, then each of these view controller need to be set to nil. right?
https://github.com/rechsteiner/Parchment/blob/7e74baa090e53fbe1512b751784c3aac95359152/DelegateExample/ViewController.swift#L50

In other words, does pagingViewController need to be set to nil before dismissing its parent?

**Comment by rechsteiner** [comment]
The view controllers are only referenced by the `PagingViewController` class, and when you dismiss it they should all be deallocated. You should not have to set anything to nil manually. You can test this pretty easily by logging something from the `deinit` method of the view controllers you are showing. Let me know if you are actually seeing any memory leaks!

**Comment by steve21124** [comment]
thanks. it seems there is no memory leak. the memory leak cause by other issues but not in Parchment. Thanks
