### ISSUE TITLE
How to Show Some part next viewcontroller in the present viewcontroller 

### ISSUE THREAD

**Issue by satheeshkumar8186** [rechsteiner/Parchment#169]
Hi
How to show some part of Some part next viewcontroller in the present viewcontroller and How to reduce the menuItemSize size and to show the full content of the viewcontroller.

**Comment by rechsteiner** [comment]
Hi! I'm not sure if I understand exactly what you are trying to achieve. Could you provide some more details?

**Comment by satheeshkumar8186** [comment]
Hi  I will give one example say suppose We have to show 4vc a,b,c,d .at the first index we will  show "a"   instead of that we have to show "a" with that we have to show some part of "b" with "a",when we scroll to b we have to show "b" and some part of "c".
![screen shot 2018-04-16 at 10 37 28 am](https://user-images.githubusercontent.com/37365685/38790991-8e798e5e-4162-11e8-95da-c85977af0577.png)

**Comment by rechsteiner** [comment]
Sorry, I don't think that's possible at the moment. Parchment only supports showing one view controller at the time, but I'm working on adding support for using the menu header as a standalone view, which would make it possible to do something like that.

**Comment by satheeshkumar8186** [comment]
ok Thanks
