### ISSUE TITLE
pagingViewController.reloadData()

### ISSUE THREAD

**Issue by igorkaryi** [rechsteiner/Parchment#170]
Hi, self.pagingViewController.reloadData() It does not work if the number of items does not change. If count items > or < - reload work

**Comment by rechsteiner** [comment]
Hi! It seems to work fine here. What kind of `PagingItem` type are you using? Could it have something  to do with your `Equatable` implementation?

**Comment by igorkaryi** [comment]
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForIndex index: Int) -> UIViewController {
        return NewsTableViewController(news: objectsArray[index].newsTitle, date: objectsArray[index].newsDate)
    }

not work after self.pagingViewController.reloadData()

work only 
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemForIndex index: Int) -> T {
        return PagingIndexItem(index: index, title: objectsArray[index].newsSubjects!) as! T
    }

**Comment by Vashum** [comment]
It does not work for me. In my case for a workaround, instead of reloading, removing pagingViewcontroller and adding back works!

**Comment by rechsteiner** [comment]
Looks like there is an bug with reloading if you are not updating the view controller instances as well: #189. I guessing this is what's causing these issues as well. I will get that fixed as soon as possible 🙂

**Comment by rechsteiner** [comment]
Should be fixed in #201! @igorkaryi can you target the master branch and see if it works now?

**Comment by rechsteiner** [comment]
This is released as part of version `1.3.0` now. Let me know if you're still seeing any issues with this!
