### ISSUE TITLE
Currently change `indicatorClass` has no effect.

### ISSUE THREAD

**Issue by Skogetroll** [rechsteiner/Parchment#176]
# Problem

Setting custom indicator class via `PagingViewController.setter:indicatorClass` has no effect. `PagingViewController` keeps using default `PagingIndicatorView`. 

# Source of problem

Custom `indicatorClass` is getting registered in collection view in `PagingCollectionViewLayout.registerDecorationViews`, but this function is called only via `PagingViewController.configureCollectionViewLayout` from `PagingViewController.init` and from `PagingViewController.didSet:menuLayoutClass`.  All the other option changes, including `indicatorClass`, have to effect.

# Proposed solution

_Currently, temporally, as hotfix hack, one can force registration of `indicatorClass` by resetting `PagingViewController.menuLayoutClass` which in `didSet` causes call of `PagingViewController.configureCollectionViewLayout` and `PagingCollectionViewLayout.registerDecorationViews`._

_**But proper solution should make `PagingViewController.setter:indicatorOptions` to cause  `PagingCollectionViewLayout.registerDecorationViews` directly.**_

**Comment by rechsteiner** [comment]
Thanks for the detailed report! I'll look into getting that fixed as soon as possible 👍

**Comment by Skogetroll** [comment]
Oh, `borderClass` setter may require to fire same update.

**Comment by rechsteiner** [comment]
Should be fixed on #191 now 🙂 Will release a new version soon!
