### ISSUE TITLE
Possible to show multiple colours for different titles of pagingviewcontroller? 

### ISSUE THREAD

**Issue by etabhijitgite** [rechsteiner/Parchment#177]
Hello, Is it possible to show different colours for multiple tabs of paging view controller?

**Comment by rechsteiner** [comment]
Yes, this is definitely possible!

The implementation depends a bit on what you are trying to achieve. If you can base the color on the index of the item you can just create a custom menu cell subclass like this:

```Swift
class CustomPagingCell: PagingTitleCell {
  override func setPagingItem(_ pagingItem: PagingItem, selected: Bool, options: PagingOptions) {
    super.setPagingItem(pagingItem, selected: selected, options: options)
    
    if let item = pagingItem as? PagingIndexItem {
      switch item.index {
      case 0:
        contentView.backgroundColor = .red
      case 1:
        contentView.backgroundColor = .blue
      case 2:
        contentView.backgroundColor = .green
      default:
        contentView.backgroundColor = .white
      }
    }
  }
}

...

let pagingViewController = FixedPagingViewController(viewControllers: viewControllers)
pagingViewController.menuItemClass = CustomPagingCell.self
```

Another approach is to create a custom `PagingItem` that will hold the color for each menu items. Then you have to use `PagingViewController` directly, and have to setup your own data source using `PagingViewControllerDataSource`. You can take a look at the `UnplashExample` on how to achieve that. Let me know if you are stuck and I can provide an example implementation for that as well 🙂

**Comment by rechsteiner** [comment]
Closing this for now, but feel free to open if you have any more questions 🙂

**Comment by schenkty** [comment]
Hey @rechsteiner, is this still possible? I can't seem to find `menuItemClass`. I don't exactly have to use this but I need a way to make certain items stand out to the user as I'm using this for a form
