### ISSUE TITLE
how print page index item? After reload i want return index which was before. I throw to the top of the list

### ISSUE THREAD

**Issue by igorkaryi** [rechsteiner/Parchment#179]

**Comment by igorkaryi** [comment]
selected index

**Comment by igorkaryi** [comment]
au, please

**Comment by rechsteiner** [comment]
Hi @igorkaryi! It depends a bit on your implementation. If you are using `FixedPagingViewController`, you can get the selected index by implementing `PagingViewControllerDelegate` like this:

```Swift
extension ViewController: PagingViewControllerDelegate {
  func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    didScrollToItem pagingItem: T,
    startingViewController: UIViewController?,
    destinationViewController: UIViewController, transitionSuccessful: Bool) {
    
    let viewControllers = self.pagingViewController.viewControllers
    
    if transitionSuccessful {
      print("index: ", viewControllers.index(of: destinationViewController))
    } else if let startingViewController = startingViewController {
      print("index: ", viewControllers.index(of: startingViewController))
    }
  }
}
```

Another option is to get the index by doing `pagingViewController.visibleItems.index(of: pagingItem)`, but that might not be correct if you have a lot of items.

Does that work for you?

**Comment by igorkaryi** [comment]
extension ViewController: PagingViewControllerDataSource {
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemForIndex index: Int) -> T {
        return PagingIndexItem(index: index, title: objectsArray[index].newsSubjects!) as! T
    }
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForIndex index: Int) -> UIViewController {

        return NewsTableViewController(news: objectsArray[index].newsTitle, date: objectsArray[index].newsDate)
    }
    
    func numberOfViewControllers<T>(in: PagingViewController<T>) -> Int {
        return objectsArray.count
    }
}

extension ViewController: PagingViewControllerDelegate {
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat? {
        guard let item = pagingItem as? PagingIndexItem else { return 0 }
        let insets = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
        let size = CGSize(width: CGFloat.greatestFiniteMagnitude, height: pagingViewController.menuItemSize.height)
        let attributes = [NSAttributedStringKey.font: pagingViewController.font]
        let rect = item.title.boundingRect(with: size,
                                           options: .usesLineFragmentOrigin,
                                           attributes: attributes,
                                           context: nil)
        
        let width = ceil(rect.width) + insets.left + insets.right
        
        if isSelected {
            return width * 1.5
        } else {
            return width
        }
    }
    
}

**Comment by igorkaryi** [comment]
I use it

**Comment by rechsteiner** [comment]
Did you try to implement the `didScrollToItem` to method I mentioned above?

**Comment by bizibizi** [comment]
https://github.com/rechsteiner/Parchment/issues/199

**Comment by rechsteiner** [comment]
Closing this for now. Let me know if you still need any help to get this working!
