### ISSUE TITLE
Use on UIView instead of UIViewController?

### ISSUE THREAD

**Issue by cwestMobile** [rechsteiner/Parchment#180]
Is this possible to use as a segmented control for a subview of a View Controller instead of the whole thing?

Thanks.

**Comment by rechsteiner** [comment]
Hi! I'm not sure if I understand exactly what you mean. Do you mean using only the menu header and not the swiping page view controllers?

**Comment by cwestMobile** [comment]
I am hoping to use it to page through subviews of a view controller. So, the top half of the view controller would be static content...yet the bottom half would use the menu header to swipe through subviews. If it still isn't clear I'll go ahead and take a video.

**Comment by cwestMobile** [comment]
Does that make sense or would you like a video showing you what I'm hoping for?

**Comment by cwestMobile** [comment]
Hellooo?

**Comment by rechsteiner** [comment]
Yeah, maybe a video would make it bit more clear. It's not possible to use the menu header as a standalone view if that's what you need. But I'm working on adding support for that 🙂

**Comment by cwestMobile** [comment]
I appreciate it, no worries. i ended up implementing a custom solution that works. i'll keep a look out for that update though. cheers!
