### ISSUE TITLE
Transparent menu

### ISSUE THREAD

**Issue by Silvia4** [rechsteiner/Parchment#181]
Hi,
I'm trying to make the FixedPagingViewController transparent, so I can see the color of the view below (that has a gradient). 
I've added all these lines without success:
```
        pagingViewController.backgroundColor = UIColor.clear
        pagingViewController.menuBackgroundColor = UIColor.clear
        pagingViewController.selectedBackgroundColor = UIColor.clear
        pagingViewController.view.backgroundColor = UIColor.clear
```
Can you help me please?
Thanks

**Comment by Silvia4** [comment]
Unfortunately no, it's completely white.
This is what I've written:

`        let pagingViewController = TransparentPagingViewController(viewControllers: [
            firstViewController,
            secondViewController
            ])
        
        addChildViewController(pagingViewController)
        view.addSubview(pagingViewController.view)
        pagingViewController.didMove(toParentViewController: self)
        pagingViewController.view.translatesAutoresizingMaskIntoConstraints = false
        pagingViewController.collectionView.translatesAutoresizingMaskIntoConstraints = false

        pagingViewController.menuInteraction = .none
        pagingViewController.font = UIFont.systemFont(ofSize: 18, weight: UIFont.Weight.light)
        pagingViewController.selectedFont = UIFont.systemFont(ofSize: 18, weight: UIFont.Weight.medium)
        pagingViewController.indicatorOptions = .visible(height: 3, zIndex: Int.max, spacing: UIEdgeInsets.zero, insets: UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 10))

        pagingViewController.indicatorColor = UIColor.white
        pagingViewController.borderOptions = .hidden
        pagingViewController.textColor = UIColor.gray
        pagingViewController.selectedTextColor = UIColor.white
        pagingViewController.backgroundColor = UIColor.clear
        pagingViewController.menuBackgroundColor = UIColor.clear
        pagingViewController.selectedBackgroundColor = UIColor.clear
        pagingViewController.view.backgroundColor = UIColor.clear
        
        NSLayoutConstraint.activate([
            pagingViewController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            pagingViewController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            pagingViewController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            pagingViewController.view.topAnchor.constraint(equalTo: view.topAnchor),
            
            pagingViewController.collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            pagingViewController.collectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            pagingViewController.collectionView.topAnchor.constraint(equalTo: view.topAnchor),
            pagingViewController.collectionView.heightAnchor.constraint(equalToConstant: pagingViewController.options.menuItemSize.height)
            ])`

**Comment by bizibizi** [comment]
@Silvia4 @rechsteiner solved: 

        pagingViewController.backgroundColor = .clear
        pagingViewController.menuBackgroundColor = .clear
        pagingViewController.borderColor = .clear
        pagingViewController.textColor = .white
        pagingViewController.indicatorColor = ._blueLight
        pagingViewController.selectedTextColor = .white
        pagingViewController.selectedBackgroundColor = .clear
        pagingViewController.view.backgroundColor = .clear
        **pagingViewController.collectionView.backgroundColor = .clear**

**Comment by rechsteiner** [comment]
You need to actually subclass `PagingView` like I mentioned above. Setting the constraints afterwards will just add an extra set of constraints that will probably just break the existing ones.

**Comment by rechsteiner** [comment]
@Silvia4 @bizibizi did you get this working?

**Comment by bizibizi** [comment]
@rechsteiner yes, check my code above

**Comment by LinusGeffarth** [comment]
The only relevant part would be:

    pagingViewController.collectionView.backgroundColor = .clear

**Comment by rechsteiner** [comment]
@Silvia4 closing this for now, but feel free to re-open if you're still having issues with this 🙂
