### ISSUE TITLE
Menu height

### ISSUE THREAD

**Issue by Silvia4** [rechsteiner/Parchment#182]
Hi, 
I have another question. I want the menu a little bit taller, so I've use this line of code:
`        pagingViewController.menuItemSize = .sizeToFit(minWidth: 150, height: 60)
`

The problem is that the labels are now not vertically aligned, but at the bottom of the menu.
How can I fix this?
Thanks!

**Comment by LinusGeffarth** [comment]
This was actually fixed in 1.0.4, I believe. Are you up-to-date?

**Comment by rechsteiner** [comment]
Yeah, this sounds like the bug that was fixed in #155 and released in version 1.2.0.

@Silvia4 @bizibizi are you sure you are using version 1.2.0? If so, could you provide some more details on your implementation. I'm not seeing this bug anymore.

**Comment by bizibizi** [comment]
@rechsteiner just basic implementation: 


class PagingViewController: FixedPagingViewController {
    
    override init(viewControllers: [UIViewController]) {
        super.init(viewControllers: viewControllers)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
    
    func setup() {
        font = UIFont._medium(20)
        selectedFont = UIFont._medium(20)
        indicatorOptions = .visible(height: 2, zIndex: Int.max, spacing:  UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20), insets: UIEdgeInsets.zero)
        //        menuItemSize = .sizeToFit(minWidth: 150, height: 60) //does not work for now
        backgroundColor = .clear
        menuBackgroundColor = .clear
        borderColor = .clear
        textColor = UIColor.white.withAlphaComponent(0.5)
        indicatorColor = ._blueLight
        selectedTextColor = .white
        selectedBackgroundColor = .clear
        view.backgroundColor = .clear
        collectionView.backgroundColor = .clear
    }
}

**Comment by bizibizi** [comment]
yes, now it works
