### ISSUE TITLE
Delegate method for paging menu item tap

### ISSUE THREAD

**Issue by LinusGeffarth** [rechsteiner/Parchment#185]
I would like to detect a tap on a menu item.

### Why can't I use the already existing `willScrollToItem:` method?

Because I want to especially detect the tap when tapped on the already-selected item to then pop all navigation child controllers back to the first, like it is natively implemented in tab bar controllers.

Would this be possible?

---

<sub>I thought about using a `UITapGestureRecognizer` in my custom paging cell, however, this isn't the most elegant solution and I'm thinking this might be a valuable feature for other developers in the future.</sub>

**Comment by rechsteiner** [comment]
Yes! You can subclass `PagingViewController` and override `collectionView:didSelectItem`. Just remember to call super 🙂

```Swift
class CustomPagingViewController: FixedPagingViewController {
  override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    super.collectionView(collectionView, didSelectItemAt: indexPath)
  }
}
```

**Comment by rechsteiner** [comment]
And if you need to actual `PagingItem` you can use `visibleItems.items[indexPath.item]`
