### ISSUE TITLE
how to use it for swift3?

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#186]

**Comment by bizibizi** [comment]
@rechsteiner

**Comment by bizibizi** [comment]
okay, i fixed the code. the bug only in 2 lines (77-78) PagingOptions.swift

**Comment by gchriswill** [comment]
I'm also interested in use Parchment with Swift 3 and Xcode 9.2 ... 
@bizibizi Have to found a solution and/or approach for this issue?

**Comment by rechsteiner** [comment]
It should work with Swift 3 now, if you target the master branch. Will release a new version soon 👍

**Comment by gchriswill** [comment]
@rechsteiner Thanks!

**Comment by bizibizi** [comment]
@rechsteiner well, it does not work https://imgur.com/9hmU0ha

**Comment by bizibizi** [comment]
works with     pod 'Parchment', :git => 'https://github.com/rechsteiner/Parchment.git', :branch => 'master'
