### ISSUE TITLE
Inset for menu item does not work

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#187]
https://image.ibb.co/i5DsGx/New_Note.jpg

        indicatorOptions = .visible(height: 2, zIndex: Int.max, spacing: UIEdgeInsets.zero, insets: UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 10))

indicator is not equal from left and right

**Comment by rechsteiner** [comment]
Yeah, that looks like how it's meant to work. The `insets` property will only add insets to indicator view around the edges of the menu. If you want to inset the indicator view equally on for each menu item, you can set the `spacing` property. Does that work for you?

**Comment by bizibizi** [comment]
yes, it works

        .visible(height: 2, zIndex: Int.max, spacing:  UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20), insets: UIEdgeInsets.zero)
