### ISSUE TITLE
Top menu to filter my View.

### ISSUE THREAD

**Issue by jeremiasdsa** [rechsteiner/Parchment#188]
Hi @rechsteiner,

I want to use your top menu fo filter the content on my tableView as the following image:
Is that possible to select an item on top menu and says reloadData to my table?

<img width="310" alt="screen shot 2018-04-29 at 12 16 34" src="https://user-images.githubusercontent.com/9071775/39408128-5593949a-4ba8-11e8-97d3-112d970bfe6e.png">

**Comment by rechsteiner** [comment]
Hi @jeremiasdsa! Do you mean using the menu header as a standalone view and just having a single table view below instead of the paging view controllers? If so, that's unfortunately not possible at the moment. But I'm working on adding support for as we speak 🙂
