### ISSUE TITLE
Issue with update titles

### ISSUE THREAD

**Issue by NBibikov** [rechsteiner/Parchment#189]
Hi! Thanks for nice library. Please look in my example and take me information about this way for update titles - maybe am i doing something wrong?

I want update titles, but after reload with 'reloadData()' i have got old and new cells.

[UpdateTitles.zip](https://github.com/rechsteiner/Parchment/files/1960751/UpdateTitles.zip)

**Comment by rechsteiner** [comment]
That definitely looks like a bug 😕 It seems to be an issue with reloading data when you are not updating the view controllers as well. If you try to create some new view controllers and update `self.tabControllers` before reloading it works just fine.

I will get that fixed as soon as possible!

**Comment by NBibikov** [comment]
thanks for answer. waiting for fix

**Comment by bizibizi** [comment]
i have it as well, waiting for fix, i hope you have time to make it asap

**Comment by rechsteiner** [comment]
This should be fixed in #201 now! @NBibikov can you target the master branch and double check that it's working for you as well?

**Comment by rechsteiner** [comment]
Closing this as it seems to be working fine now. Please re-open if you're still seeing any issues!
