### ISSUE TITLE
Allow scrolling in the menu items header

### ISSUE THREAD

**Issue by rechsteiner** [rechsteiner/Parchment#19]
Currently, the menu items only have a swipe gesture to switch between pages. It would be nice to be able to scroll freely inside the menu items collection view.

**Comment by IVANKRUPSKI** [comment]
Hey, Martin!

Hope you are Ok. Any plans to finalise proper scrolling in the menu items header?

I applied temporarily, as you recommended,
pagingViewController.collectionView.isScrollEnabled = true
pagingViewController.collectionView.showsHorizontalScrollIndicator = false

But, as you wrote here, there is a bug when there are too many items in the menu, which sometimes is the case with our app.
![image](https://user-images.githubusercontent.com/16180201/27527218-d541621c-5a4a-11e7-9096-383ef55d4391.png)

**Comment by rechsteiner** [comment]
Hey! Sorry that this is taking so long–I kinda got stuck on some tricky edge-cases. I plan to spend some more time on this during the next couple of weeks, so hopefully I'll get this done pretty soon 🙌

**Comment by IVANKRUPSKI** [comment]
Great! Thanks!

**Comment by rechsteiner** [comment]
Hey!  Getting very close to releasing this now ✌️You can check out the `scrolling` branch if you want to try it out right now. You should be able to point both carthage and CocoaPods to a specific branch from your project. Let me know if you need any help with that.

I had to make quite a lot of changes to get this working properly, and there are some breaking changes in this release. If you're using a custom `PagingItem` implementation you now need to conform to both `Hashable` and `Comparable`. I haven't updated the documentation yet, so let me know if you need any help with that as well.

I still need to fix one bug before I can release a new version. When setting the menu item width using `PagingViewControllerDelegate` the collection view layout sometimes gets in a weird state and crashes.  I'll try to fix this as soon as possible!

And let me know if you find any bugs 🙌

**Comment by rechsteiner** [comment]
Fixed the issue with the width delegate, so it should be ready to use now. Need to do a bit more testing before releasing the new version, but it looks like everything should be working fine now ✌️

**Comment by rechsteiner** [comment]
New version is released now!

**Comment by IVANKRUPSKI** [comment]
Thanks you, Martin!

Very much appreciated. We'll upgrade to new release shortly, and let you know if any.
