### ISSUE TITLE
Under navigation bar?

### ISSUE THREAD

**Issue by cwestMobile** [rechsteiner/Parchment#193]
The item menu shows underneath the navigation bar. Are there any solutions other than setting the following...

` self.navigationController?.navigationBar.isTranslucent = false `

this is a very limiting solution and i'm wondering if there is someway to just move the selection down?

**Comment by rechsteiner** [comment]
The default behavior of navigation controller is to show content below the navigation controller. Try setting that navigation bar to opaque or changing the `edgesForExtendedLayout` property. If you are using Storyboard you can take a look at the Example target.

**Comment by cwestMobile** [comment]
I guess what i'm really hoping for is for it to not pin to the top of a view automagically. I would like to be able to designate a top/bottom/side "padding" value. If that isn't on the roadmap maybe i'll take a crack at it and let you know how it goes.

**Comment by rechsteiner** [comment]
Closing this for now. Feel free to re-open if you're still having issues with this 🙂

**Comment by asbis** [comment]
If someone still have this problem like i did:

Add this function in "viewDidLoad" Where you add "pagingViewController":
edgesForExtendedLayout = []

**Comment by aviciida** [comment]
@VishnuMU 
Thank you so much for your suggestion.
Been trying to figure out the same problem for hours, and finally got that right with your approach.🙌

**Comment by hslightnin** [comment]
Any new workarounds?

**Comment by blusewang** [comment]
`self.navigationController?.navigationBar.isTranslucent = false`
OMG! It saved me!
thanks!
