### ISSUE TITLE
is it possible to set fixed width to indicator?

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#194]
Let's say I want that all my indicators have 30pt width @rechsteiner 
And rounded corners will be great as well

**Comment by bizibizi** [comment]
my solution: 

        let width: CGFloat = 30
        let count: CGFloat = CGFloat(viewControllers.count)
        let leftRightSpacing = ((UIScreen.main.bounds.width / count) - width) / 2
        indicatorOptions = .visible(height: 3, zIndex: Int.max, spacing:  UIEdgeInsets(top: 0, left: leftRightSpacing, bottom: 0, right: leftRightSpacing), insets: UIEdgeInsets.zero)

**Comment by rechsteiner** [comment]
It's not built in as a default behaviour, but you can set the `indicatorClass` to your own subclass of `PagingIndicatorView`. Something like this should work to get fixed width and corner radius:

```Swift
class CustomIndicator: PagingIndicatorView {
  
  private let roundedView: UIView
  
  override init(frame: CGRect) {
    roundedView = UIView(frame: .zero)
    super.init(frame: frame)
    addSubview(roundedView)
    roundedView.translatesAutoresizingMaskIntoConstraints = false
    
    NSLayoutConstraint.activate([
      roundedView.topAnchor.constraint(equalTo: topAnchor),
      roundedView.bottomAnchor.constraint(equalTo: bottomAnchor),
      roundedView.centerXAnchor.constraint(equalTo: centerXAnchor),
      roundedView.widthAnchor.constraint(equalToConstant: 50),
    ])
  }
  
  required init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  override open func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
    super.apply(layoutAttributes)
    backgroundColor = .clear
    if let attributes = layoutAttributes as? PagingIndicatorLayoutAttributes {
      roundedView.backgroundColor = attributes.backgroundColor
      roundedView.layer.cornerRadius = attributes.frame.height / 2
    }
  }
  
}
```

Then set the indicator class like this:

```Swift
pagingViewController.indicatorClass = CustomIndicator.self
```

Does that work for you?

**Comment by bizibizi** [comment]
i am using my code above because it already works :)

**Comment by rechsteiner** [comment]
Sounds good. If you need rounded corners though, you have to do something like the solution above.

**Comment by bizibizi** [comment]
yes, thank you!

**Comment by luongchautuan** [comment]
Hi sir, 

I have added a custom View like your code above for Indicator but the indicator color still default. Can you help me?

`class PagingIndicatorCusView: PagingIndicatorView {
    
    private let roundedView: UIView
    
    override init(frame: CGRect) {
        roundedView = UIView(frame: .zero)
        
        super.init(frame: frame)
        addSubview(roundedView)

        roundedView.backgroundColor = UIColor.red
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override open func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        super.apply(layoutAttributes)
        backgroundColor = UIColor.red
        if let attributes = layoutAttributes as? PagingIndicatorLayoutAttributes {
                        roundedView.backgroundColor = backgroundColor
            roundedView.layer.cornerRadius = attributes.frame.height / 2
        }
    }
    
}`

**Comment by VishnuMU** [comment]
@luongchautuan 

The below code is for red color based on @rechsteiner 's answer above 
`class CustomIndicator: PagingIndicatorView {
    
    private let roundedView: UIView
    
    override init(frame: CGRect) {
        roundedView = UIView(frame: .zero)
        super.init(frame: frame)
        addSubview(roundedView)
        roundedView.translatesAutoresizingMaskIntoConstraints = false
        
        if #available(iOS 9.0, *) {
            NSLayoutConstraint.activate([
                roundedView.topAnchor.constraint(equalTo: topAnchor),
                roundedView.bottomAnchor.constraint(equalTo: bottomAnchor),
                roundedView.centerXAnchor.constraint(equalTo: centerXAnchor),
                roundedView.widthAnchor.constraint(equalToConstant: 50),
                ])
        } else {
            // Fallback on earlier versions
        }
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override open func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        super.apply(layoutAttributes)
        backgroundColor = .clear
        if let attributes = layoutAttributes as? PagingIndicatorLayoutAttributes {
            roundedView.backgroundColor = .red  // only place I have changed
            roundedView.layer.cornerRadius = attributes.frame.height / 2
        }
    }
    
}`

**Comment by VishnuMU** [comment]
@luongchautuan May be you forgot to set `pagingViewController.indicatorClass = CustomIndicator.self`

**Comment by luongchautuan** [comment]
` let pagingViewController = PagingViewController<PagingIndexItem>()
        pagingViewController.indicatorClass = PagingIndicatorCusView.self
        pagingViewController.dataSource = self
        pagingViewController.delegate = self`

I have already set them but not working at all
