### ISSUE TITLE
Horizontal padding between pages

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#197]
Is it possible to setup this property?
Like this one https://stackoverflow.com/questions/20694679/horizontal-padding-between-uipageviewcontroller-child-view-controllers

**Comment by rechsteiner** [comment]
We're using `EMPageViewController` as a replacement for `UIPageViewController` and that's not something that's supported. I'm working on moving the menu items into a standalone component, which means you could roll you own implementation of the page view controller that supports that.

**Comment by crabman448** [comment]
I'm also wondering if it is possible to achieve such behaviour

![](http://qaru.site/img/49b6c0c843e74eb1e7ec60a607f84148.png)

Thanks for the library 👍

**Comment by rechsteiner** [comment]
@crabman448 It's not possible with the current version, but as soon as version 2.0 (#243) is done you should be able to use any custom type of page view controller 🙂

**Comment by rechsteiner** [comment]
Version 2.0 is now released and makes it possible to use the `PagingMenuView` as a standalone component. This should allow you to use it with any page view controller and not just `EMPageViewController`. You need to implement the `PagingMenuDelegate` delegate methods and update your page view controller based on that. When user scrolls in your page view controller (or table view for that matter), you need to call the following methods on the `PagingMenuView` to update it:

```Swift
/// Call this method when the parent view controller viewDidAppear method is called.
func viewAppeared()
/// Call this method when the parent view controller viewWillTransitionToSize method is called.
func transitionSize()
/// Call this method when the user scrolls in your page view controller.
func contentScrolled(progress: CGFloat)
/// Call this method when the user has finished scrolling.
func contentFinishedScrolling()
```

Let me know if you have any issues with getting this working. I will look into setting up an example project for this in the future.
