### ISSUE TITLE
is it possible to make menu vertically scrollable with VCs as well?

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#198]

**Comment by rechsteiner** [comment]
Hi! Sorry, this is not currently possible. I will consider adding support for this in version 2.0 🙂

**Comment by bizibizi** [comment]
well, i already did that and also added header as imageView above menu. And menu has 3 VCs. So, if you will plan to add this, let me know - i will share the code

**Comment by LinusGeffarth** [comment]
@bizibizi, you should open a pull request with your code so @rechsteiner can easily implement it as soon as possible

**Comment by rechsteiner** [comment]
@bizibizi I think I maybe misunderstood your original question. Could we provide a bit more details on what you are trying achieve? Are you doing something like this #150?

**Comment by rechsteiner** [comment]
@bizibizi any updates on this?

**Comment by rechsteiner** [comment]
Closing this for now, but feel free to re-open if you have any updates 🙂

**Comment by VishnuMU** [comment]
@rechsteiner I'm trying to implement a UI like this. I feel this page was for the same need.
Do you think we will be able to implement this as well with Parchment?

![screen shot 2018-07-29 at 9 05 52 am](https://user-images.githubusercontent.com/15333022/43505150-aa328b68-956e-11e8-8ab2-83607309f63e.png)
