### ISSUE TITLE
Bug: Transition to next item during Transition

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#202]
Let's say I have 3 menu items.
I switch by swipe from 1 to 2. During that Transition I swipe to 3.
So, if I do that - I have several different bugs after that. The page's content can become invisible, the page can display content from different page. 
After several swipes with slow speed it returns to normal. 
I can not be reproduced by clicking menu items. (Looks like it locked if transition in a progress).
Are there any ways to solve that?
I realize that finding that bug can be an issue. But maybe there are some ways how to stop it? Like disabling transition to next item if transition in a progress?

And also:
I switch by swipe from 1 to 2. During that Transition I swipe to 3.
The content from 2nd page disappears and it replaced with content for 3rd page. It does not looks good as well

**Comment by rechsteiner** [comment]
Hmm, I'm not able to reproduce the bug you're seeing. Are you able to reproduce this when running the Example target or is this specific to your implementation?

**Comment by LinusGeffarth** [comment]
I experienced this too until the latest update.

**Comment by rechsteiner** [comment]
@LinusGeffarth are you seeing this bug in the `Example` target as well?

**Comment by LinusGeffarth** [comment]
I'm not sure. Like I said, after the latest update, I don't see this bug anymore.
