### ISSUE TITLE
how on one controller add 2 pageViewController?

### ISSUE THREAD

**Issue by igorkaryi** [rechsteiner/Parchment#203]

**Comment by rechsteiner** [comment]
I'm not sure if I understand exactly what you mean. Are you talking about adding two instances of `PagingViewController` (two menus and two swipable page view controllers)?

**Comment by rechsteiner** [comment]
@igorkaryi any updates on this?

**Comment by rechsteiner** [comment]
Closing this for now, but feel free to re-open 👍
