### ISSUE TITLE
i'm use PagingViewControllerDataSource. How move page items to down screen? so that the table is above it

### ISSUE THREAD

**Issue by igorkaryi** [rechsteiner/Parchment#204]

**Comment by rechsteiner** [comment]
Hi! You need to subclass `PagingView` and override the constraints to move the menu to the bottom. Here's an example:

```Swift
class CustomPagingView : PagingView {
  override func setupConstraints() {
    pageView.translatesAutoresizingMaskIntoConstraints = false
    collectionView.translatesAutoresizingMaskIntoConstraints = false
    
    NSLayoutConstraint.activate([
      pageView.leadingAnchor.constraint(equalTo: leadingAnchor),
      pageView.trailingAnchor.constraint(equalTo: trailingAnchor),
      pageView.topAnchor.constraint(equalTo: collectionView.topAnchor),
      pageView.bottomAnchor.constraint(equalTo: bottomAnchor),
      
      collectionView.leadingAnchor.constraint(equalTo: leadingAnchor),
      collectionView.trailingAnchor.constraint(equalTo: trailingAnchor),
      collectionView.bottomAnchor.constraint(equalTo: bottomAnchor),
      collectionView.heightAnchor.constraint(equalToConstant: options.menuItemSize.height),
    ])
  }
}

class CustomPagingViewController : PagingViewController<PagingIndexItem> {
  override func loadView() {
    view = CustomPagingView(
      options: options,
      collectionView: collectionView,
      pageView: pageViewController.view)
  }
}
```

Does that work for you?

**Comment by rechsteiner** [comment]
@igorkaryi did you manage to get this working?

**Comment by rechsteiner** [comment]
Closing this, but let me know if you need any more help getting  this working!

**Comment by lm2343635** [comment]
Why not add it to your library? so that developers can set the menu position directly.

**Comment by Smiller193** [comment]
can you reopen it because this isn't working for me

**Comment by Silvia4** [comment]
Hi,
this isn't working for me too. Can you reopen this issue and help us? Thanks

**Comment by rechsteiner** [comment]
Can you provide some more details on what's not working? The above suggestion seems to work just fine here.

**Comment by Smiller193** [comment]
@rechsteiner on an iphone 8 plus are the buttons that we use for paging supposed to look to far to the left or have padding that makes it not look centered.

**Comment by Smiller193** [comment]
let me show a picture of what I'm talking about it seems to only be present on the bigger iPhones because on the iPhone x and 8 I don't notice it 

<img width="346" alt="screen shot 2018-09-18 at 2 01 23 pm" src="https://user-images.githubusercontent.com/16108750/45706868-5d79ba00-bb4b-11e8-8fee-6277669708c1.png">

**Comment by rechsteiner** [comment]
@Smiller193 I don't understand how that is related to positioning the menu to the bottom of the screen. Are you having issues with overwriting `setupConstraints`? Can you make sure that you are actually constraining the menu view to each side without any padding? If you think this is an issue with Parchment, please open a separate issue 🙂

**Comment by Smiller193** [comment]
oh sorry lol  yeah this had nothing to do with adding the menu to the bottom

**Comment by Silvia4** [comment]
Hi, I'm sure I'm not setting the constraints properly.. I have a view controller with a label a table view and other things, all constrain to the "safe area" margins. If I put the menu on the top everything is working fine, all the controls are properly shifted down. If I put the menu at the bottom, with your suggested constraints, I can see it at the bottom but all the other controls aren't shown, and xcode gives me a lot of errors about breaking constraints. I don't understand what I have to change, can you help me please? Sorry I'm a bit of a newbie in settings constraints.

**Comment by rechsteiner** [comment]
@Silvia4 it's a bit hard without to say what's wrong without seeing your implementation. This isn't really related to this issue though, so if you still need help with this feel free to open a separate issue 🙂
