### ISSUE TITLE
Disappear on scroll?

### ISSUE THREAD

**Issue by cwestMobile** [rechsteiner/Parchment#205]
Is it possible to have the menu hide when scrolling the view?

An example is the paging view controllers are all tableview controllers and upon scrolling the tableviews can we hide the menu?

Thanks!

**Comment by rechsteiner** [comment]
Yeah, that should be possible! You need to subclass `PagingView` and update the constraints as the user is scrolling in the table view. E.g.

```Swift
class CustomPagingView : PagingView {
  override func setupConstraints() {
     // Set up some constraints for the paging view that you can update on scroll
  }
}

class CustomPagingViewController: FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      options: options,
      collectionView: collectionView,
      pageView: pageViewController.view)
  }
}
```

Then you can update the `topAnchor` constraint of the `collectionView` when the table view content offset changes. Let me know if you need any more help implementing that 🙂

**Comment by rechsteiner** [comment]
Closing this for now, but feel free to re-open if you need any more help to get this working 🙂

**Comment by Smiller193** [comment]
this doesn't work

**Comment by Smiller193** [comment]
can you reopen it because this isn't working for me
