### ISSUE TITLE
It is possible to update the title, once loaded the controls?

### ISSUE THREAD

**Issue by BhaveshKumbhani** [rechsteiner/Parchment#207]
I want to update title, It will look something like Peoples(0), Where Peoples is title of the page.

**Comment by rechsteiner** [comment]
Hi! I'm not sure if I understand exactly what you are trying to achieve. Are you talking about reloading the titles when some of the data changes?

**Comment by BhaveshKumbhani** [comment]
Yes, titles need dynamic, It should allow to edit anytime and from anywhere.

**Comment by rechsteiner** [comment]
You can reload the menu items by calling `pagingViewController.reloadData()`. There was a bug with reloading items that was fixed recently, so try to target the `master` branch if you are having any issues. I will get a new version released this weekend.

**Comment by BhaveshKumbhani** [comment]
See I show your update and test it, it is reloading whole controller and creating new instance of pager view controller on reload, instead of just provide the method to reload only menu items.

**Comment by rechsteiner** [comment]
Yeah, it will reload both the menu items and the view controllers. If you do not want to create new instances of the view controllers, you can store them in a property like this:

```Swift
class ViewController: UIViewController {
    let viewControllers: [UIViewController]

   ...
}

extension ViewController: PagingViewControllerDataSource {

  ...

  func pagingViewController(_ pagingViewController: PagingViewController, viewControllerForIndex index: Int) -> UIViewController {
    return viewControllers[index]
  } 
} 

```

Does that work for you?

**Comment by rechsteiner** [comment]
@BhaveshKumbhani did you manage to get this working?

**Comment by BhaveshKumbhani** [comment]
Yes, works for me but it was reloading with animation.
