### ISSUE TITLE
Delegate methods does not called in 1.2.0/1.3.0 swift 3.2

### ISSUE THREAD

**Issue by bizibizi** [rechsteiner/Parchment#209]
This is the code from 1.2.0

        pagingViewController = PagingViewController(viewControllers: [downloadedUserInterface, downloadingUserInterface])
        pagingViewController.delegate = self

        extension DownloadsContainerPresenter: PagingViewControllerDelegate {
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController, willScrollToItem pagingItem: T, startingViewController: UIViewController, destinationViewController: UIViewController) {
        
    }
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController, didScrollToItem pagingItem: T, startingViewController: UIViewController?, destinationViewController: UIViewController, transitionSuccessful: Bool) {
        
    }
        }

I upadated to 1.3.0, updated methods, but it still does not called

**Comment by bizibizi** [comment]
@rechsteiner

**Comment by bizibizi** [comment]
also, in 3.2 swift need to make some updates https://imgur.com/a/l6FJgJB

**Comment by rechsteiner** [comment]
Sorry for the delayed response. Can you verify that this is not working with the latest version (`v1.4.1`)?
