### ISSUE TITLE
it is not friendly to "Large Title Navigation Bar"

### ISSUE THREAD

**Issue by gaojinhsu** [rechsteiner/Parchment#210]
if I set `navigationController?.navigationBar.prefersLargeTitles = true`,  the navigation bar won't shrink or expand automatically while UITableView is scrolling

**Comment by crabman448** [comment]
Actually it seems, that it is not possible to handle large titles when we have multiple scroll views in the controller. Because I didn't find a good way to reassign navigation bar to the new scroll view when switching between controllers. All ways that I found have bugs :( 
But if someone will be able to provide some solution it would be awesome 🙌

**Comment by crabman448** [comment]
@rechsteiner Do you have any plans to try to support large large titles and other stuff like refresh control and search bar?

**Comment by gaojinhsu** [comment]
@crabman448 @rechsteiner   At least, I've seen some apps make it. https://itunes.apple.com/cn/app/yuan-fu-dao-chu-gao-zhong/id974568444?mt=8

**Comment by crabman448** [comment]
Maybe they use their own implementation of navigation bar

**Comment by zzmasoud** [comment]
also if no large title , but prompt (subtitle) text in navigation set , it fails .

**Comment by rechsteiner** [comment]
Hi everyone 👋 Sorry for the delayed response – I finally had some time to look into this. As @crabman448 mentioned, it's not really supported to use large titles unless you're using a single UIScrollView as the root view.

But, I did manage to get it somewhat working. You can add a "hidden" scroll view behind the `PagingViewController` and then update the content offset of that scroll view based on the scroll view of the currently selected view controller. That will "trick" the navigation controller to update the navigation bar while you are scrolling. It's not a perfect solution though, as the navigation bar does not transition very smoothly to the small title state.

I've created a new example target called `LargeTitlesExample` that you can check out for implementation details: https://github.com/rechsteiner/Parchment/blob/master/LargeTitlesExample/ViewController.swift

Here's a video of how the implementation looks like: https://youtu.be/jWNYMmtgSpk

Let me know if any of you find a way to get around the jump from large to small titles. You can see the effect that I'm talking about in the last part of the video.

**Comment by crabman448** [comment]
I was also trying to accomplish such behaviour (without parchment. Just to check the idea). But in my situation I tried to add SearchBar also. And it caused the problems as it is possible to see in the attached gif.
https://stackoverflow.com/questions/50820140/ios-11-large-title-navigation-bar-switch-scroll-view
I will try to attach my project soon

**Comment by crabman448** [comment]
Inside workspace there are two attempts. One without any libraries. Another one is with XLPagerTabStrip(was the one, that we used before). Code is not very clean because the main point was to test the idea. Also I think there should exist some private methods or properties, that can help to achieve the ideal behaviour
[MyCountries 2.zip](https://github.com/rechsteiner/Parchment/files/2313460/MyCountries.2.zip)

**Comment by rechsteiner** [comment]
Closing this for now as it seems like this the only way to achieve this. I will update the `LargeTitlesExample` target if I find any improvements 🙂

**Comment by vanab** [comment]
Try it for more smooth animation

```
func scrollViewDidScroll(_ scrollView: UIScrollView) {
        // When the current table view is scrolling, we update the
        // content offset of the hidden scroll view to trigger the
        // large titles to update.
        hiddenScrollView.contentOffset = scrollView.contentOffset
        hiddenScrollView.panGestureRecognizer.state = scrollView.panGestureRecognizer.state 
}
```

**Comment by pkamb** [comment]
> I've created a new example target called LargeTitlesExample that you can check out for implementation details:  
 > https://github.com/rechsteiner/Parchment/blob/master/LargeTitlesExample/ViewController.swift

that seems to have been merged in the PR here if you are looking for it, as I was.

https://github.com/rechsteiner/Parchment/pull/237
