### ISSUE TITLE
Delegate method doesn't called

### ISSUE THREAD

**Issue by voytov1ch** [rechsteiner/Parchment#211]
Hello! Thank you so much for Parchment.

Have some problem:

func pagingViewController<T>(_ pagingViewController: PagingViewController<T>,
                               widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat?

Doesn't called for me.

**Comment by LinusGeffarth** [comment]
Hey, have you set these:

**Comment by voytov1ch** [comment]
@LinusGeffarth yes, sure

**Comment by rechsteiner** [comment]
Hi @voytov1ch! Which version of Parchment are you using? It seems to work just fine here.

**Comment by funlabuz** [comment]
Met the same problem @rechsteiner  version Using Parchment (1.3.0) 
`    let pagingViewController = PagingViewController<PagingIndexItem>()

  override func viewDidLoad() {
        super.viewDidLoad()
 addChildViewController(pagingViewController)
        pagingViewController.dataSource = self
        pagingViewController.delegate = self
        view.addSubview(pagingViewController.view)
        pagingViewController.didMove(toParentViewController: self)
        pagingViewController.textColor = .warmGrey
        pagingViewController.options.indicatorColor = .strawberry
        pagingViewController.options.selectedTextColor = .black51
        pagingViewController.options.selectedFont = UIFont.robotoRegular(fontSize: 14)
        pagingViewController.options.font = UIFont.robotoRegular(fontSize: 14)
        pagingViewController.options.menuItemSize = .sizeToFit(minWidth: 70, height: 38)
        pagingViewController.options.borderColor = .clear
        pagingViewController.indicatorOptions = .visible(height: 3, zIndex: 0, spacing: UIEdgeInsets.init(top: 0, left: 0, bottom: 0, right: 0), insets: UIEdgeInsets.init(top: 0, left: 5, bottom: 0, right: 5))
}

  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat? {
        guard let item = pagingItem as? PagingIndexItem else { return 0 }
        let insets = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
        let size = CGSize(width: CGFloat.greatestFiniteMagnitude, height: pagingViewController.menuItemSize.height)
        let attributes = [NSAttributedStringKey.font: pagingViewController.font]
        let rect = item.title.boundingRect(with: size,
                                           options: .usesLineFragmentOrigin,
                                           attributes: attributes,
                                           context: nil)
        let width = ceil(rect.width) + insets.left + insets.right
        if isSelected {
            return width * 1.5
        } else {
            return width
        }
    }
`

**Comment by rechsteiner** [comment]
@funlabuz thanks for the report! Managed to reproduce it now. Will get a fix out shortly 👍

**Comment by rechsteiner** [comment]
Pushed a fix for this now #244 ✌️

@voytov1ch @funlabuz could you target the `master` branch and verify that this actually fixes the issue for you as well?
