### ISSUE TITLE
Disable swipe on page

### ISSUE THREAD

**Issue by jaceklapinski** [rechsteiner/Parchment#212]
Is there any way to disable swipe gesture on page ? I don't want to use swipe because this is block swipe on my TableViewController :) i just want to change page swipe on clicking on menu header 

Best

**Comment by rechsteiner** [comment]
Yes! You can disable scrolling in the content area like this:

```Swift
pagingViewController.contentInteraction = .none
```

**Comment by beilusen** [comment]
> Yes! You can disable scrolling in the content area like this:
> 
> ```swift
> pagingViewController.contentInteraction = .none
> ```

nice!!!
