### ISSUE TITLE
Swipe to delete row in tableview

### ISSUE THREAD

**Issue by mrJ0hn** [rechsteiner/Parchment#215]
Hello! I used calendar pager and added tableview as child viewcontroller. I tried to enable deleting a row. But swipe to delete doesn't work. It works only once in a hundred. Instead of this view controller switch to the right. Could you help me?

**Comment by rechsteiner** [comment]
Hi! It sounds like it would be better to disable swiping between view controllers in that case. You can disable swiping by setting `pagingViewController.contentInteraction = .none`.

Does that work for you?

**Comment by rechsteiner** [comment]
Closing this now, but feel free to re-open if you still need any help 🙂
