### ISSUE TITLE
One view controller but more categories?

### ISSUE THREAD

**Issue by luongchautuan** [rechsteiner/Parchment#219]

**Comment by luongchautuan** [comment]
Can help me about this? @rechsteiner

**Comment by rechsteiner** [comment]
Hi @luongchautuan! This isn't really possible at the moment. I'm working adding support for using the menu items as a standalone component, but it will probably be a few weeks before that is ready.

**Comment by VishnuMU** [comment]
@luongchautuan Could you please describe what you are trying to achieve here?

**Comment by rechsteiner** [comment]
Closing this due it inactivity, but feel free to re-open if you any updates 🙂
