### ISSUE TITLE
viewWillAppear not getting called on child controllers when came back from other tabbar controller index

### ISSUE THREAD

**Issue by barkiiqbal** [rechsteiner/Parchment#220]
I am using TabbarViewController in my application. Now when I change controller from tabbar and came back to Parchment view controller then viewWillAppear does not call on child view controllers.

**Comment by rechsteiner** [comment]
Thanks for the report! I will take a look and try to get a fix out shortly 👍

**Comment by liorazi** [comment]
@barkiiqbal I don't think it's an issue specifically related to Parchment.
According to what I know it's related to how UITabBarController is working with child view controllers which are navigation view controllers.

**Comment by hiral128** [comment]
getting same issue

**Comment by rechsteiner** [comment]
Hi everyone! I finally managed to implement a fix for this. The page view controller we're using was not forwarding the appearance methods to the selected child view controller. This is fixed in #306 and will be included in the next release ✌️

**Comment by ikesyo** [comment]
Ref: https://github.com/emalyak/EMPageViewController/issues/19
