### ISSUE TITLE
Can't get parent view controller

### ISSUE THREAD

**Issue by garciaish** [rechsteiner/Parchment#221]
I was wondering why I can't get the parent view controller of the view controllers in the FixedPagingViewController, or the FixedPagingViewController itself.

My use case is that I've put the FixedPagingViewController on top of a ViewController that is a child of a TabbarViewController, and I want to get the reference to that tabbarviewcontroller. I was testing around, but even `let parentViewController = self.parent` is returning nil. 

For example, I added `firstVC` and `secondVC` to the FixedPagingViewController, and added it to the current view controller as a subview:
```
let firstVC = storyboard.instantiateViewController(withIdentifier: "firstView")
let secondVC = storyboard.instantiateViewController(withIdentifier: "secondView") 
let pagingViewController = FixedPagingViewController(viewControllers: [firstVC, secondVC])
        
addChildViewController(pagingViewController)
view.addSubview(pagingViewController.view)
view.constrainToEdges(pagingViewController.view)
pagingViewController.menuItemSize = .sizeToFit(minWidth: 30, height: 30)
pagingViewController.didMove(toParentViewController: self)
```

And then on the viewcontroller of the firstview, when I do `let parentVC = self.parent`, the returned value is nil.

**Comment by garciaish** [comment]
Nevermind, I was trying to get it from viewDidLoad. It works on viewDidAppear.

**Comment by rechsteiner** [comment]
Great! Closing this then 👍

**Comment by shinip2** [comment]
Thank you, you saved my day!
