### ISSUE TITLE
How to know when the view controller is really selected?

### ISSUE THREAD

**Issue by prsolucoes** [rechsteiner/Parchment#222]
Hi,

How to know when the view controller is really selected?

In my case i have 3, and when the app load, the first and second are loaded and the http request are called for the two tabs.

I want individual requests. When the user enter on each tab, the view controller will be showed and the request start individually.

On android view pager we can set an option to disable the create/remove option, so, if i created the first and the http request was done, if i go to latest tab and back, it is there.

Can you help me?

Thanks.

**Comment by kraisorns** [comment]
@prsolucoes  I think you can get that by using the delegate func

```
func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    didScrollToItem pagingItem: T,
    startingViewController: UIViewController?,
    destinationViewController: UIViewController,
    transitionSuccessful: Bool)
```

**Comment by rechsteiner** [comment]
Yeah, you should be able to do that using the delegate methods. Another option would be to perform the fetching in `viewDidAppear` instead. Does that work for you?

**Comment by rechsteiner** [comment]
Closing this issue, but feel free to re-open if you have any further questions 🙂
