### ISSUE TITLE
Get current controller with InfiniteDataSource

### ISSUE THREAD

**Issue by mimmo00** [rechsteiner/Parchment#224]
Hi, congratulations for the framework!
I'm using the InfiniteDataSource. I can set the variables of controller during the initial setting.

`extension ContainerViewController: PagingViewControllerInfiniteDataSource {
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {
        let calendarItem = pagingItem as! CalendarItem
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let currentController = storyboard.instantiateViewController(withIdentifier: "CollectionViewController") as! CollectionViewController
        currentController.currentDate = calendarItem.date
        currentController.delegate = self
        return currentController
    }
...`

How can I communicate with the current controller later?

Thanks

**Comment by rechsteiner** [comment]
Hi @mimmo00! You can get the currently selected view controller using the `delegate`:

```
func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    didScrollToItem pagingItem: T,
    startingViewController: UIViewController?,
    destinationViewController: UIViewController,
    transitionSuccessful: Bool)
```

Does that work for you?

**Comment by mimmo00** [comment]
Thanks for the answer. I use it to get the scroll of the pages. Two questions:
- do I need to cast the destionationViewController into CollectionViewController, right?
- I have to use this delegate even if I don’t scroll?

Thanks a lot!

**Comment by rechsteiner** [comment]
> do I need to cast the destionationViewController into CollectionViewController, right?

Yeah, that's correct 

> I have to use this delegate even if I don’t scroll?

Yes, this delegate should also be called if the user selects the items in the menu 🙂

**Comment by mimmo00** [comment]
Hi @rechsteiner , unfortunately the delegate is not called on startup. it is only called when you scroll or select a menu item. So I have not found a solution yet :(

**Comment by mimmo00** [comment]
Thanks, but in ViewDidAppear it is nil

`
...
pagingViewController.select(pagingItem: CalendarItem(date: Date()))            
            if (pagingViewController.pageViewController.selectedViewController == nil) {
                print("NIL")  
            }`

I need to replicate this on start:

`func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, didScrollToItem pagingItem: T, startingViewController: UIViewController?, destinationViewController: UIViewController, transitionSuccessful: Bool) where T : PagingItem, T : Comparable, T : Hashable {
        
        currentController = destinationViewController as! CollectionViewController
}
}`

Thanks a lot

**Comment by mimmo00** [comment]
@rechsteiner maybe the problem is that I'm using a subclass of PagingViewController?

`class ResizedPagingViewController : PagingViewController<CalendarItem> {
    override func loadView() {
        view = ResizedPagingView(
            options: options,
            collectionView: collectionView,
            pageView: pageViewController.view)
    }
}`

**Comment by rechsteiner** [comment]
Using a subclass shouldn't be a problem. The view controller is not added before `viewDidAppear`. Are you sure you are checking there and not in `viewDidLoad`? I just tried adding this to the `CalendarExample` and it logs the selected view controller just fine:

```Swift
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    print(pagingViewController.pageViewController.selectedViewController)
  }
```

```
Optional(<CalendarExample.CalendarViewController: 0x7fb74a42fc00>)
```

**Comment by mimmo00** [comment]
Yes, I tried everything inside `viewDidAppear ` 
For now I solved this dirty way (inside `viewDidAppear `):

```
DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {

                self.pagingViewController.select(pagingItem: CalendarItem(date: Date()))

            })

```
Thanks!

**Comment by rechsteiner** [comment]
Can you try calling `select(pagingItem:)` in `viewDidLoad` then printing `selectedViewController` in `viewDidAppear`?

**Comment by mimmo00** [comment]
Yes, I tried again now. If I'm logged in, it crash because it loads the listing from server. If I am not logged in, the empty status appears without problems. Probably it is some strange logic of the listing to cause the error, not the library :)
