### ISSUE TITLE
Programmatic Navigation Controller & Autolayout

### ISSUE THREAD

**Issue by rahilbhansali** [rechsteiner/Parchment#226]
Hi @rechsteiner,

Thanks for the awesome library. We've been using CapsPageMenu all this while but thought we'd switch to this. One issue I noticed - which I'd like your inputs on: 

If you add the navigation controller dynamically - instead of on storyboard - while loading the view, the paging menu controller doesn't adjust the internal view height. 

1. Paging Menu did not show up under the navigation bar - I've set the navigationController.navigationbar.istranslucent to false as per another issue I noticed (#193) - this helped me atleast with the positioning of the paging menu under the navigation bar 

2. However, the child controllers do not take into account this paging menu height & the navigation bar height while loading it's content. You can see my attached screenshots of what the controller should look like if there was no paging menu & what it looks like when there is. The inner view should have been smaller by navigationBarHeight + pagingMenuHeight. Have you come across this before or have any ideas on how to fix it?

![simulator screen shot - iphone 7 - 2018-08-09 at 08 29 36](https://user-images.githubusercontent.com/7209471/43875535-6531bf02-9bae-11e8-9623-4d4d9f9ab052.png)
![simulator screen shot - iphone 7 - 2018-08-09 at 08 23 28](https://user-images.githubusercontent.com/7209471/43875536-655cd5a2-9bae-11e8-9284-15e002ff1ea6.png)

Note: If it helps, I've created a sample example called WithoutStoryboardExample. You'll see that the label 0, 1, 2 shows a different spacing at the bottom in the event the navigation bar is translucent or not. Ideally, if constraints or layout was working correctly, the appearance in both cases should be the same with just the child view controller reducing in height to account for the navigation bar and the paging menu (i have a feeling it's not accounting for both the heights).

[Parchment-master-New.zip](https://github.com/rechsteiner/Parchment/files/2272691/Parchment-master-New.zip)
![simulator screen shot - iphone 7 - 2018-08-09 at 08 53 44](https://user-images.githubusercontent.com/7209471/43876325-2504a436-9bb2-11e8-9b32-53a175a39ee8.png)
![simulator screen shot - iphone 7 - 2018-08-09 at 08 53 29](https://user-images.githubusercontent.com/7209471/43876326-253270be-9bb2-11e8-9489-577c60b66b97.png)

**Comment by rechsteiner** [comment]
Hi @rahilbhansali!

It's true that it's not accounting for the height for the navigation bar. I'm not really sure how I would do that without taking too many assumptions about how it's being used. The default implementation constrains the page view controller to the bottom of the menu view. If you want to go underneath the menu view, you can subclass `PagingView` and setup your own constraints ([See here](https://github.com/rechsteiner/Parchment/blob/master/UnplashExample/ViewController.swift#L36) for an example). Does that work for you?

**Comment by rahilbhansali** [comment]
@rechsteiner this approach works for now. Thanks!! Fixes the issue at the bottom. Having some scroll view issues at the top now - though i'll figure it out. Appreciate the help. 

I'll delve deeper when I get a chance and see if i can help with a more generic solution to account for non-storyboard created navigation controllers
