### ISSUE TITLE
I selected first pageItem the collectionview was changed,but the pagingview's content didn't change

### ISSUE THREAD

**Issue by RickwangF** [rechsteiner/Parchment#231]
![image](https://user-images.githubusercontent.com/14838520/44070676-c46fb782-9fb7-11e8-9582-574bec7750ac.png)

**Comment by RickwangF** [comment]
the pagingview was still showing third pageitem's viewcontroller

**Comment by lovealbert** [comment]
me too. ㅠㅠ

**Comment by RickwangF** [comment]
I guess why cause this problem is I did override subviewcontroller’s viewdidlayoutsubviews function and call super’s founction

发自我的 iPhone

**Comment by lovealbert** [comment]
I solved it by changing the calling function. Thanks
viewWillAppear --> viewDidAppear

**Comment by rechsteiner** [comment]
@RickwangF Hi! Did you figure this out or is this an issue with Parchment?

**Comment by rechsteiner** [comment]
Ah okay. Could you provide some more details on how to reproduce this?

**Comment by rechsteiner** [comment]
@RickwangF  any updated on this?
