### ISSUE TITLE
Corner Radius Indicator

### ISSUE THREAD

**Issue by anthony1810** [rechsteiner/Parchment#232]
I simply want to add corner radius to the indicator using indicatorClass might be a little too much? Please provide the fourth customise option for indicator.

`pagingViewController.indicatorConerRadius = 2`

**Comment by rechsteiner** [comment]
I've been thinking a bit more about this and I don't think I will add this as an option. One of the goals of Parchment is to be a generic and easily customizable framework. I think adding built-in support for these things will only make it bloated in the end.

You can achieve rounded corners by just adding a few lines of code:

```Swift
class RoundedIndicatorView: PagingIndicatorView {
  override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
    super.apply(layoutAttributes)
    layer.cornerRadius = layoutAttributes.frame.height / 2
  }
}
```

Thanks for the suggestion though 🙂

**Comment by ruofeilyu** [comment]
This is not about the simplicity, it's actually a necessary attribute when designing any UI related repo, corner radius improve the beauty of user interface.
