### ISSUE TITLE
Landscape scrolling constraint and layout only setup correctly after viewDidAppear

### ISSUE THREAD

**Issue by eyzuky** [rechsteiner/Parchment#236]
Hi, I am attaching a video showing the problem. 
My design is like your calendar example. Please help! why does this happen?
[ScreenRecording_08-22-2018 17-34-53.MP4.zip](https://github.com/rechsteiner/Parchment/files/2310778/ScreenRecording_08-22-2018.17-34-53.MP4.zip)

The file is attached in a zip since I couldn't publish an mp4 here.

Thanks!!

**Comment by rechsteiner** [comment]
Hi @eyzuky! It's a bit hard to tell without some more details on your implementation. How are you adding that "Aug" view in the menu? Is that part of the collection view?

**Comment by eyzuky** [comment]
hey @rechsteiner, thanks for your response!
Well, it is mostly just views and collectionViews, specifically the "Aug" is a little view with a label.
What seems to be the problem (which I cannot solve), is occurring only on iPhone X, where there is a Safe area thing. I am not sure 100%, but this seems to be happening with collection views more than anything else. From our research, it looks like the VC only understand its margins after it fully appears. Meaning that the VC's that were loaded out of the bounds of the screen, do not know about the Safe area, and only when it fully appears (viewDidAppear is called), it then applies the constraints like they were defined...

Thanks, I hope we solve this!

**Comment by rechsteiner** [comment]
@eyzuky did you manage to figure this out? If not, are you able to reproduce this in an example project or implementation that you can send? 🙂

**Comment by eyzuky** [comment]
@rechsteiner Hey! thanks for your interest. Actually, I haven't.. this is really frustrating as it is the only thing that is holding us back from releasing our feature. I will try to make the example project, I need to have few hours of capacity for that, will work on my boss :)

**Comment by rechsteiner** [comment]
I can't really find a way of reproducing this. Are you sure this is an issue with Parchment and not just something released to your implementation? If not, it would be nice if you could provide a minimal example that reproduces this issue.

**Comment by rechsteiner** [comment]
Closing this for now. Feel free to re-open if you have any ways of reproducing this 🙂
