### ISSUE TITLE
Not possible to have transparent/ translucent nav. bar

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#24]
Hello!

We tried but didn't succeed in making the effect when what is vertically scrolled in the view appears underneath the nav. bar in order to have transparency/translucency effect.

Our idea was to make

1. Fully transparent nav. bar
2. Make fully transparent menu (horizontal collection view with icons).
3. Than add custom view (nav. bar view) of a certain height and level of translucency.
We, actually, succeeded in all of that. The bottleneck appeared to be that we couldn't move the view underneath the nav. bar and the menu itself. We also don't really understand how to change y position of the menu (horizontal collection view with icons), neither of the view, independently of each other.

By view here I mean the any view (tableview, collectionView, ...) that is inserter into the contentView together with the menu (horizontal collection view with icons).

I tried to explain on this picture.
So we need to put the view underneath the nav. bar and the menu. And move it up to the contentView's top margin.

<img width="654" alt="screen shot 2017-02-02 at 19 59 36" src="https://cloud.githubusercontent.com/assets/16180201/22565531/c4ece0a4-e988-11e6-9b84-7766fadf5b75.png">

**Comment by rechsteiner** [comment]
Yeah, this should definitely be possible. You would have to subclass `PagingView` and setup your custom constraints something like this:

```Swift
class CustomPagingView : PagingView {
  
  override func setupConstraints() {
    collectionView.translatesAutoresizingMaskIntoConstraints = false
    collectionView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
    collectionView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
    collectionView.topAnchor.constraint(equalTo: topAnchor).isActive = true
    collectionView.heightAnchor.constraint(equalToConstant: options.menuItemSize.height).isActive = true
   
    pageView.translatesAutoresizingMaskIntoConstraints = false
    pageView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
    pageView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
    pageView.topAnchor.constraint(equalTo: topAnchor).isActive = true
    pageView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
  }

  // You need to override this as well to change the order of the
  // views so that the collection view is at the top. I will update
  // this later to make sure this is the default.
  override func configure() {
    addSubview(pageView)
    addSubview(collectionView)
    setupConstraints()

    // Also, turns out the headerBackgroundColor option on the
    // PagingTheme is not actually hooked up, so for now you
    // can just make the menu view transparent like this:
    collectionView.backgroundColor = .clear
  }
}
```

Then you need to subclass `PagingViewController` and set your custom view:

```Swift
class CustomPagingViewController : FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      pageView: pageViewController.view,
      collectionView: collectionView,
      options: options)
  }
}
```

This should make the menu items appear above the paging views. Let me know if this is working for you!

**Comment by IVANKRUPSKI** [comment]
Worked well. Thank you!
