### ISSUE TITLE
Add Buttons

### ISSUE THREAD

**Issue by Urkman** [rechsteiner/Parchment#242]
Any chance to add a button to the left and right side of the paging control?

**Comment by rechsteiner** [comment]
Hi! It depends a bit on what you are trying to achieve. If you need the buttons to be scrolling alongside the menu items, you would need to create your own `PagingCell` where you can show a button depending the some data that you set in your `PagingItem`.

Here's the general approach you can use:

First, create your own `PagingItem` type that contains something to determine whether or not you should show a button.

```Swift
struct Item: PagingTitleItem, Hashable, Comparable {
    let showButton: Bool
    ...
}
```

Then create an array of `Item`'s that you can return in your `PagingViewControllerDataSource` implementation. See [this guide](https://github.com/rechsteiner/Parchment/blob/master/Documentation/data-source.md) on how to use the custom data source.

```Swift
let items: [Item] = [
      Item(showButton: true, title: "Button 1", index: 0),
      Item(title: "View 0", index: 1),
      Item(title: "View 1", index: 2),
      Item(showButton: true, title: "Button 2", index: 3)
]
```

Then create your own `PagingCell` where you override the `setPagingItem` and use that to determine whether to show your button or not:

```Swift
class CustomPagingCell: PagingCell {
    override func setPagingItem(_ pagingItem: PagingItem, selected: Bool, options: PagingOptions) {
          guard let item = pagingItem as? Item else { return }
          if item.showButton {
               // Show the button
          } else {
               // Show a title or some other cell content
          }
     }
  }

}
```

Does that work for you?

**Comment by Urkman** [comment]
Thanks for your answer :)

But I don't want the Button to scroll with the items.
It should be fixed on the right or left side.

In my case I want to have an "Add Button" on the side of the list...

**Comment by rechsteiner** [comment]
Ah okay. Then you can just add your buttons directly to `pagingViewController.view`
