### ISSUE TITLE
Header Above MenuItem

### ISSUE THREAD

**Issue by gordoneliel** [rechsteiner/Parchment#246]
Is there an easy way to add a header above the MenuItemsw without writing a whole collection view layout. The idea here is for the header to scroll with the menu items and possibly the menu items stick to the top while scrolling

Example:

![examplewithheader](https://user-images.githubusercontent.com/5516761/44686118-11cb6900-aa02-11e8-9f8d-4a6e05acbc65.jpg)

**Comment by rechsteiner** [comment]
Hi @gordoneliel! Sorry for the delayed response. I don't have any examples of how to achieve exactly this, but I'm pretty sure it should be possible to do this. You basically need to create your own `PagingView` subclass where you add your image view above the menu view. Then you need to listen to scroll changes by setting the scroll view delegate and updating the constraints in your custom view.

You can check out the `ScrollExample` for details on how to do that. Let me know if you are able to get this working 🙂

**Comment by rechsteiner** [comment]
Did you manage to get this working?

**Comment by yungdbo** [comment]
I am having this same issue. I tried using the scrolling example, but with my situation, I need to able to scroll in the Parchment paging view and the header. I keep running into constraint issues where my paging view doesn't scroll past a certain point. No matter how tall I make the View in the view controller (that I added the paging view and header which is a picture that is about 150 pts big), I don't get a continuous scroll for it all. Can you help me? @rechsteiner

**Comment by pushchris** [comment]
Likewise having similar issues with getting that area to be vertically scrollable. An example would be much appreciated

**Comment by rechsteiner** [comment]
I've added another example, showing how you can add a header above the menu: https://github.com/rechsteiner/Parchment/blob/master/HeaderExample/ViewController.swift. Here's a video of how it works: https://www.youtube.com/watch?v=mPwk_ky7q-Q

**Comment by yungdbo** [comment]
I will give it a shot and let you know how it goes! Thanks @rechsteiner I appreciate the video and example

**Comment by yungdbo** [comment]
Works like a charm! Thanks again @rechsteiner

**Comment by gordoneliel** [comment]
Works!
