### ISSUE TITLE
Working in a Tabbed App

### ISSUE THREAD

**Issue by dadidu67** [rechsteiner/Parchment#249]
![simulator screen shot - iphone 8 - 2018-09-05 at 10 29 24](https://user-images.githubusercontent.com/35390510/45081284-29d47400-b0f7-11e8-9377-4cd563189c9b.png)
Is it possible to use Parchment in an Tabbed App? I did try to add the lib to my projekt, but if do the same like in the sample code (which is not difficult) i don't see the whole menu only the indicator.

**Comment by Michele404** [comment]
Hey.
Did you solve the problem?
I can't see the TabBarController on Parchment View

**Comment by dadidu67** [comment]
Yes in 'extension UIView'(UIView+constraints.swift) I had to change the let topContraint = NSLayoutConstraint( ... constant = ANOTHER VALUE).
But this is not related to the problem that you not see the 'TabBarController'. Try maybe to play around with the 'bottomConstraint'.
