### ISSUE TITLE
Want to remove UISwipeGestureRecognizer 

### ISSUE THREAD

**Issue by Singh09Meenu** [rechsteiner/Parchment#252]
I am using this pod file and want to remove the UISwipeGestureRecognizer feature. I tried everything but unable to do that ,can any one help me out for that.
Thanks in advance

**Comment by vijay1864** [comment]
I also Have the Same issue too
Can anyone help me out
Thanks in advance

**Comment by vijay1864** [comment]
@Singh09Meenu Did you solve your issue
If yes, please tell me how to do that..?
