### ISSUE TITLE
Want to pass data from MainViewController to FirstViewController on selecting the data in MainViewController

### ISSUE THREAD

**Issue by Singh09Meenu** [rechsteiner/Parchment#253]
Hi,
I am making a dropdown in mainViewController and after getting the value in MainViewcontroller ,I need it to be passed in FirstViewcontroller at same time .I had already tried delegates but it is not working .Can any1 help me in this please.
Thanks in advance.

**Comment by rechsteiner** [comment]
Hi @Singh09Meenu! I don't think I understand exactly what the problem is. Can you provide some more details on your implementation and what you are trying to achieve?

**Comment by Singh09Meenu** [comment]
Thanks for the approach ,I had resolved the problem thanks for replying.

**Comment by isaacraja15** [comment]
hi singh ,

how you solve kindly give that details .. i need pass data from first tab to second tab

**Comment by Singh09Meenu** [comment]
In MainViewController were I am getting the value which I have to pass there in my recalling the viewdidload  by this line 
 self?.viewDidLoad().
After that , simply make a var object in my FirstViewController 
       e.g.  var weekValue = ""
       and passed the data Of Mainviewcontroller to firstViewcontroller

        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc1 = storyboard.instantiateViewController(withIdentifier: "first") as! FirstViewContoller
        vc1.weekValue = gettingWeekValue.

**Comment by Singh09Meenu** [comment]
Hi,

I haven't tried that and don't have the idea too.

Thanks and regards,
Meenu singh
