### ISSUE TITLE
Occasionally doesn't recognise swipe when swiping rapidly many controllers from one to another, one direction.

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#26]
Occasionally doesn't recognise swipe when swiping rapidly many controllers from one to another, one direction.

It's just for some parts of a second.

But when you want to swipe rapidly many screens that might be annoying.

**Comment by rechsteiner** [comment]
Looks like there is an issue with the `EMPageViewController` library I'm using. If you swipe very fast it doesn't seem to recognize some of the swipes. I'm planning to place that library with a custom implementation, but it might take a while before that's ready.

**Comment by IVANKRUPSKI** [comment]
Got it. Thanks for the answer!

Looking forward for the update.

2017-02-09 17:36 GMT+01:00 Martin Rechsteiner <notifications@github.com>:

**Comment by rechsteiner** [comment]
Closing in favour of this #80. It's quite hard to create a page view controller that works really well, so it might take while before this is ready.
