### ISSUE TITLE
Two pages - one ViewController

### ISSUE THREAD

**Issue by jaceklapinski** [rechsteiner/Parchment#260]
Hello, 

Is there any way to have only 1 ViewController and change his state base on selected page ( tab ) ??

Best

**Comment by rechsteiner** [comment]
Hi @jaceklapinski! Sorry for the late reply. This isn't really supported at the moment, but it will be possible once I've separated the menu into a standalone component: #243.

That said, you might be able to get it working by creating a `PagingViewControllerDataSource` that always returns the same view controller and set `pagingViewController.contentInteraction = .none`

**Comment by kaleemozitech** [comment]
@jaceklapinski  how did you over come this problem.
i just want to change state of one  viewController on tab to different pager items

**Comment by ansonngch** [comment]
I'm curious about it too @jaceklapinski
