### ISSUE TITLE
Update a PagingCell / remove current page

### ISSUE THREAD

**Issue by AntoGeekz** [rechsteiner/Parchment#262]
hello,

It's not really a issue, but I need your help because I don't found how to achieve what I want to do with Parchment :(

How is it possible to update just one PagingCell? And how can I delete the current page (or another) displayed? I don't understand/find how is it possible...

thx for your help and nice job for the lib :)

**Comment by rechsteiner** [comment]
Hi! It's not really possible to update just a single cell. If you need to update the menu items or remove current pages you need to update your data source and call `reloadData`. Here's an introduction to using [custom data sources](https://github.com/rechsteiner/Parchment/blob/master/Documentation/data-source.md). Does that work for you?

**Comment by AntoGeekz** [comment]
Hi, oh ok, too bad :'( I wanted to avoid to reload all just to update one cell. 

Thx for you answer.
