### ISSUE TITLE
Caching more than 3 VC's in infinite page view controller

### ISSUE THREAD

**Issue by eyzuky** [rechsteiner/Parchment#264]
Hi! Is there a possibility to cache more VC's, maybe more towards the 10-20 VCs?

**Comment by rechsteiner** [comment]
Yeah, if you're using `FixedPagingController` it will keep all the view controllers in memory. If you want to do it using `PagingViewController` you need to allocate and store a reference to you view controllers and return them in the data source.

**Comment by eyzuky** [comment]
@rechsteiner Thanks. Though it is not clear to me on where/when I should reload the cache in a proper efficient manner.. any insights?

**Comment by rechsteiner** [comment]
Do you have a fixed amount of view controllers or are you using PagingInfiniteDataSource?

**Comment by eyzuky** [comment]
Unfortunately, no, I am implementing a calendar so every day has a different VC.. i want to load a week forward and backwards, and as I see the difference in speed between adjacent VC's, but sometimes the user presses on a day that is not cached and it is much slower.. I want to at least cache around the selected day. Maybe I will do some LRU cache, so the last used is removed everytime a new one is loaded.. but then I still need to know where to update them :)

**Comment by rechsteiner** [comment]
Sounds like you are doing something quite heavy in the initialiser of that view controllers then. It shouldn't be a very noticeable delay for just allocating a view controller when clicking it.

It would require quite a lot of on your end to "prefetch" view controllers like that, so I would recommend looking into why it's taking so long to initialise it in the first place. Maybe you can move something into `viewDidAppear` etc?

**Comment by eyzuky** [comment]
@rechsteiner Thank you, I will investigate this direction.

**Comment by eyzuky** [comment]
Hey @rechsteiner , just to update - eventually we found the issue was loading some nibs was too pricey, since the inner collectionView loaded them in every VC. Solved it by replacing nibs with programatic cells :) happy coding
