### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by Smiller193** [rechsteiner/Parchment#267]
Sorry to burden you again with my problems but this is most likely the last one :). I want to implement pull to refresh inside the collectionViews that are contained inside the pagingViewController. I am using this library  https://github.com/CRAnimation/CRRefresh  which makes implementing a pull to refresh fairly easy.

Only thing that is seemingly weird and I may be wrong is the nature of how the pull to refresh occurs.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16108750/47389568-1ac77680-d6e3-11e8-837a-c462028229a8.gif)

Is there anyway to make it so the cells/menu items don't drag down like that on the pull to refresh

**Comment by akun1** [comment]
Hi, did you ever find a solution to this?

**Comment by rechsteiner** [comment]
Hi! The default behaviour is that the menu don't drag down like tat. It looks like you've based your implementation on the `UnsplashExample`? In that case, you can update the `calculateMenuHeight` to cap the menu height at a certain point. Does that work for you?

**Comment by Smiller193** [comment]
@rechsteiner how would I do that. I tried to update that and it didn't work too well
