### ISSUE TITLE
Can the menu be put at bottom instead of top

### ISSUE THREAD

**Issue by bitflying** [rechsteiner/Parchment#268]
Hi, friends,

For all examples of Parchment, menu always is put at top under NavigationBar. So, Is there any way to put menu at bottom?

Thanks in advance!

**Comment by rechsteiner** [comment]
Hi @bitflying! You can customize the position of the menu by subclassing `PagingView` and override `setupConstraints` like this::

```Swift
class CustomPagingView : PagingView {
  override func setupConstraints() {
    pageView.translatesAutoresizingMaskIntoConstraints = false
    collectionView.translatesAutoresizingMaskIntoConstraints = false
    
    NSLayoutConstraint.activate([
      pageView.leadingAnchor.constraint(equalTo: leadingAnchor),
      pageView.trailingAnchor.constraint(equalTo: trailingAnchor),
      pageView.topAnchor.constraint(equalTo: collectionView.topAnchor),
      pageView.bottomAnchor.constraint(equalTo: bottomAnchor),
      
      collectionView.leadingAnchor.constraint(equalTo: leadingAnchor),
      collectionView.trailingAnchor.constraint(equalTo: trailingAnchor),
      collectionView.bottomAnchor.constraint(equalTo: bottomAnchor),
      collectionView.heightAnchor.constraint(equalToConstant: options.menuItemSize.height),
    ])
  }
}

class CustomPagingViewController : FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      options: options,
      collectionView: collectionView,
      pageView: pageViewController.view)
  }
}
```

**Comment by bitflying** [comment]
Thanks @rechsteiner , I will try it!

**Comment by davidrivasro07** [comment]
this " pageView.topAnchor.constraint(equalTo: topAnchor)" worked for me instead of "pageView.topAnchor.constraint(equalTo: collectionView.topAnchor),"

**Comment by Istroot** [comment]
snapkit worked fo me:

`   
 private(set) lazy var pagingViewController: FixedPagingViewController = {
        let viewController = FixedPagingViewController(viewControllers: [ReleaseAlbumViewController(),
                                                                         ReleaseCameraViewController(),
                                                                         ReleaseVideoViewController()])
        return viewController
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        pagingViewController.didMove(toParent: self)
        pagingViewController.view.snp.makeConstraints { (make) in
            make.edges.equalToSuperview()
        }
        pagingViewController.collectionView.snp.makeConstraints { (make) in
            make.left.right.bottom.equalTo(view)
            make.height.equalTo(CGFloat.zhTabBarHeight)
        }
        pagingViewController.pageViewController.view.snp.makeConstraints { (make) in
            make.left.right.top.equalTo(view)
            make.bottom.equalTo(pagingViewController.collectionView.snp.top)
        }
    }
`

**Comment by Istroot** [comment]
snapkit worked fo me:

```
private(set) lazy var pagingViewController: FixedPagingViewController = {
    let viewController = FixedPagingViewController(viewControllers: [FirstViewController(), SecondViewController()])
    return viewController
}()

override func viewDidLoad() {
    super.viewDidLoad()
    pagingViewController.didMove(toParent: self)
    pagingViewController.view.snp.makeConstraints { (make) in
        make.edges.equalToSuperview()
    }
    pagingViewController.collectionView.snp.makeConstraints { (make) in
        make.left.right.bottom.equalTo(view)
        make.height.equalTo(CGFloat.zhTabBarHeight)
    }
    pagingViewController.pageViewController.view.snp.makeConstraints { (make) in
        make.left.right.top.equalTo(view)
        make.bottom.equalTo(pagingViewController.collectionView.snp.top)
    }
}
```
