### ISSUE TITLE
cannot compile project after fresh install

### ISSUE THREAD

**Issue by duczki4** [rechsteiner/Parchment#273]
I created new project. Installed newest cocoapods and installed parchment (0.9.0).
I made 'repo update'. Even though I cannot build empty project with installed parchment library.
![zrzut ekranu 2018-11-06 o 21 19 26](https://user-images.githubusercontent.com/35579002/48091512-34e87500-e20a-11e8-99c8-bf3ceeb57085.png)

**Comment by rechsteiner** [comment]
Hi! Looks like your’re trying to install an old version. Can you update to the latest version (`1.4.1`)?
