### ISSUE TITLE
remove DEVELOPMENT_TEAM from Parchement framework

### ISSUE THREAD

**Issue by ofirreuv72** [rechsteiner/Parchment#274]
Hi, 

Is it possible to remove the DEVELOPMENT_TEAM entry on the Parchement framework. 

fastlane is having issuses signing from the command line 

--- a/Parchment.xcodeproj/project.pbxproj
+++ b/Parchment.xcodeproj/project.pbxproj
@@ -1685,7 +1685,6 @@
                                CODE_SIGN_IDENTITY = "iPhone Developer";
                                "CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "";
                                DEFINES_MODULE = YES;
-                               DEVELOPMENT_TEAM = G4TGN24VA2;
                                DYLIB_COMPATIBILITY_VERSION = 1;
                                DYLIB_CURRENT_VERSION = 1;
                                DYLIB_INSTALL_NAME_BASE = "@rpath";
@@ -1712,7 +1711,6 @@
                                CODE_SIGN_IDENTITY = "iPhone Developer";
                                "CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "";
                                DEFINES_MODULE = YES;
-                               DEVELOPMENT_TEAM = G4TGN24VA2;
                                DYLIB_COMPATIBILITY_VERSION = 1;
                                DYLIB_CURRENT_VERSION = 1;
                                DYLIB_INSTALL_NAME_BASE = "@rpath";

and this fixed my issue, i am happy to submit a PR but i haven't done one yet. 

Thank you.

**Comment by rechsteiner** [comment]
Yeah, we can definitely remove that. If you can open a PR that would be awesome 🙂

**Comment by ofirreuv72** [comment]
Hi, 

I tried to create a branch via the web GUI, I don't think i have permissions. 

When i try to push a new branch i am getting the below error. 

ERROR: Permission to rechsteiner/Parchment.git denied to ofirreuv72.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

**Comment by rechsteiner** [comment]
You need to fork the project, then create a pull-request from your fork 🙂 But I've updated the project to remove the development team now #280
