### ISSUE TITLE
How to get seleted index in PagingViewController (infinite scroll)

### ISSUE THREAD

**Issue by Sopheak0** [rechsteiner/Parchment#276]
as [https://github.com/rechsteiner/Parchment/issues/199] problem, he has been solved this problem for FixPaging Viewcontroller. but i want to get the selected index for Infinite scrollview also (using in calendar)

**Comment by rechsteiner** [comment]
Hi @Sopheak0! When using the infinite data source the items doesn't really have any indexes. What do you need to index for? Maybe you can to use the currently selected date instead?

You can get the selected index based on the currently visible items like this:

```Swift
extension ViewController: PagingViewControllerDelegate {
  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, didScrollToItem pagingItem: T, startingViewController: UIViewController?, destinationViewController: UIViewController, transitionSuccessful: Bool) {
    print(pagingViewController.visibleItems.indexPath(for: pagingItem))
  } 
}
```

But keep in mind that these indexes will change when scrolling in the menu.

**Comment by Sopheak0** [comment]
sorry that I said the wrong word. I mean the selected date that the user was in. and I did try your code but the result when we scrolling is just an optional (Optional([0, 9])). also, didScrollToItem is called only when user scrolling the item but what the function should do is when the page visible to each date, they have to print to that selected that. if you're not sure what I'm talking about, I'll try to explain with the image. thank you for the library though, it's' awesome

**Comment by rechsteiner** [comment]
Great! You need to select the initial item, so you should already have access to the initial date. E.g: https://github.com/rechsteiner/Parchment/blob/master/CalendarExample/ViewController.swift#L58

**Comment by Sopheak0** [comment]
Ahhh! I see, great! thanks you so much
