### ISSUE TITLE
How to select item programmatically after first time loading is over

### ISSUE THREAD

**Issue by dhaval4gvm** [rechsteiner/Parchment#277]
I have tried several solutions like

```
pagingViewController.select(index: 0)
pagingViewController.select(pagingItem: PagingIndexItem(index: 0, title: "First Page"), animated: false)
```

I have tried writing above code in button click event, it works,, but if try same inside delegate method, then it won't work. If I write it while initialising `pagingViewController` then it works fine. 

Please help me out in this situation.

**Comment by dhaval4gvm** [comment]
I have tried to place item selection code inside `viewWillAppear` method, which will be called once user navigate to other screen and come back to same screen when this code is implemented.

**Comment by rechsteiner** [comment]
Hi @dhaval4gvm! I'm not sure I understand exactly what you mean. Which delegate method are you trying to select it from?

**Comment by dhaval4gvm** [comment]
I mean my custom protocol delegate method, but the select is also not work if I try in `viewWillAppear`, I have a requirement like when I came back to `UIViewController` where I have `pagingViewController` implemented, I have to change the selected item to another one, so I have tried in custom protocol also and also tried placing selection statement in `viewWillAppear`, but it won't work for me.

But if I write same selection statement while configuring `pageViewController` then it works.

**Comment by rechsteiner** [comment]
I'm having some troubles reproducing this. Could you provide some minimal example implementation where this is an issue?

**Comment by rechsteiner** [comment]
@dhaval4gvm any updates on this?
