### ISSUE TITLE
how to navigate second tab from side menu navigation 

### ISSUE THREAD

**Issue by isaacraja15** [rechsteiner/Parchment#278]

**Comment by isaacraja15** [comment]
![screen shot 2018-11-17 at 3 46 34 pm](https://user-images.githubusercontent.com/44321070/48659973-fd868d80-ea7f-11e8-90ed-eb7e775ee101.png)
![screen shot 2018-11-17 at 3 46 29 pm](https://user-images.githubusercontent.com/44321070/48659974-fd868d80-ea7f-11e8-857e-5317724bf206.png)
if i click ticket list  its need to go active tab .
how can i write code ?

**Comment by rechsteiner** [comment]
Hi @isaacraja15! You can programatically change tabs by calling:

```Swift
pagingViewController.select(index: 1)
```

https://github.com/rechsteiner/Parchment#selecting-items

**Comment by isaacraja15** [comment]
Thank you for reply...  OK so what can I decular pagingViewController ?

Need to decular again?


Let pagingViewController = [] ?

Could you explain me please?

**Comment by isaacraja15** [comment]
Great!
Thank you so much for your help.

**Comment by isaacraja15** [comment]
![screenshot 2018-11-19 at 12 31 00 pm](https://user-images.githubusercontent.com/44321070/48691155-7a884300-ebf7-11e8-9b0d-c1469b97c75a.png)
![screenshot 2018-11-19 at 12 31 30 pm](https://user-images.githubusercontent.com/44321070/48691156-7a884300-ebf7-11e8-80ac-146105985c3c.png)
No sir its not working , Cannot invoke initializer for type 'FixedPagingViewController' with no arguments
error what is the arguments
