### ISSUE TITLE
Load controllers from storyboard

### ISSUE THREAD

**Issue by kmyn** [rechsteiner/Parchment#28]
Hi,

Is it possible for loading view controllers from the storyboard rather? i.e., each tab would be a viewcontroller from the storyboard. If so, can you provide an example?

Thanks,
Karthik

**Comment by rechsteiner** [comment]
Yes, you need to load each view controller using `instantiateViewController:` on the storyboard and then manually setup a `PagingViewController`. Here's an example:

```Swift
override func viewDidLoad() {
    super.viewDidLoad()
    
    // Load each of the view controllers you want to embed
    // from the storyboard.
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let firstViewController = storyboard.instantiateViewController(withIdentifier: "FirstViewController")
    let secondViewController = storyboard.instantiateViewController(withIdentifier: "SecondViewController")
    
    // Initialize a FixedPagingViewController and pass
    // in the view controllers.
    let pagingViewController = FixedPagingViewController(viewControllers: [
      firstViewController,
      secondViewController
    ])
    
    // Make sure you add the PagingViewController as a child view
    // controller and contrain it to the edges of the view.
    addChildViewController(pagingViewController)
    view.addSubview(pagingViewController.view)
    view.constrainToEdges(pagingViewController.view)
    pagingViewController.didMove(toParentViewController: self)

  }
```

I will look into other ways of setting up a PagingViewController directly in the storyboard in the future. I've added a `StoryboardExample` to the project that you can check out if you want to see how the setup looks like in the storyboard.

**Comment by kmyn** [comment]
@rechsteiner thanks for the quick response and the example.

I tried the above code (StoryboardExample) it works fine as is. So, I tried extending it a bit by adding a class (swift file) to one of the controllers (FirstViewController) as below:

`
import UIKit

class FirstViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        print("In first VC")
        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}`

I expected the message "In first VC" (from viewDidLoad()) to get printed to the console when the app is fired but, that does not seem to happen. Am I doing something wrong? or is this what you were referring to as future work?

**Comment by rechsteiner** [comment]
Yeah, you need to set class type for that view controller. You can just select the view controller in the storyboard and then set the `Custom Class` property to be `FirstViewController` like this:

<img width="280" alt="screen shot 2017-02-19 at 21 14 53" src="https://cloud.githubusercontent.com/assets/1238984/23106128/f905d158-f6e8-11e6-8ce0-0d1e381ba7a3.png">

**Comment by kmyn** [comment]
I did set the class. The issue seems to be with the compiler. It worked perfectly after I ran it after a clean build.  Thanks again for the quick response and the example.
