### ISSUE TITLE
Different background color on different pages

### ISSUE THREAD

**Issue by PrashantKT** [rechsteiner/Parchment#283]
I have to change different color for different page for that I have used code in `pagingViewController<T>(_ pagingViewController: PagingViewController<T>, didScrollToItem
`

```
  self.navigationController?.navigationBar.barTintColor = self.menuItems[item.index].navigationColor
        self.pagingViewController.backgroundColor =  self.menuItems[item.index].navigationColor
        self.pagingViewController.selectedBackgroundColor =  self.menuItems[item.index].navigationColor
```
But issue is color is applied one index before for example color of index 0 is red , index1 is blue and index 2 is green .

Now initially I applied a red color. Now when I move to page 1 color is still red. Move to page2 color is now blue.

Please help

**Comment by PrashantKT** [comment]
after this self.pagingViewController.collectionView.reloadData() Fixes the issue. But is it right way to do this please suggest

**Comment by rechsteiner** [comment]
Hi @PrashantKT! For now, calling `pagingViewController.collectionView.reloadData` is the best way to get this working. I will look into getting this fixed 🙂

**Comment by mrcwbr** [comment]
For me did this work.

in the viewDidLoad:
`self.pagingVC = PagingViewController<PagingIndexItem>()`

later in the code (e. g. in the didScrollToItem delegate function):
`self.pagingVC.collectionView.backgroundColor = UIColor.red`

**Comment by rechsteiner** [comment]
Looked a bit more into this and it seems like `reloadData` is the way to go. You can also use `pagingViewController.reloadMenu()` to trigger and update to just the menu items.
