### ISSUE TITLE
how to navigate second tab from side menu navigation

### ISSUE THREAD

**Issue by isaacraja15** [rechsteiner/Parchment#286]
Please Help this there is issue 

Cannot invoke initializer for type 'FixedPagingViewController' with no arguments
error 

_Originally posted by @isaacraja15 in https://github.com/rechsteiner/Parchment/issue_comments#issuecomment-441169791_

**Comment by rechsteiner** [comment]
You need to initialize it with your view controllers: https://github.com/rechsteiner/Parchment/blob/master/Documentation/fixed-view-controller.md.

If you don’t want to initialize your view controllers up front, you can use PagingViewControllerDataSource: https://github.com/rechsteiner/Parchment/blob/master/Documentation/data-source.md

**Comment by rechsteiner** [comment]
Closing this now, but let me know if you are still having issues with this 🙂
