### ISSUE TITLE
Show badge in a tab

### ISSUE THREAD

**Issue by rafsouzap** [rechsteiner/Parchment#287]
Hi there... is it possible to show a badge in a tab option?

![Image of example badge](https://i.stack.imgur.com/lOTAL.png)

Or is there any possibility of joining a future roadmap?

**Comment by rechsteiner** [comment]
Hi! Sorry for the late reply. You can achieve this by creating your own `PagingCell` subclass. See `UnsplashExample` target for an example. 

I want to keep Parchment as generic as possible, so I don’t have any plans of adding built-in support for this. Hope that makes sense 🙂

Let me know if you need any help implementing the custom cell

**Comment by rafsouzap** [comment]
Hi @rechsteiner, I had not really thought about the option of creating my own PagingCell. Looking at the examples, including what you mentioned, I was able to simulate the badge and it worked. 

Tks!

**Comment by kodeflow** [comment]
> Hi there... is it possible to show a badge in a tab option?
> 
> ![Image of example badge](https://camo.githubusercontent.com/9d4a32acf18616652a56082ae5e6a00e43fa478e/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f6c4f54414c2e706e67)
> 
> Or is there any possibility of joining a future roadmap?

`menuItemSource = .nib(nib: UINib)`
