### ISSUE TITLE
How to go to next view controller when button tapped?

### ISSUE THREAD

**Issue by fcbmojtaba1995** [rechsteiner/Parchment#289]
hi I have 3 view controller that when tappd button go to next view controller. please help me thank.
`var pagingViewController : FixedPagingViewController?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Load each of the view controllers you want to embed
        // from the storyboard.
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let worksToDoViewControllers = storyboard.instantiateViewController(withIdentifier: "WorksToDoViewController")
        let worksDoingViewControllers = storyboard.instantiateViewController(withIdentifier: "WorksDoingViewController")
        let worksDoneViewControllers = storyboard.instantiateViewController(withIdentifier: "WorksDoneViewController")
        
        // Initialize a FixedPagingViewController and pass
        // in the view controllers.
        pagingViewController = FixedPagingViewController(viewControllers: [
            worksDoneViewControllers,
            worksDoingViewControllers,
            worksToDoViewControllers
            ])
              
        // Make sure you add the PagingViewController as a child view
        // controller and contrain it to the edges of the view.
        addChildViewController(pagingViewController!)
        contentView.addSubview((pagingViewController?.view)!)
        contentView.constrainToEdges((pagingViewController?.view)!)
        pagingViewController?.didMove(toParentViewController: self)
        
    }`

**Comment by fcbmojtaba1995** [comment]
I use this storyboard example
[https://github.com/rechsteiner/Parchment/tree/master/StoryboardExample](url)

**Comment by isaacraja15** [comment]
did you get this  anaswer ?

**Comment by fcbmojtaba1995** [comment]
No 

> did you get this anaswer ?

No Please Help

**Comment by fcbmojtaba1995** [comment]
> did you get this anaswer ?

No . Please Help me i use top example.

**Comment by isaacraja15** [comment]
no bro . im also waiting for reply

**Comment by rechsteiner** [comment]
Hi! You can programmtically select views using `pagingViewController.select(index: 1)`: https://github.com/rechsteiner/Parchment/blob/master/README.md#selecting-items

Does that work for you?
