### ISSUE TITLE
Can not set title programmatically 

### ISSUE THREAD

**Issue by veila** [rechsteiner/Parchment#291]
I am using storyboard to design UI and its title does not show. I know need to set the title properties earlier (e.g. in init). But is there anyway to set title do not need use init and reloadData ( reloadData need to set in viewDidAppear so it showing delay, and I dont like this)

**Comment by VishnuMU** [comment]
Hi Veila, Have you tried this?

 [https://github.com/rechsteiner/Parchment/issues/207#issuecomment-390404906](url)

**Comment by rechsteiner** [comment]
You don't need set the title in `init`, just make sure you set it before creating the `PagingViewController`. For instance, in the `StoryboardExample` you can change the title like this:

```Swift
let firstViewController = storyboard.instantiateViewController(withIdentifier: "FirstViewController")
let secondViewController = storyboard.instantiateViewController(withIdentifier: "SecondViewController")
    
firstViewController.title = "Another title"
```

You can also update the title after you've initialised the `PagingViewController`, but then you need to call `reloadData` as you said. In the latest version (1.6.0), you can also reload just the menu items using `reloadMenu`.

**Comment by Denok137** [comment]
When i create viewcontroller programatically without init ->

class MyViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "My name"  
}
}

title not set

but when i create by this way ->

class MyViewController: UIViewController  {
   
    init() {
        super.init(nibName: nil, bundle: nil)
        title = "My name"  
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
   }

all work correctly
any ideas?
