### ISSUE TITLE
Menu Bar coming under Status bar.

### ISSUE THREAD

**Issue by Ankit8946** [rechsteiner/Parchment#293]
The structure of my UI looks like below..
TabBarController ->(3rd Item in Tab bar) NavigationController-> BaseSegmentViewController
My BaseSegmentViewController subclasses PagingViewController. Not sure why this is happening.
It seems to work fine if  it is pushed in inside NavigationController when the navigation bar is visible.
First Image is what is wrong. Second case works fine

Here is how my class BaseSegmentViewController looks like..

class BaseSegmentViewController: PagingViewController<PagingIndexItem>, UINavigationControllerDelegate, UIGestureRecognizerDelegate  {

    var controllers : [UIViewController] {
        assertionFailure("Must be overriden in subclass")
        return [UIViewController()]
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        enableTransparentNavigationBar()
        navigationController?.hidesBarsOnSwipe = hidesBarOnSwipe()
    }
      
    override func viewDidLoad() {
        super.viewDidLoad()
        changeMenuBarAppeareance()
        dataSource = self
    }
    
    func changeMenuBarAppeareance() {
        textColor = Color.White.secondary
        selectedTextColor =  Color.white
        font = Font.semiboldSize17
        selectedFont = Font.semiboldSize17
        indicatorColor = Color.white
        borderColor = Color.white
        indicatorOptions = PagingIndicatorOptions.visible(height: 3.0, zIndex: 0, spacing: UIEdgeInsets(), insets: UIEdgeInsets())
        borderOptions = PagingBorderOptions.visible(height: 1, zIndex: 0, insets: UIEdgeInsets())
        menuItemSize = PagingMenuItemSize.fixed(width: CGFloat(Float(UIScreen.width)/Float(controllers.count)), height: 40.0)
        collectionView.backgroundColor = Color.clear
        collectionView.isScrollEnabled = false
    }
}

![img_6955](https://user-images.githubusercontent.com/14289212/51117592-436b9200-1834-11e9-9c39-14f7ae3cafc3.jpg)
![img_6956](https://user-images.githubusercontent.com/14289212/51117680-7f065c00-1834-11e9-99fa-4b72ef7a446a.PNG)

**Comment by rechsteiner** [comment]
This isn’t really an issue with Parchment. You need to setup you navigation controller so that the edges doesn’t extend below the navigation bar. E.g. https://stackoverflow.com/questions/30042131/uiviewcontroller-under-uinavigationbar

If you need a different behaviour you also have full control over the view hierarchy by subclassing PagingView 🙂
