### ISSUE TITLE
Content Inset Not Working Table View

### ISSUE THREAD

**Issue by muhasturk** [rechsteiner/Parchment#294]
If one of the page view controllers of PagingViewController is subclass of UIViewController includes table view, applying table view content inset seems not working. 

If it is kind of UITableViewController, content inset of table view is working properly.
https://github.com/rechsteiner/Parchment/blob/master/HeaderExample/ViewController.swift#L107

In order to reproduce problem change page view controller [super class to UIViewController](https://github.com/rechsteiner/Parchment/blob/master/HeaderExample/TableViewController.swift#L3) in demo project "HeaderExample"

Any help?

### PagingViewControllerDelegate
```swift
    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>,
                                 viewControllerForIndex index: Int) -> UIViewController {

        let height = pagingViewController.options.menuHeight + RestaurantPagingView.HeaderHeight
        let insets = UIEdgeInsets(top: height, left: 0, bottom: 0, right: 0)
        
        let viewController = GetOrderVC()
        viewController.externalTableDelegate = self
        viewController.externalContentInsets = insets

        return viewController
    }
```

### First Paging View Controller Which is NOT Subclass of UITableViewController
```swift
class GetOrderVC: UIViewController {
    
    private static let CellIdentifier = "CellIdentifier"
    
    var tableView : UITableView!

    var externalContentInsets : UIEdgeInsets!

...

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        tableView.contentInset = externalContentInsets
    }
```

**Comment by rechsteiner** [comment]
Hi @muhasturk! Are you suggesting that this is an issue with Parchment? As far as I can tell, this is just an issue with your application specific code.
