### ISSUE TITLE
Update single tab custom view without reload content

### ISSUE THREAD

**Issue by prsolucoes** [rechsteiner/Parchment#297]
Hi,

We have created a custom view to show a red sign on tab to show to the customer some updates on that page.

The problem is when the user enter on that page and we need remove the red sign/dot from the custom tab view. 

Today we are reloading all tabs with "reloadData" method, but it reload everything. 

My question is:
There is any method to reload only the tab view intead of all contents without need call reloadData or reloadAround?

Thanks.

**Comment by rechsteiner** [comment]
Unfortunately, this is not possible at the moment. I will look into adding support for this in the next version 🙂

**Comment by rechsteiner** [comment]
I've just published a new version (1.6.0) which adds support for this. Calling `reloadMenu` will only reload the menu items and not the content view controllers:

```Swift
pagingViewController.reloadMenu()
```
