### ISSUE TITLE
Replicate menu

### ISSUE THREAD

**Issue by jvsl** [rechsteiner/Parchment#298]
Hello. Is possible replicate this menu below using that lib? If yes, what I should override to reach it.
https://gyazo.com/b908ebaa19f9256e6f3dc748c73dd90c

**Comment by rechsteiner** [comment]
Hi @jvsl! This is definitely possible. You need to do something like the following:

- Create a subclass of `PagingCell` that sets the background color based on the selected state
- Set `menuItemSize` to your desired size. E.g: `.fixed(width: 15, height: 2)`
- Set `menuHorizontalAlignment` to `.center` 
- Set `indicatorOptions` and `borderOptions` to `.hidden`
- Add the `collectionView` to the navigation bar. See `NavigationBarExample` for more details. If you want the title above the menu dots, you need to create a custom `UIView` that contains the title label and the collection view and set that as the `titleView`.

Let me know if that works for you 🙂
