### ISSUE TITLE
How to disable load sibling/next view controllers?

### ISSUE THREAD

**Issue by prsolucoes** [rechsteiner/Parchment#300]
Hi,

How to don't let load sibling view controllers?

In our project we load remote data when we enter on each page, and today this library is creating the next view controller after Page X (ex: Page Y), and we are sending two requests.

How to disable sibling pages to load and only load single page that im inside?

Thanks.

**Comment by VishnuMU** [comment]
Greetings,

Parchment is optimized for performance and less memory usage.

I recommend you moveing the loading method to **PagingViewControllerDelegate** methods

`  func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    didScrollToItem pagingItem: T,
    startingViewController: UIViewController?,
    destinationViewController: UIViewController,
    transitionSuccessful: Bool)`

Also check this reply from the author [https://github.com/rechsteiner/Parchment/issues/158#issuecomment-376991069](url)
