### ISSUE TITLE
How to get view controller at index?

### ISSUE THREAD

**Issue by philipborbon** [rechsteiner/Parchment#301]
Need to update data of view controller at specific index.

**Comment by VishnuMU** [comment]
Where’s your source data at? inside the child view controller?

When do you want to update the data?

**Comment by philipborbon** [comment]
Inside child view controller.

Let's say I have 5 view controller and each controller has a data called "Person".

I changed the name of Person in 3rd view controller.

I want to pass the updated Person to 1st controller.

**Comment by VishnuMU** [comment]
You can keep the 'person' data on the main view controller and pass it to child view controllers on Parchment's delegate method.

This will work even if you have infinite child views.

**Comment by philipborbon** [comment]
Thanks for the hint @VishnuMU.

I will be using these delegate methods to update ViewController data.

```swift
protocol PagingViewControllerDelegate: class {
  func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    isScrollingFromItem currentPagingItem: T,
    toItem upcomingPagingItem: T?,
    startingViewController: UIViewController,
    destinationViewController: UIViewController?,
    progress: CGFloat)

  func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    willScrollToItem pagingItem: T,
    startingViewController: UIViewController,
    destinationViewController: UIViewController)

  func pagingViewController<T>(
    _ pagingViewController: PagingViewController<T>,
    didScrollToItem pagingItem: T,
    startingViewController: UIViewController?,
    destinationViewController: UIViewController,
    transitionSuccessful: Bool)
}
```
