### ISSUE TITLE
How start loading api data of all the views at launch?

### ISSUE THREAD

**Issue by gaffuuuu** [rechsteiner/Parchment#302]
I have an app with 3 viewcontrollers, all of them put in the fixedpagingcontroller. They download some data from api and they show them in cells... the issue is that when I swipe from the first to the second/third view controller, it takes time to load these data. I would like to know how i can load the views at launch...
Thanks

**Comment by VishnuMU** [comment]
Load the common data on parent view controller instead of childern.

Look at #301

**Comment by rechsteiner** [comment]
This isn't really an issue with Parchment. As @VishnuMU mentioned, you should be able to load the data in the view controller that contains Parchment.
