### ISSUE TITLE
Menu Drag Height Error

### ISSUE THREAD

**Issue by Smiller193** [rechsteiner/Parchment#303]
Hello I am. not sure if it is just me but when I drag the menu it has this weird nature which can be seen in the below gif.

![47389568-1ac77680-d6e3-11e8-837a-c462028229a8](https://user-images.githubusercontent.com/16108750/52901125-d6e60900-31cc-11e9-966c-d49709466fed.gif)

Im not sure if it is supposed to look like that and I remember you saying something about capping the menuHeight. Could you show an example of that?

**Comment by rechsteiner** [comment]
Hi @Smiller193! These things are not really part of the Parchment framework, I just created these examples to illustrate the possibilities. It's up you to decide how it's supposed to look. If you need to cap the menu height, change line 191 in the UnsplashExample like this:

```diff
- return height
+ return min(200, height)
```

**Comment by Smiller193** [comment]
thanks fixed
