### ISSUE TITLE
menuItemSize height > 40.0 ,problem

### ISSUE THREAD

**Issue by andmix** [rechsteiner/Parchment#309]
Parchment version 1.5.0, Swift version 4.0
I find the menu'height cant be changed, it was be setted to 40.0 in default options. Only menuItem 's Height can be effected

```
let pageVC = PagingViewController<PagingIndexItem>()
pageVC.frame = CGRect(x: 0.0, y: 0.0, width: width, height: height)
pageVC.menuItemSize = .sizeToFit(minWidth: (width / 3.0).rounded(), height: 60.0)
```

**Comment by andmix** [comment]
And I find the menu'height cant be changed, it was be setted to 40.0 in default options. Only menuItem 's Height can be effected

**Comment by rechsteiner** [comment]
Hi @andmix! I'm not sure if I understand you correctly. I just tried to add this to the `Example` target:

```
let pagingViewController = FixedPagingViewController(viewControllers: viewControllers)
pagingViewController.menuItemSize = .sizeToFit(minWidth: 100, height: 300)
```

And it seems to be working fine here:

![simulator screen shot - iphone x - 2019-03-03 at 16 51 59](https://user-images.githubusercontent.com/1238984/53697752-e2dce800-3dd4-11e9-92c4-b4fa179fae53.png)

**Comment by andmix** [comment]
Sorry!  It's my fault that I didn't express myself clearly .
By debugging your example code, I find the problem. 

![09_55_58__03_04_2019](https://user-images.githubusercontent.com/7136490/53706151-d0f65600-3e63-11e9-9a24-08636362790f.jpg)

This is my project：

![09_49_57__03_04_2019](https://user-images.githubusercontent.com/7136490/53705983-fcc50c00-3e62-11e9-8844-7ca62890a0b5.jpg)

In my project, I set the pageViewController' view frame directly, and this has caused some incorrect performance。

Sorry again for my poor English。。。
