### ISSUE TITLE
Dummy cells in menuItem [Calendar Example]

### ISSUE THREAD

**Issue by moosabaloch** [rechsteiner/Parchment#310]
Hey, first of all, Thanks a lot, it's a great library saved a lot of time.
I am just playing around with the features of **Calendar example**, I want to show **2**(in my case) dummy cells for the future date in `menuItems collectionView`, 
Why dummy? because those future dates should not be accessible, 
by doing this my selected date(_today's date_) will be in the center in `menuItems collectionView`.
Is this possible to do this using current functionality OR can you suggest how I can do this?

**Comment by rechsteiner** [comment]
Hi @moosabaloch! Yes, this should be possible!

For example, you can update `CalendarItem` with an `isSelectable` property:

```Swift
struct CalendarItem: PagingItem, Hashable, Comparable {
  let date: Date
  let dateText: String
  let weekdayText: String
  let isSelectable: Bool
  ...
}
```

Then create your own `PagingViewController` subclass, override `didSelectItemAt` and check if the item is selectable:

```Swift
class CustomPagingViewController: PagingViewController<CalendarItem> {
  
  override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    let pagingItem = visibleItems.pagingItem(for: indexPath)
    if pagingItem.isSelectable {
      super.collectionView(collectionView, didSelectItemAt: indexPath)
    }
  }
  
}
```

Then you just need to update your date source to set `isSelectable` to false if the date is later than today's date. You can also update the styling of `CalendarPagingCell` based on the `isSelectable` property.

Does that work for you?

**Comment by moosabaloch** [comment]
Yes it works from the menu side but not from the UIPageController
by swiping, it takes to the future date but it shouldn't.  😞

**Comment by moosabaloch** [comment]
@rechsteiner: In the current implementation, Is there any possibility to avoid generating pages for future dates?

**Comment by rechsteiner** [comment]
Hi @moosabaloch! Sorry for the late reply. Unfortunately, I don't know a way of achieving this at the moment. I guess one way to achieve this is to change `viewControllerForPagingItem` in `PagingViewControllerInfiniteDataSource` to return an optional `UIViewController`. You might need to do some additional changes. I guess you could fork Parchment and see if you get that working

**Comment by moosabaloch** [comment]
Thanks, I'll try.
