### ISSUE TITLE
Change Transition Animation

### ISSUE THREAD

**Issue by philipborbon** [rechsteiner/Parchment#315]
Is it possible to change transition animation?

I.e, fade out/ fade in animation on view change

**Comment by githubYiheng** [comment]
I have the same problem, is it possible to replace the collectionLayout?

**Comment by rechsteiner** [comment]
Hi @philipborbon! No, this is not possible to customize at the moment. Once we have support for custom page controllers (#80) it would be possible, but I don't have any ETA for that.
