### ISSUE TITLE
Reload Data From Given List Of Index

### ISSUE THREAD

**Issue by philipborbon** [rechsteiner/Parchment#316]
Is there a way to reload list of view controllers only at a given list of index/path/pageitem?

**Comment by rechsteiner** [comment]
This is not possible right now, but I will look into adding support for this 🙂

**Comment by rechsteiner** [comment]
I've been thinking a bit more about this lately and I don't think it would make sense to add an API for this. When calling `reloadData` the only view controllers that are re-created is the currently selected one and its two siblings. It wouldn't make any sense to reload view controllers outside of those as they're not initialized yet anyway (unless you are caching them somewhere). 

When it comes to the `PagingItem`s, you can reload them using `reloadMenu`. This will reload all of the paging items, but that is a quite cheap operation as we're only reloading the currently visible items.

Closing this issue, but let me know if you have any thoughts on this 🙂
