### ISSUE TITLE
Referring to variables within sub view controllers from main view controller

### ISSUE THREAD

**Issue by jackklink** [rechsteiner/Parchment#319]
I'm banging my head on the desk after trying to figure this out for hours. I am trying to figure out how to access elements located within the sub view controllers from my main view controller. 

My viewDidAppear which loads the scrollview very nicely:

override func viewDidAppear(_ animated: Bool) {

        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let songDetailsView = storyboard.instantiateViewController(withIdentifier: "SongDetailsView")
        let playerView = storyboard.instantiateViewController(withIdentifier: "PlayerView")
        let songRequestView = storyboard.instantiateViewController(withIdentifier: "SongRequestView")
        
        pagingViewController = FixedPagingViewController(viewControllers: [
                                                                                songDetailsView,
                                                                                playerView,
                                                                                songRequestView
                                                                          ])
        
        // Add the PagingViewController as a child view controller and contrain it to the edges of the view.
        addChild(pagingViewController)
        pagerView.addSubview(pagingViewController.view)
        pagerView.constrainToEdges(pagingViewController.view)
        pagingViewController.didMove(toParent: self)
    }

I would like to perform an action like the one below, however I get a "Fatal Error. Unexpectedly found nil" error on this line because I don't think I am accessing the view controller correctly due to the way it was loaded in by Parchment.

`PlayerView().songTitle.text = "Sample Text"`

Any help is much appreciated!

**Comment by rechsteiner** [comment]
Hi @jackklink! I'm don't see any reason why that should not work. In your example, it looks like you just need to change `PlayerView()` to `playerView`. Does that fix it?

**Comment by rechsteiner** [comment]
Did you manage to figure this out? 🙂

**Comment by bfstaff01** [comment]
is it possible to use PagingViewController with storyboard item? like FixedPagingViewController?

**Comment by rechsteiner** [comment]
@jackklink Closing this for now, but let me know if you are still having issues with this.

@bfstaff01 Yes, that is possible. Take a look at the guide here: https://github.com/rechsteiner/Parchment/blob/master/Documentation/data-source.md. In `viewControllerForIndex` you need to get the view controller you want from the storyboard.
