### ISSUE TITLE
Support for SwiftPM and Accio

### ISSUE THREAD

**Issue by rocklyve** [rechsteiner/Parchment#322]
Hey,
I tried to add this project with [Accio](https://github.com/JamitLabs/Accio), but a Manifest file is missing. 
Can you please add this? Maybe in the roadmap to version 2 :)

**Comment by rechsteiner** [comment]
Hi @rocklyve! I will look into adding this in the next version 🙂

**Comment by rechsteiner** [comment]
Should be working now (#345) 🙂 Can you target the `master` branch and verify that it works for you as well before I release a new version?
