### ISSUE TITLE
Separator or Divider between Menu items

### ISSUE THREAD

**Issue by tushar666** [rechsteiner/Parchment#323]
Hi,
Can we add Separator or Divider between Menu items
<img width="356" alt="Screenshot 2019-04-11 at 12 46 43 PM" src="https://user-images.githubusercontent.com/5293346/55938134-3fdf7f80-5c58-11e9-9825-2d5a77ff8dc2.png">

**Comment by rechsteiner** [comment]
Yes, this should be possible 🙂 You can either create a custom `PagingCell` that contains the separator, or provide a custom `PagingCollectionViewLayout` subclass that adds supplementary views based on the layout attributes for all the items.

You can take a look at `CalendarExample` on how to create you own `PagingCell` subclass. I can also provide an example using a custom collection view layout, but it's probably going to take some time to have that ready.
