### ISSUE TITLE
Possible for different Menu Item sizes?

### ISSUE THREAD

**Issue by ProAppleOS** [rechsteiner/Parchment#324]
Hi,

is it possible to have different menu item sizes (width) because some titles are big and some are not and i donÄt want all menu items to be big just to display the big one properly

**Comment by rechsteiner** [comment]
Yes, this is possible 🙂 Take a look at the `DelegateExample`. You need to implement this method and return the size based the text:

```
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat?
```
