### ISSUE TITLE
3D Touch doesn't work for StoryboardExample

### ISSUE THREAD

**Issue by emreisik95** [rechsteiner/Parchment#326]
Hi there, I'm using Storyboard example and storyboard has tableview. I add 3d touch for cells but it just work without Parchment. How can I fix this?

**Comment by rechsteiner** [comment]
I don't see any reason why that shouldn't work with Parchment. I'll take a look at it when I have some more time. Could just try to use the same view controller without Parchment and see if it is working then?

**Comment by emreisik95** [comment]
Yes when i try to use viewcontroller without the parchment it works very well. i couldn't understant why it doesn't work with parchment.

**Comment by rechsteiner** [comment]
Can you provide some details on how you've set up add 3D shortcuts? Are you using `registerForPreviewing`?
