### ISSUE TITLE
V1.6.0 Reload data says item doesn’t exist

### ISSUE THREAD

**Issue by sprzenus** [rechsteiner/Parchment#329]
`self.pagingViewController.reloadData(around: self.pagingViewController(self.pagingViewController, pagingItemForIndex: startIndex))` after loading data crashes with message: `Thread 1: Fatal error: pagingViewController:viewControllerForPagingItem: PagingItem does not exist`. It doesn’t matter if startIndex is 0 or last index of new data array.

**Comment by rechsteiner** [comment]
@sprzenus can you check what `self.pagingViewController(self.pagingViewController, pagingItemForIndex: startIndex)` is returning here?

**Comment by sprzenus** [comment]
It returns the first item of type `PagingIndexItem` for a new data

**Comment by rechsteiner** [comment]
But what is the value of the item? If you could provide any ways of reproducing this that would be great

**Comment by rechsteiner** [comment]
Any updates on this? I'm not able to reproduce the crash your are seeing
