### ISSUE TITLE
change tab back to the first one when click to different navigation tab

### ISSUE THREAD

**Issue by lephillips** [rechsteiner/Parchment#331]
I want to reset the select index back to the first tab (create tab in the screen shot) when I change the bottom navigation tab and go back. it tried func reloadMenu() as well as pagingViewController.select(index: 0), they both not working. here is my code

extension IndexReferralViewControler: UITabBarControllerDelegate {
    func tabBarController(_ tabBarController: UITabBarController, didSelect viewController: UIViewController) {
        let vc = UIApplication.topViewController(controller: viewController) as? IndexReferralViewControler
        if vc != self {
             [pagingViewController.reloadMenu()
![Screen Shot 2019-04-30 at 2 11 18 PM](https://user-images.githubusercontent.com/48699418/56993706-0496e900-6b52-11e9-9e04-037ee70fbe0d.png)

        }
    }
}

**Comment by rechsteiner** [comment]
`reloadMenu` will keep the currently selected index, so you need to use `pagingViewController.select(index: 0)`. I'm not sure why that shouldn't work. Are you sure the method is actually being called?

**Comment by sinhaGIT** [comment]
I am also facing same issue. have you solve your issue. if yes, then please help me 

I call the select method in viewWillAppear. and my code confirm executes. It select first page controller, but menu indicator are not moved to first page it remains on previous selected page.

Thanks.

**Comment by rechsteiner** [comment]
Hi @lephillips! Managed to find the issue you reported here (fixed in #371). Will release a new version soon 🙂 Thanks for the report
