### ISSUE TITLE
Custom page view size

### ISSUE THREAD

**Issue by khacdai37** [rechsteiner/Parchment#333]
Hi, 
I want to show page view with width size equal 2/3 screen width size device, so how I can do it? we have any property for that ?
Thanks.

**Comment by rechsteiner** [comment]
Hi @khacdai37! Do you want to show multiple pages at the same time, like in #197? In that case, Parchment currently does not support this. If you just want to change the size of the page view controller, you can create a `PagingView` subclass where you override the `setupConstraints` method (check out the `LargeTitlesExample`).
