### ISSUE TITLE
Prevent removing ViewControllers in FixedPagingViewController from hierarchy

### ISSUE THREAD

**Issue by nickdnk** [rechsteiner/Parchment#334]
Hello

I recently had to change to this lib because PagingMenuController that I used before (https://github.com/kitasuke/PagingMenuController) is no longer maintained.

I've managed to get it up and running, but I have one major issue: I have only two view controllers. The second VC kind of depends on the first one. It can tell the first VC to present a VC, display an alert etc. However, this doesn't work because it seems view controllers are removed from the view hierarchy when not visible. I know this makes a lot of sense for most use-cases, but is there any way to turn it off? I really just need both VCs to remain in the view stack regardless if they are visible or not.

Perhaps we could introduce a boolean option for all VCs or a delegate method that determines if a specific VC should be removed from the view hierarchy? Would save me a lot of headache.

**Comment by nickdnk** [comment]
Specifically, commenting out this code in `EMPageViewController.swift` fixes my problem entirely and everything works this way, but I realize it's not a great solution. I have very limited knowledge of how this library is built, so perhaps someone can come up with a clean solution.

``` 
private func removeChildIfNeeded(_ viewController: UIViewController?) {
    //viewController?.view.removeFromSuperview()
  
    #if swift(>=4.2)
    //viewController?.didMove(toParent: nil)
    //viewController?.removeFromParent()
    #else
    //viewController?.didMove(toParentViewController: nil)
    //viewController?.removeFromParentViewController()
    #endif
}
```

**Comment by rechsteiner** [comment]
Hi @nickdnk! There isn't really a way to achieve this without modifying the library like you mentioned. I also don't think I will add support for that scenario as it sounds a bit like an anti-pattern to reference the view hierarchy for something that isn't in view.

That said, I'm working on a new version of Parchment (#243) where you can use the menu independently from the page view controller. When that is ready you can use it with your own custom page view controller that doesn't remove the views (or use something like [Pageboy](https://github.com/uias/Pageboy) if they support that). I don't have a clear ETA when that is ready though.

**Comment by nickdnk** [comment]
@rechsteiner Hey. Sorry, this got shelved a bit.

I forked the repo and just commented out those lines and added my fork to Podfile. Kind of a hack, but works fine. The particular app that needs this is being entirely replaced in the near future, so there's no reason to spend time with this.
