### ISSUE TITLE
Gradient background not working if we replace an UIView instead of UIImageView in HeaderExample of Parchment

### ISSUE THREAD

**Issue by Abhishek-Dwivedi** [rechsteiner/Parchment#335]
I am using parchment library for pagination in my application. When I replace the UIImageView with a UIView in the header example of Parchment, gradient background is not working. I only see white screen.

Gradient works if I add separately in a view, with Parchment, I believe it is overlapped by some layer. I also tried this link but did not work. https://github.com/rechsteiner/Parchment/issues/181

Actual result is a white screen in the header view, expected is the gradient fill.

**Comment by rechsteiner** [comment]
This doens't sound like an issue with Parchment. I just looked at the HeaderExample and it works perfectly fine to make everything transparent if that's what you are trying to do. I would just inspect the view hierarchy and figure out which views are overlapping, or if it's just an problem with your gradient view.
