### ISSUE TITLE
Add Image in menu items.

### ISSUE THREAD

**Issue by Akshay4593** [rechsteiner/Parchment#337]
Hi,
can we add image in menu items?

<img width="368" alt="Screenshot 2019-05-10 at 5 55 31 PM" src="https://user-images.githubusercontent.com/50488281/57527536-915d5600-734d-11e9-96ec-2bf6cfb41373.png">

**Comment by nikolaveljic64** [comment]
You can use custom cell.See IconsExample. And if you want you can use .nib.

pagingViewController.menuItemSource =  .nib(nib: UINib.init(nibName: "CollectionViewCell", bundle: nil))

Or much easier, is to make two uiview , and through delegate change image.
