### ISSUE TITLE
Problem with HeaderExample

### ISSUE THREAD

**Issue by nikolaveljic64** [rechsteiner/Parchment#338]
![30n1r8](https://user-images.githubusercontent.com/18101315/57543338-6296ae00-7354-11e9-9342-837cb52dfa47.gif)

How to fix this problem?

**Comment by Alexookah** [comment]
@rechsteiner have the same issue

**Comment by Alexookah** [comment]
only workaround is to use in TableViewController viewDidLoad

tableView.contentInsetAdjustmentBehavior = .never

but is this the correct way?

**Comment by qiaqiaxian** [comment]
@rechsteiner have the same issue

how to solve this problem?

**Comment by rechsteiner** [comment]
Hi! These examples are just to illustrate what you can do with Parchment and are not actually part of the framework itself. I can look into improving the example code when I have some more time, but it's not really anything specific to Parchment here.

**Comment by AlexanderPan** [comment]
I got same issue.

**Comment by rechsteiner** [comment]
@AlexanderPan As I mentioned above, this functionality is not part of Parchment and it's only an example of what you can do with the framework. If you need this functionality in your app, its up to you to figure out how to solve that in a good way. I will look into improving the examples, but feel free to open a PR with improvement if you solve it in your app 🙂

**Comment by rechsteiner** [comment]
I've updated the example project with a fix for this now (#443) 🙂 All the example targets have also been combined into a single target now. You can find the header example in `HeaderViewController.swift`
