### ISSUE TITLE
Scroll not resizing

### ISSUE THREAD

**Issue by cwestMobile** [rechsteiner/Parchment#340]
I am having an issue using the example for resizing the menu on scroll. I have a delegate hooked up and all that jazz, it is working except it is not actually resizing the menu. It is just scrolling up and it gives the appearance the child view controller is scrolling over half the menu.

Please let me know if you need more info or anything. Thanks :)

<img width="385" alt="TopScroll" src="https://user-images.githubusercontent.com/16341697/57733474-73953700-7654-11e9-913f-569004160c3b.png">

I also have a question on the following method from the Unsplash example...

func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, isScrollingFromItem currentPagingItem: T, toItem upcomingPagingItem: T?, startingViewController: UIViewController, destinationViewController: UIViewController?, progress: CGFloat) {
    guard let destinationViewController = destinationViewController as? ImagesViewController else { return }
    guard let startingViewController = startingViewController as? ImagesViewController else { return }
    
    // Tween between the current menu offset and the menu offset of
    // the destination view controller.
    let from = calculateMenuHeight(for: startingViewController.collectionView)
    let to = calculateMenuHeight(for: destinationViewController.collectionView)
    let height = ((to - from) * abs(progress)) + from
    updateMenu(height: height)
  }
If you aren't sure what type the destination and starting view controllers are going to be, how would you handle that? Let me know if you need more info. :)

**Comment by cwestMobile** [comment]
I also have a question on the following method from the Unsplash example...

`func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, isScrollingFromItem currentPagingItem: T, toItem upcomingPagingItem: T?, startingViewController: UIViewController, destinationViewController: UIViewController?, progress: CGFloat) {
    guard let destinationViewController = destinationViewController as? ImagesViewController else { return }
    guard let startingViewController = startingViewController as? ImagesViewController else { return }
    
    // Tween between the current menu offset and the menu offset of
    // the destination view controller.
    let from = calculateMenuHeight(for: startingViewController.collectionView)
    let to = calculateMenuHeight(for: destinationViewController.collectionView)
    let height = ((to - from) * abs(progress)) + from
    updateMenu(height: height)
  }`

If you aren't sure what type the destination and starting view controllers are going to be, how would you handle that? Let me know if you need more info. :)

**Comment by rechsteiner** [comment]
Hi @cwestMobile! It's a bit hard for me to tell without looking at your code. The Unsplash example should work, so maybe you can cross-reference your implementation to that one? These examples are just to illustrate what you can do with Parchment and are not actually part of the framework itself. I'm trying to keep Parchment as generic as possible, so it's up to you to figure out how this should work in your app.
