### ISSUE TITLE
Function call three time

### ISSUE THREAD

**Issue by quynv186** [rechsteiner/Parchment#350]
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {

Func called 3 times => ViewController init 3 times => Bug

Value is wrong. When choose calendar "20/Thu" but using print, value is "21/Thu". 

How can I get the correct value when func being called 3 times?

**Comment by atalayasa** [comment]
I think it is calling for your current, before and after view controller. It makes my structure broken but I do not know how to prevent it.

**Comment by rechsteiner** [comment]
Yes, that's correct. Parchment will call your data source for the current view controller and its two siblings. The is the same behaviour the `UIPageViewController` has. The reason for this is that you would see a noticeably lag when swiping between view controller if you had to allocate them on the fly. You can always allocate the view controllers up front and cache them in a property if you want to prevent them from being re-allocated. This is how `FixedPagingViewController` works.
