### ISSUE TITLE
Menu Indicator not scrolling upon select function calling

### ISSUE THREAD

**Issue by sinhaGIT** [rechsteiner/Parchment#355]
I am facing an issue with this, issue when I select 3rd page and change tab from tabBarController now I want to switch back 1st tab and 1st Page through select Method it selects first page, but menu indicator not going to first page position.

I tried following on viewWillAppear

pagingViewController.select(index: 0, animated: true)

Thanks.

**Comment by rechsteiner** [comment]
Hi @sinhaGIT! This should be fixed in #371 🙂 You can target the `master` branch for now. Will release a new version soon!
