### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by nickdnk** [rechsteiner/Parchment#356]
Hello

I have a view controller in a tab-bar setup. When I click the tab-bar for this controller, I receive this error. I'm using the `FixedPagingViewController` with only 2 view controllers.

`Unbalanced calls to begin/end appearance transitions for <ClassOfFirstViewController: 0x1028f1c00>.`

Everything works. There are no crashes or weird behaviour, but it seems something is wrong when this happens, at least according to: https://stackoverflow.com/questions/9088465/unbalanced-calls-to-begin-end-appearance-transitions-for-detailviewcontroller

My code for the view controller in the tab-bar looks like this:

```
override open func viewDidLoad() {
        super.viewDidLoad()

       // I initialize the view controllers here as:
       let viewController 1 = self.storyboard?.instantiateViewController(withIdentifier: "whatever1") as! ClassOfFirstViewController
       let viewController 2 = self.storyboard?.instantiateViewController(withIdentifier: "whatever2") as! ClassOfSecondViewController

        pagingMenuController = FixedPagingViewController.init(viewControllers: [viewController1, viewController2])
        pagingMenuController.dataSource = self;
        pagingMenuController.delegate = self;
        pagingMenuController.select(index: 0)
        pagingMenuController.indicatorOptions = .visible(height: 3, zIndex: Int.max, spacing: UIEdgeInsets.zero, insets: UIEdgeInsets.init(top: 0, left: 0, bottom: 0, right: 0))
        pagingMenuController.indicatorColor = UIColor.green
        pagingMenuController.backgroundColor = UIColor.black
        pagingMenuController.menuBackgroundColor = UIColor.black
        pagingMenuController.selectedTextColor = UIColor.lightGray
        pagingMenuController.textColor = UIColor.lightGray
        pagingMenuController.font = UIFont.systemFont(ofSize: 11);
        pagingMenuController.selectedFont = UIFont.systemFont(ofSize: 12);
        pagingMenuController.menuItemSize = .sizeToFit(minWidth: 0, height: 40)
        pagingMenuController.borderColor = UIColor.red
        pagingMenuController.borderOptions = .visible(height: 0, zIndex: 0, insets: UIEdgeInsets.zero)
        pagingMenuController.menuInteraction = .none
    
        addChild(pagingMenuController)
        controllerViewContainer.addSubview(pagingMenuController.view)
        
        pagingMenuController.didMove(toParent: self)
        pagingMenuController.view.translatesAutoresizingMaskIntoConstraints = false
        
        NSLayoutConstraint.activate([
            pagingMenuController.view.leadingAnchor.constraint(equalTo: controllerViewContainer.leadingAnchor),
            pagingMenuController.view.trailingAnchor.constraint(equalTo: controllerViewContainer.trailingAnchor),
            pagingMenuController.view.bottomAnchor.constraint(equalTo: controllerViewContainer.bottomAnchor),
            pagingMenuController.view.topAnchor.constraint(equalTo: controllerViewContainer.topAnchor)
        ])
        
}
```

`viewController1` and `viewController2` do *not* initialize any child view controllers or present anything when created, and I didn't encounter this error on the previous library I used.

Any idea what I might be doing wrong?

I should add that this is unrelated to the "hack" (https://github.com/rechsteiner/Parchment/issues/334) I had to implement to get the library to work like  I wanted to. It gives this error warning on the release version as well.

Edit: I had to add the "controllerViewContainer" as a subview with top-bottom-width-height constraints to "safe area" of the view controller's view and use that. If I don't do this, the menu in the top simply disappears. Removing this view and going directly with self.view removes the menu but does not remove the warning.

**Comment by rechsteiner** [comment]
Hi @nickdnk! Thank for the report. This should be fixed now (#373). Sorry for taking so long to get a fix ready – I'll release a new version soon 🙂
