### ISSUE TITLE
Navigate ViewControllers With Custom Button in Storyboard Example

### ISSUE THREAD

**Issue by vijay1864** [rechsteiner/Parchment#358]
Hello guys,
I have implemented functionality with storyboard example
But I got an issue when I click on the next button I need to go next view controller and whenever I click the previous button and need to go to the previous screen
How to do that
please help
Thanks in advance
![Simulator Screen Shot - iPhone 8 Plus - 2019-07-12 at 12 12 29](https://user-images.githubusercontent.com/28288700/61107787-533ff800-a49e-11e9-87b6-f5b7e76aa731.png)
![Simulator Screen Shot - iPhone 8 Plus - 2019-07-12 at 12 12 26](https://user-images.githubusercontent.com/28288700/61107789-53d88e80-a49e-11e9-920e-15b9fc445e1f.png)

**Comment by rechsteiner** [comment]
Hi @vijay1864! You can navigate programatically using `pagingViewController.select(index:)` or `pagingViewController.select(pagingItem:)`. Does that work for you?
