### ISSUE TITLE
Customize hidden indicators

### ISSUE THREAD

**Issue by LeeTwelve** [rechsteiner/Parchment#359]
Hello,
How to customize a hidden indicators?

What I have: 
![1](https://user-images.githubusercontent.com/5905995/61113219-e5a0c580-a4b7-11e9-86c7-3b3c332aa6bc.png)

What I want:
![1 2](https://user-images.githubusercontent.com/5905995/61113233-f05b5a80-a4b7-11e9-9e45-85bd4cccf473.png)

Is it possible?

**Comment by rechsteiner** [comment]
Hi @LeeTwelve! If each title should have a line underneath, then the easiest would be to create your custom `PagingCell` subclass where you add that line. You can check of the CalenderExample or UnsplashExample targets for details on how to create your own cells 🙂
