### ISSUE TITLE
Caching before and after view controller causes crashing

### ISSUE THREAD

**Issue by atalayasa** [rechsteiner/Parchment#362]
I am using `PagingViewControllerInfiniteDataSource` for my purposes and in my view controller I am using collection view. As far as I understood while doing debug library is calling 3 times for current, before and after view controller init function for caching. However, it causes a problem that is even if collection view data has been changed it can't reflect changes in my view controller because it already cached. How can I prevent it? I'd appreciate if anyone can help to solve issue. Here is my code for PageViewController

```
extension PagingVC: PagingViewControllerInfiniteDataSource {

    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForPagingItem pagingItem: T) -> UIViewController {
        return MainVC(pager: self)
    }

    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemBeforePagingItem pagingItem: T) -> T? {
        let calendarItem = pagingItem as! CalendarItem
        return CalendarItem(date: calendarItem.date.addingTimeInterval(-86400)) as? T
    }

    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, pagingItemAfterPagingItem pagingItem: T) -> T? {
        let calendarItem = pagingItem as! CalendarItem
        return CalendarItem(date: calendarItem.date.addingTimeInterval(86400)) as? T
    }
}
```

**Comment by rechsteiner** [comment]
Hi @atalayasa! One option is to call `reloadData` when something in your data source changes, but that will re-create the entire view controller, which might be a bit too expensive. Ideally, I guess you should pass something down to the view controller instances that they can subscribe to changes to directly. That way you don't need to create new view controller instances every time the data changes.
