### ISSUE TITLE
InputAccessoryView Doesn't Work with Parchment

### ISSUE THREAD

**Issue by kareemarab** [rechsteiner/Parchment#363]
I have two view controllers side by side using Parchment. One of them is a chat view controller  (ChannelLogController) which has a messageInputBar. I'm trying to use InputAccessoryView with the messageInputBar but I keep getting this error message:

Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<UICompatibilityInputViewController: 0x7ffbfd898c70> should have parent view controller:<space_ios.ChannelLogController: 0x7ffbfc025e00> but requested parent is:<UIInputWindowController: 0x7ffbfd0a9a00>'

Anyone know how this can be fixed?

**Comment by rechsteiner** [comment]
Hi @kareemarab! Are you sure this is an issue related to Parchment and not just specific to your implementation? I tried setting up a view controller with a text field and an accessory view using the `inputAccessoryView` property and it seems to work just fine.

**Comment by rechsteiner** [comment]
Any updates on this?
