### ISSUE TITLE
Header menu customization

### ISSUE THREAD

**Issue by velthune** [rechsteiner/Parchment#366]
Hi, 
is it possible to customize the height for menu?

The only way I found is:

    self.pagingViewController.menuItemSize = .sizeToFit(minWidth: width, height: height)

Specifying an height > 40, the whole menu goes behind the view of the current view controller.

**Comment by rechsteiner** [comment]
Hi @velthune! Setting `menuItemSize` should work. Are you overriding the layout constraints for the paging view or something?

**Comment by rechsteiner** [comment]
Any updates on this?

**Comment by velthune** [comment]
Hi, I'm working on another project so I can't give you any updates, yet. I'm sorry
