### ISSUE TITLE
All the menuItem is not getting dispalyed in pagingViewController in landscape mode on tab for iOS 12.4 version

### ISSUE THREAD

**Issue by shalsuman** [rechsteiner/Parchment#368]
In PagingViewController , suppose the Paging item is 5 then only 4 is getting displayed landscape mode on iPad . The func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell is not getting called for 5 times and its returning after 4th call. Is it some library issue ?

**Comment by rechsteiner** [comment]
Hi @shalsuman! I'm not aware of any issues related to this. Do you have any screenshots and/or some ways of reproducing this?

**Comment by ankit0812** [comment]
@shalsuman  +1 
I have the same issue. I am using a containerview which points to a view controller that is using PagingViewController<PagingIndexItem>. After dragging towards the next controller then i see the item to be visible
