### ISSUE TITLE
Value of type 'CustomPagingViewController' has no member 'menuItemSource'

### ISSUE THREAD

**Issue by seangee777** [rechsteiner/Parchment#369]
Hi,
It seems there's a mistake in your last version and "MenuItemSource" not defined and it replaced with "MenuItemClass" every where in Parchment !
e.g. below line in Parchment (where MenuItemSource should have been defined) :

`  public var menuItemClass: Parchment.PagingCell.Type `

**Comment by rechsteiner** [comment]
Hi @seangee777 🙂 I'm not sure I understand exactly what the issue is. The `menuItemSource` property replaced the `menuItemClass`. I can't find any remaining references to `menuItemClass`.

**Comment by seangee777** [comment]
I added Parchment to my App using CocoaPods,
When I'm trying to run my App I get this error :
`Value of type 'CustomPagingViewController' has no member 'menuItemSource'  `
I wanted to use "Unplash Example" from your sample project, So I exactly copied the "Unplash Example" folder contents and It just shows above error !
The error says that "MenuItemSource" has not defined !
So I compared your sample project that I'd downloaded from GitHub with my project,
Interesting! after comparing frameworks I realized the framework in my app have no "menuItemSource" and everywhere in framework instead of "menuItemSource" you'll face "menuItemClass" !

<img width="1391" alt="Error" src="https://user-images.githubusercontent.com/23621768/64122280-64c6c180-cdb6-11e9-9fcd-e644eef781ab.png">

<img width="1391" alt="Framework" src="https://user-images.githubusercontent.com/23621768/64122350-9cce0480-cdb6-11e9-854c-53c0f615bddf.png">

**Comment by rechsteiner** [comment]
It sounds like your are using an old version of Parchment in your app. Can try to upgrade to the latest version?

**Comment by seangee777** [comment]
I used Parchment by adding below line to my pod file :
` pod 'Parchment' `
My Xcode is updated And I think Xcode uses the latest version of Parchment automatically . .
Please correct me if I'm doing wrong.

Thanks for your nice support

**Comment by rechsteiner** [comment]
Awesome!
