### ISSUE TITLE
Resize Menu Item After Orientation Change

### ISSUE THREAD

**Issue by Pratik948** [rechsteiner/Parchment#375]
Hi @rechsteiner you've done a great job, this is an awesome library.

I'm facing one issue with size of Menu item when orientation changes, I have implemented `widthForPagingItem` for dynamic sizing cell but this method is not getting called when orientation changes and all menu item uses cached size(I guess). I have also tried to invalidate layout of collection view in `viewDidLayoutSubviews` but it didn't ask me for new size.

Is it expected behaviour or is it a bug? and what if I want to resize items when orientation changes? if I call `self.pagingViewController.reloadMenu()` in `viewDidLayoutSubviews` it asks for new size but doesn't apply it. can you guide me through it?

Thanks

**Comment by rechsteiner** [comment]
Thanks @Pratik948! This definitely seems like a bug. I will look into getting that fixed soon 🙂

**Comment by rechsteiner** [comment]
Hi @Pratik948! This should be fixed in the latest `master` now (#444). I'll release a new version pretty soon

**Comment by pratikgajbhiye222** [comment]
@Pratik948  Have to got this?
