### ISSUE TITLE
UISearchController compatibility

### ISSUE THREAD

**Issue by artemkalinovsky** [rechsteiner/Parchment#383]
Is it possible to add UISearchController to large navigation bar with Parchment paging controller?

**Comment by rechsteiner** [comment]
I haven't tried myself, but I'm pretty sure that should be possible. Are you running into some issues with it?

**Comment by artemkalinovsky** [comment]
Yep, UISearchController doesn't work when pagingController.collectionView is added to navigation bar:(

**Comment by rechsteiner** [comment]
Can you provide a bit more details on what is not working? This doesn't sound like something that's specific to Parchment

**Comment by artemkalinovsky** [comment]
Hey!
On today's morning I've figured out that it was my fault and it wasn't specific to Parchment😅

@rechsteiner thank you for help!
