### ISSUE TITLE
Using Unsplash Example with UITableView instead of collection view images

### ISSUE THREAD

**Issue by seangee777** [rechsteiner/Parchment#387]
Hi,
First thanks for the great design of Unsplash,
I want to use Unsplash Example with a tableview as contents source instead of collectionView images in it's body.
But I don't know how to remove that collection view images and it's constraints and where to implement my TableView ?
I don't want to define constraints and  I mean just keeping the above category imageBar and using tableview as contents for each category (instead of images )

**Comment by rechsteiner** [comment]
Hi @seangee777! You need to replace the `ImagesViewController` with your own view controller implementation. This isn't really something that's related to Parchment – it's up to you to decide how to implement your app specific view controllers.
