### ISSUE TITLE
Can't update width existing menu item

### ISSUE THREAD

**Issue by Pro2005** [rechsteiner/Parchment#389]
Hi there. Firstly thx for the library.
In my case when user opens ViewController I need to show only one menu item and on viewDidAppear I perform API request. When I get response from the server I need to add another tab. Everything work except I can't update width of existing first menu item. I'm using
` func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat?`

So when user opens the screen this method returns screen.bounds.width (because there is only one tab), but after adding new menu item I want to show them together. So the method returns screen.bounds.width / 2.  But As I see, it's not possible
`  func itemWidth(for pagingItem: T) -> CGFloat {
    if let width = widthCache[pagingItem] {
      return width
    } else {
      let width = widthForPagingItem?(pagingItem, false)
      widthCache[pagingItem] = width
      return width ?? options.estimatedItemWidth
    }
  }`
Because You use cache width for existing item. Is there way to cleat cache ?

**Comment by AntoGeekz** [comment]
Same problem https://github.com/rechsteiner/Parchment/issues/341 ?

**Comment by rechsteiner** [comment]
How are you reloading the menu when the data comes back? `reloadMenu()`?

**Comment by AntoGeekz** [comment]
Yes @rechsteiner , in my case, I call "reloadMenu" because I just want to reload the tabs content, not all the view controllers.

**Comment by AntoGeekz** [comment]
Hey,

I tested again the issue in my app using this repo. I updated the repo to the last release and.... it works! The problem no longer seems to be present.

**Comment by rechsteiner** [comment]
Great! @Pro2005 feel free to re-open this issue if you are still seeing the issue
