### ISSUE TITLE
how to add pull to refresh to pageview.scrollView 

### ISSUE THREAD

**Issue by alexdecor** [rechsteiner/Parchment#391]
I tried to add a pull to refresh to pageview.scrollView, is there a way to do it, thank you.

**Comment by rechsteiner** [comment]
Hi @alexdecor! I don't think `pageView.scrollView` would be the correct place to add pull-to-refresh. That scroll view is only scrolling horizontally. If you need pull-to-refresh inside one of your tabs you need to add it to your own view controller.
