### ISSUE TITLE
PagingViewController only load first cell on first appear

### ISSUE THREAD

**Issue by destantifw** [rechsteiner/Parchment#393]
when page first appears, PagingViewController only show the first cell, the next cell will appear after swipe.

[first appear]
![Screen Shot 2019-10-09 at 15 16 57](https://user-images.githubusercontent.com/14884055/66464759-c4954400-eaa9-11e9-856b-aaa796774b55.png)

[after being swiped]
![Screen Shot 2019-10-09 at 15 17 04](https://user-images.githubusercontent.com/14884055/66464829-e68ec680-eaa9-11e9-906e-9c8f4abda6b4.png)

i use Parchment 1.7.0. How do i fix it?

**Comment by rechsteiner** [comment]
Hmm, it's a bit hard to tell without seeing more of your implementation. How are you setting up the `PagingViewController`?

**Comment by leacode** [comment]
I have the same issue here. 

Here's my code:

`
pagingViewController = FixedPagingViewController(viewControllers: viewControllers)
        pagingViewController.menuItemSize = .fixed(width: (UIScreen.screenWidth - 16.0) / 4.0, height: 44.0)
        pagingViewController.indicatorOptions = .visible(height: 2.0,
                                                         zIndex: Int.max,
                                                         spacing: UIEdgeInsets(top: 0, left: 30, bottom: 0, right: 30),
                                                         insets: UIEdgeInsets.zero)
        pagingViewController.indicatorColor = .white
        pagingViewController.menuBackgroundColor = .clear
        pagingViewController.selectedBackgroundColor = .clear
        pagingViewController.textColor = .white
        pagingViewController.selectedTextColor = .white
        pagingViewController.borderColor = .clear
        pagingViewController.font = UIFont(name: "PingFangSC-Medium", size: 16.0) ?? UIFont.systemFont(ofSize: 16.0, weight: .medium)
        
        addChild(pagingViewController)
        containerView.addSubview(pagingViewController.view)
        containerView.constrainToEdges(pagingViewController.view)
        pagingViewController.didMove(toParent: self)

`


The strange part is. The first time when I push into the view it will be ok. The second time  it will just show one item on the top. Then after a bit of scroll. The whole menu will be shown.

**Comment by leacode** [comment]
@destantifw  It took me whole afternoon to figure this out.

`
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    if (pagingViewController?.visibleItems.items.count ?? 0) < items.count {
        pagingViewController?.reloadMenu()
        pagingViewController?.collectionView.layoutIfNeeded()
    }
}
`

The visibleItems only return 1 at the first time.
 When you scroll it will recalculate and return the actual items count.
Hope it'll be helpful.

**Comment by rechsteiner** [comment]
@leacode it shouldn't be necessary to do all that. When are you calling code that you shared? It sounds a bit like you are setting it up too late, e.g. viewDidAppear. Could that be the case?

**Comment by Sparrow-Iv** [comment]
I have the same issue.


I use fixedPagingVC in some tabs and add it in viewDidLoad, the first VC works well, however, when i switching the tab, the next VC shows only a single item in the menu.

don't really want to reload the menu collection in viewWillAppear

**Comment by zuil7** [comment]
i encountered this one also in IOS 13. The work around i did is this
 addChild(pagingViewController)
 containerView.addSubview(pagingViewController.view)
 containerView.constrainToEdges(pagingViewController.view)
 pagingViewController.didMove(toParent: self)
 **pagingViewController.collectionView.layoutIfNeeded()** 

Hope it helps

**Comment by rechsteiner** [comment]
A new version is available that I _think_ should fix this: https://github.com/rechsteiner/Parchment/releases/tag/v2.1.0. Let me know if you're still seeing any issues!
