### ISSUE TITLE
Default width of custom item

### ISSUE THREAD

**Issue by Antonyyy13** [rechsteiner/Parchment#396]
Hey, 

I encounter a new problem that I can't find the origin of.

The current situation : I'm using a custom data source + custom paging cell.  I want to display 2 items. 

The problem: The width used for items are not the width wanted.

I'm using the protocole PagingViewControllerDelegate and the method  "func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat?" to define the width according the content of my cell. (a title + Little imageview) 

I can define whatever I want in this method, like a width value at 50, it doesn't work. The first time, I have always my two items sharing the width of the main View controller (for example 150 & 150 each) or If I have one item, it Will use the full width available of the main VC. And if I swipe from the first item to the second, in this case, all items are using the correct width (50).

What do I forget to define? Why the first time my items don't use the width defined in the delegate?

Thank for your help & your lib!

**Comment by rechsteiner** [comment]
Hi @AntoGeekz! When are you setting up the delegate? It sounds a bit like you are setting the delegate after then view has already been displayed.

**Comment by AntoGeekz** [comment]
Hey @rechsteiner, I'm initializing everything in my ViewController's viewDidLoad method. (This VC is loaded in another VC btw). And yep, I was thinking about the same issue, but I did something like in your exemple initializing everything in viewDidLoad.

**Comment by Antonyyy13** [comment]
Ok stupid problem found... an event triggered a process which restarted the initialization of the paging ^^" Fail ! (and this process was indeed started after the UI created)
