### ISSUE TITLE
Menu Item is not showing

### ISSUE THREAD

**Issue by OCEO-YJ** [rechsteiner/Parchment#397]
Hello, 

First of all, thank you for sharing really good project! 

I was following the basic usage by using Fixedpage method, I can swipe the view controllers, however, but the view does not show the title menu. I followed exactly same as demo, but still top of title menu is hidden.

Is there way I can make it to be shown?

**Comment by ziad007** [comment]
You have to put .title = "" in the init() of the view controller
and 
   pagingViewController.view.topAnchor.constraint(equalTo: view.topAnchor, constant: 90)
