### ISSUE TITLE
Background Color Attribute Not Working

### ISSUE THREAD

**Issue by Rhodesyork** [rechsteiner/Parchment#40]
The backgroundColor attribute under the PagingTheme does not seem to be working when I change it through my structure, it remains white. 
![screen shot 2017-03-08 at 20 34 07](https://cloud.githubusercontent.com/assets/17065930/23722869/ebd26114-043e-11e7-971c-b51b52b71b14.png)

**Comment by rechsteiner** [comment]
Yeah, sorry about that. I've forgotten to actually handle that option. Will push a fix this weekend 🙌

**Comment by Rhodesyork** [comment]
Thanks a lot, awersome project by the way! 👏🏻

**Comment by rechsteiner** [comment]
Thanks! Fixed in #41. Releasing a new version `v0.3.0` now 👍
