### ISSUE TITLE
When using a HeaderView above PagingViewController how to use custom view controllers rather than UITableViewController?

### ISSUE THREAD

**Issue by ankit0812** [rechsteiner/Parchment#402]
Whenever I try to use a controller from storyboard I get a crash on tvProfileList (It is a tableView on my custom view controller from storyboard). How should I initialize this as I know that IBOutlets get initialized after push/present

    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForIndex index: Int) -> UIViewController {
        if index < contentViewControllers.count {
            let viewController = self.contentViewControllers[index]
            // Inset the table view with the height of the menu height.
            let height = pagingViewController.options.menuHeight + CustomPagingView.HEADER_VIEW_HEIGHT
            let insets = UIEdgeInsets(top: height, left: 0, bottom: 0, right: 0)
            viewController.tvProfileList.contentInset = insets
            viewController.tvProfileList.scrollIndicatorInsets = insets
            viewController.tvProfileList.delegate = self
            return viewController
        }
        return UIViewController()
    }

**Comment by ankit0812** [comment]
@rechsteiner Any updates for this?

**Comment by rechsteiner** [comment]
Hi @ankit0812. This doesn't seem to be an issue related to Parchment. Take a look at the Storyboard example if you want to see how to initialize a view controller from storyboard.
