### ISSUE TITLE
Disable scrolling to page

### ISSUE THREAD

**Issue by kirilldobr** [rechsteiner/Parchment#403]
Currently, there is no delegate method like `canShowPageAtIndex: `, which could prevent from scrolling to a specific page without reloading the whole datasource and removing that page completely.

**Comment by rechsteiner** [comment]
Hi @kirilldobr. I'm not sure how a delegate like that would work. Should you still be able to select the item in the menu or should that also be disabled for that item? If you have a page in the middle that is disabled, should you then scroll all the way to the next enable item? Would like to hear more about the use-case you are having for this type of delegate.

**Comment by jvashisht** [comment]
Hi @kirilldobr , Have you find any solution for this?

**Comment by rechsteiner** [comment]
@jvashisht could you explain a bit more about the use-case your are trying to solve here? I'm still not sure what the desired behaviour should be here.

**Comment by rechsteiner** [comment]
Closing this issue as I'm not sure how this could be done. Let me know if you have any more details on the behaviour you're trying to achieve.
