### ISSUE TITLE
Crash on iOS 12

### ISSUE THREAD

**Issue by thihaaung6245** [rechsteiner/Parchment#408]
I am experiencing crash on iOS 12.1, 12.4.2. Please see below attachment for error log.

<img width="1519" alt="Screenshot at Dec 21 23-51-02" src="https://user-images.githubusercontent.com/10526402/71311417-3ea05c80-244d-11ea-8d57-b682365e08b1.png">
<img width="1679" alt="Screenshot at Dec 21 23-51-30" src="https://user-images.githubusercontent.com/10526402/71311446-61cb0c00-244d-11ea-92e2-9cbf41943674.png">

Here is the way I set up: 
```
func setUpView() {
        // Instantiate
        pagingViewController.dataSource = self
        pagingViewController.delegate = self
        
        // Customize the menu styling.
        pagingViewController.menuItemSize = .sizeToFit(minWidth: 80, height: 47)
        pagingViewController.menuHorizontalAlignment = .center
        pagingViewController.menuTransition = .scrollAlongside
        pagingViewController.font = Font.Regular.of(size: 12.0)
        pagingViewController.selectedFont = Font.Regular.of(size: 12.0)
        pagingViewController.selectedTextColor = Color.Black.instance()
        pagingViewController.indicatorColor = Color.DarkGreen.instance()
        pagingViewController.indicatorOptions = .visible(
            height: 3,
            zIndex: Int.max,
            spacing: .zero,
            insets: UIEdgeInsets(top: -0.5, left: 0, bottom: 0.5, right: 0)
        )
        pagingViewController.borderOptions = .visible(
            height: 2,
            zIndex: Int.max,
            insets: UIEdgeInsets(top: 0, left: -100, bottom: 0, right: -100)
        )
        
        // Make sure you add the PagingViewController as a child view
        // controller and contrain it to the edges of the view.
        addChild(pagingViewController)
        containerView.addSubview(pagingViewController.view)
        containerView.constrainToEdges(pagingViewController.view)
        pagingViewController.didMove(toParent: self)
}
```

Here is how this library is used.
1. Paging view is init on viewDidLoad
2. I download array of dates from api
3. After I downloaded, assign reusable paging view controller which depending on dates
4. Then reload and select the appropriate controller using paging `select(index: index, animated: true)`

Did I do something wrong? The weird thing is, it's only happening at iOS 12. Not at iOS 13 latest.

**Development Machine** : Xcode 11.3
**Parchment Version** : 1.6.0

**Comment by Tawfikk** [comment]
hi, you're fixed this crash ?

**Comment by rechsteiner** [comment]
Hmm, this looks a bit like an issue with the way you initialise your view controllers. Could you try just allocating your view controllers programatically and see if that removes the crash?

**Comment by rechsteiner** [comment]
@thihaaung6245 did you manage to look into this?
