### ISSUE TITLE
Ability to add logo to top menu.

### ISSUE THREAD

**Issue by RyPoints** [rechsteiner/Parchment#409]
Could you tell me a good method or show me to the area of code to change to add a logo to the top menu.

Essentially I am looking to add a leading constraint to the menu so I can move it to the right slightly to make room for a logo.

**From this:**
![top1](https://user-images.githubusercontent.com/10441971/71426369-48001380-265d-11ea-9a6e-47efc5ad8926.png)

**To this:**
![top2](https://user-images.githubusercontent.com/10441971/71426370-4afb0400-265d-11ea-85eb-50be3c4edae1.png)

**Comment by RyPoints** [comment]
I figured it out with the help of this answer here: [](https://github.com/rechsteiner/Parchment/issues/268)

First you reformat that answer back to provide a CustomPagingView for the top.  Then you add a constant to the leadingAnchor.

```
class CustomPagingView : PagingView {
  override func setupConstraints() {
    pageView.translatesAutoresizingMaskIntoConstraints = false
    collectionView.translatesAutoresizingMaskIntoConstraints = false

    NSLayoutConstraint.activate([
      pageView.leadingAnchor.constraint(equalTo: leadingAnchor),
      pageView.trailingAnchor.constraint(equalTo: trailingAnchor),
      pageView.topAnchor.constraint(equalTo: topAnchor, constant: 40),
      pageView.bottomAnchor.constraint(equalTo: bottomAnchor),

      collectionView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 40),
      collectionView.trailingAnchor.constraint(equalTo: trailingAnchor),
      collectionView.topAnchor.constraint(equalTo: topAnchor),
      collectionView.heightAnchor.constraint(equalToConstant: options.menuItemSize.height),
    ])
  }
}

class CustomPagingViewController : FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      options: options,
      collectionView: collectionView,
      pageView: pageViewController.view)
  }
}
```

After this you can load your logo after the CustomPagingViewController setup and add it with:

`customPagingViewController.view.addSubview(imageView)`

**Comment by rechsteiner** [comment]
Great! Another option is to use version 2.0. There you can definitely multiple PagingItem types, so you could have one for you logo and one for the menu items. The benefit of that approach is that the logo would scroll alongside the menu items if that's something you want.
