### ISSUE TITLE
How to clear the sizeCache of menu?

### ISSUE THREAD

**Issue by gowtham1094** [rechsteiner/Parchment#411]
My application need to show the menu equally by the width if total width is lesser than the total screen width, else it should occupy its needed space.

For Example:

```
Scenario 1:
Screen Width - 350
Total Menu width of 5 items - 250 (50+50+50+50+50)
Since it is lesser than screen width so my menu width need to spread equally - 350/5 -> 70

```
```
Scenario 2:
Screen Width - 350
Total Menu width of 5 items - 360 (60+50+60+70+120)
Since it is greater than screen width so each and every menu need to occupy in their own width itself.
```

Also my application supports orientation so in single view controller itself there will be possible of having two different sets of menu width.

I am using PagingViewControllerDelegate widthForPagingItem in-order to assign width for each and every menu, but problem with this is PagingSizeCache which fetch the width from delegate for the very first time and cache it. Because of this every time it stick to the same width even though inside delegate function i have a logic to change the width based on screen width.

Is there any work around to solve my problem?

**Comment by rechsteiner** [comment]
Hi @gowtham1094! This is provided by default using [menuItemSize](https://github.com/rechsteiner/Parchment/blob/master/README.md#menuitemsize):

```Swift
pagingViewController.menuItemSize = .sizeToFit(minWidth: 100, height: 100)
```

Does that work for you?

**Comment by rechsteiner** [comment]
I just made some improvements to invalidating the size cache. You can now manually invalidate the size cache by calling `reloadMenu` (#444) Available in `master` until the next version is out

**Comment by gowtham1094** [comment]
@rechsteiner , Sorry for late response. 
And Yes this will work Thank you so much for this fix.  When can we expect the next version?
