### ISSUE TITLE
Menu height is 0 by default, and looks weird when I set it

### ISSUE THREAD

**Issue by hatimmakki** [rechsteiner/Parchment#413]
Hi
I am facing a problem with the menu height.
- menu appears on iPhone 8 but doesn't appear on iPhone 11
- it appears on iPhone 11 when I set the height, but it looks weird.

example iPhone 11 pro without setting the height:
https://drive.google.com/file/d/1AeRp7AZz5WrFvABmegKVaKKtjYMvzaoz/view?usp=sharing

example  iPhone 11 pro after setting the height:
https://drive.google.com/file/d/17s1LXCAddqVXXW26ABkH17ywnyXGwYCI/view?usp=sharing

example iPhone 8 without setting the height:
https://drive.google.com/file/d/1529LUdcqzxXmdIwby4cUc4dVhJrLUCgP/view?usp=sharing

code:
`    override func viewDidLoad() {
        super.viewDidLoad()
        
        let brd = UIStoryboard(name: "Main", bundle: nil)
        let firstViewController = brd.instantiateViewController(withIdentifier: "StatsDailyViewController")
        let secondViewController = brd.instantiateViewController(withIdentifier: "StatsMonthlyViewController")
        
        overallViewController = brd.instantiateViewController(withIdentifier: "StatsOverallViewController") as? StatsOverallViewController
        
        
        let pagingViewController = FixedPagingViewController(viewControllers: [
          firstViewController,
          secondViewController,
          overallViewController!
        ])
        
        // Make sure you add the PagingViewController as a child view
        // controller and contrain it to the edges of the view.
        
       // set the menu height
       pagingViewController.menuItemSize = .sizeToFit(minWidth: 50, height: 90)

        addChild(pagingViewController)
        view.addSubview(pagingViewController.view)
        view.constrainToEdges(pagingViewController.view)
        pagingViewController.didMove(toParent: self)
        pagingViewController.delegate = self
        
//        pagingViewController.
        // Do any additional setup after loading the view.

//        pagingViewController.reloadMenu()
        
    }
`

How can I fix this issue?
I want the menu always shown

**Comment by rechsteiner** [comment]
Hi @hatimmakki! It sounds a bit like the menu is extending below the edges of the navigation bar. Could you use the view inspector in Xcode to check if that's the case?

**Comment by rechsteiner** [comment]
@hatimmakki did you figure this out?
