### ISSUE TITLE
PagingCell menu button doesn't work

### ISSUE THREAD

**Issue by HakanSAYAR** [rechsteiner/Parchment#414]
I created ButtonPagingCell and this cell contains only buttons for menu item. Unfortunately, scrolling doesn't work when the menu items are tapped. Scrolling works when I add anything instead of a button. 
How can I fix this issue?

**Comment by rechsteiner** [comment]
Can you provide some more details on your implementation? It doesn't sound like this is an issue with Parchment, but rather that the setup in your custom cell is causing the scrolling to not work.

**Comment by rechsteiner** [comment]
@HakanSAYAR any updates on this?
