### ISSUE TITLE
PagingViewControllerDataSource recall many times

### ISSUE THREAD

**Issue by i1020242** [rechsteiner/Parchment#415]
func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForIndex index: Int) -> UIViewController
- call many times and wrong index in case of function numberOfViewControllers return value>2

**Comment by HakanSAYAR** [comment]
yes you're right man, i have the same problem. Did you find any solution?

**Comment by HakanSAYAR** [comment]
> func pagingViewController(_ pagingViewController: PagingViewController, viewControllerForIndex index: Int) -> UIViewController
> 
> * call many times and wrong index in case of function numberOfViewControllers return value>2

 yes you're right man, i have the same problem. Did you find any solution?

**Comment by rechsteiner** [comment]
Parchment will call the `viewControllerForIndex` methods for the currently selected view controller _and_ for the two sibling view controllers. See this comment for the reason behind that: https://github.com/rechsteiner/Parchment/issues/350#issuecomment-527575222. 

Is that what's happening for you or are you seeing some other behaviour?

**Comment by i1020242** [comment]
I wanna custom header on first time when view appear, but the function return wrong index? how do I fix it?

**Comment by rechsteiner** [comment]
I'm not sure I understand exactly what you mean, but if you want to do something only the first time something is displayed you could probably have some kind of state variable that you set either in the `viewControllerForIndex` or have a closure/delegate from the view controller that you call in `viewDidAppear`. Does that work for you?
