### ISSUE TITLE
Question: Is it possible to hide the top menu?

### ISSUE THREAD

**Issue by alexjameslittle** [rechsteiner/Parchment#421]
I'd like to use this library as just the paging between the view controllers without the top menu, would you be open to this functionality?

**Comment by rechsteiner** [comment]
It's possible to hide the menu using your own `PagingView` subclass (see #378), but I wouldn't recommend using Parchment if you're never displaying the menu. If you only need the paging of view controller you could use `UIPageViewController` directly. Another good option is https://github.com/uias/Pageboy if you have a fixed number of view controllers.

**Comment by alexjameslittle** [comment]
Thank's for the tip, will just use `UIPageViewController` for custom implementation. Thanks for the quick response!
