### ISSUE TITLE
Getting a white scrollable view (1px)

### ISSUE THREAD

**Issue by mavris** [rechsteiner/Parchment#425]
Hi,
I am using my own cells for MenuItems and I get this white line on the menu. Any ideas?
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-18 at 00 23 58](https://user-images.githubusercontent.com/3520168/74689818-3c584580-51e5-11ea-8f4a-a79be58f28a6.png)
PS. It's scrollable if that's help

**Comment by rechsteiner** [comment]
That's a border view that is added by default. You can remove it by setting:

```
pagingViewController. borderOptions = .hidden
```
