### ISSUE TITLE
I am not able to set select paging item for static data source I.e selecting items in parchment(2.0.1)

### ISSUE THREAD

**Issue by amolPawar1221** [rechsteiner/Parchment#428]
Set index programmatically for static viewcontrollers array

**Comment by LeeTwelve** [comment]
With non-static dataSource select don't work too.

**Comment by LeeTwelve** [comment]
@amolPawar1221 You should use `select` in `viewDidAppear` but this way have a side effect. You will see swipe a page on viewController.

**Comment by amolPawar1221** [comment]
Yes that work for me but side effect is there

**Comment by rechsteiner** [comment]
This should be fixed in `master` now. Will create a new release once I have done a bit more tested, but please check it out and see if it works for you 🙂
