### ISSUE TITLE
Swipe back navigation action

### ISSUE THREAD

**Issue by XRadevFRT** [rechsteiner/Parchment#430]
Greetings everyone,

Lovely library! I've been using and modifying it in my projects for a while. I have a question tho...
How can I trigger the default navigation swipe back action when I am at the first view controller (first on the left), or any other? I've been trying some stuff, but I just can't seem to make it work...

Will appreciate your help...
Thanks!

**Comment by rechsteiner** [comment]
Thanks @XRadevFRT! This isn't really something specific to Parchment and would be the same for any view where you want to trigger back swipe from everywhere on the screen. This thread might be a good starting point: https://stackoverflow.com/questions/22244688/navigation-pop-view-when-swipe-right-like-instagram-iphone-app-how-i-achieve-thi/22244990#22244990
