### ISSUE TITLE
Paging forward resets UIViewController.view layout, paging backward does not

### ISSUE THREAD

**Issue by bryan1anderson** [rechsteiner/Parchment#431]
I'm not even sure how to describe what I'm seeing. Basically I have a container view that houses a PagingViewController

The pages all have different heights, which tell the container view to change height on `pagingViewController: PagingViewController, didScrollToItem`

When I score forward, the appears, slides off to the left of the window, and then flies back in, its a very jarring transformation.

When I scroll backwards though, everything smoothly animates.

I'm at a total loss. Nothing different is happening when I am swiping forward vs swiping backward 

Here is a gif to demonstrate it
![Image 2](https://user-images.githubusercontent.com/7976521/75571420-67793b00-5a16-11ea-8caa-f53e7113fbb9.gif)

**Comment by rechsteiner** [comment]
Hi @bryan1anderson! I'm not really sure what would be causing this. Are you able to reproduce it in a smaller case/using the example targets? I'm also struggling a bit too understand which parts are which here. What is the menu here and what is the content view controllers?

**Comment by rechsteiner** [comment]
Need more details to help with this. Would be great if you could open new issues where you explain a bit more what the actual issue is and provide a way to reproduce it 🙂
