### ISSUE TITLE
widthForPagingItem delegate method causes leak with new PagingViewControllerSizeDelegate

### ISSUE THREAD

**Issue by rocxteady** [rechsteiner/Parchment#432]
Hello.

I have just migrated the project to 2.0.1 and started to use the new delegate and noticed it causes leaks. When I dismiss the view controller that has PagingViewController, the view controller is removed from memory but the child view controllers that belong to PagingViewController are stayed in the memory.

I have just created and simple code showing what I did:
https://gist.github.com/rocxteady/3f562c2b2bd2262ff1c6f40a7bd11052

I took a screenshot that shows the memory graph.
<img width="1407" alt="Screen Shot 2020-02-28 at 21 45 10" src="https://user-images.githubusercontent.com/3393424/75577789-ca4cef80-5a73-11ea-8192-35fefab02970.png">

See the child view controllers called PirtViewController which should have been released from the memory.

Thank you.

**Comment by rocxteady** [comment]
I have just sent a pull request which solves this issue: #433

**Comment by rechsteiner** [comment]
This should be fixed now and will be included in the next release. Thanks again for the PR!
