### ISSUE TITLE
errors in Swift Package Manager v.2.0.0

### ISSUE THREAD

**Issue by indiraAman** [rechsteiner/Parchment#436]
there are errors "Use of undeclared type 'UIViewController' "in files: PagingStaticDataSource,  PagingFiniteDataSource 
and  in  file PagingViewController -  "Cannot convert value of type '[UIViewController]' to expected argument type '<<error type>>' "

**Comment by rechsteiner** [comment]
Hi @indiraAman! This was fixed in #420. I'm planning on release a new version very soon, but in the meantime you can just target the `master` branch 🙂

**Comment by rechsteiner** [comment]
The new version is now released: https://github.com/rechsteiner/Parchment/releases/tag/v2.1.0
