### ISSUE TITLE
Add another view in navigation item titleview.

### ISSUE THREAD

**Issue by MiteshiOS** [rechsteiner/Parchment#437]
I added paging viewcontroller collection view into navigation bar.

     navigationItem.titleView = pagingViewController.collectionView
     pagingViewController.menuHorizontalAlignment = .center
     pagingViewController.selectedScrollPosition = .center
<img width="327" alt="Screenshot 2020-03-05 at 3 54 52 PM" src="https://user-images.githubusercontent.com/17427703/75972577-a832f180-5ef9-11ea-8c4f-6f12e883cf2f.png">

Now i wants to add another button on top left side of navigation bar. Can you please let me know how can i do this ?
I tried it with by adding new view into title view but not get success.
Thank you.

**Comment by rechsteiner** [comment]
Hi! It depends a bit if you want the button to be scrolling along with the menu items. If not, you should be able to just add a button using `navigationItem.leftBarButtonItem` on the view controller. If you want to button to scroll with the menu, you can create a custom `PagingCell` and add that to you data source. See the `MultipleCellsExample` target for an example of how to add multiple cell types.

**Comment by MiteshiOS** [comment]
Adding as navigationItem.leftBarButtonItem leads to this type of result. Why collection view moves that much ? I don't want my button scrollable, fix will be fine.

<img width="325" alt="Screenshot 2020-03-05 at 4 59 57 PM" src="https://user-images.githubusercontent.com/17427703/75977755-17f9aa00-5f03-11ea-98e2-e5d0fa612b12.png">

Also can you please let me know it is possible to go at specific page index outside view did load. I have 4 pages and on that button click(left side navigation bar) i wants to transfer at no 4 view controller.

**Comment by rechsteiner** [comment]
You need to modify the frame of the titleView. This isn't really specific to Parchment, it would be the same regardless of the view you put in the navigation bar. 

You can select items using the `select(index:)` method: https://github.com/rechsteiner/Parchment#selecting-items

**Comment by MiteshiOS** [comment]
Please check below screenshot. It say has no member and also `select(index:) ` is not working in demo `MultipleCellsExample`
I tried both turn by turn.

<img width="1384" alt="Screenshot 2020-03-05 at 5 55 37 PM" src="https://user-images.githubusercontent.com/17427703/75981616-e1c02880-5f0a-11ea-9d3b-ac25807284c7.png">

**Comment by rechsteiner** [comment]
Ah, that’s a bug in the latest version. Same as this one I assume #435. I’øl get that fixed as soon as possible

**Comment by MiteshiOS** [comment]
Thank you. Please try to provide update as soon as possible. Because at the time of integration i seen methods and i thought it fits perfect as my requirement but this issue breaks me. 
Thank you and will wait for update.

**Comment by rechsteiner** [comment]
This should be fixed now. I need to do a bit more testing before creating a new release, so you need to target the `master` for now. Let me know if you find any issues!
