### ISSUE TITLE
Initial index still not working on the latest master

### ISSUE THREAD

**Issue by Haeuncs** [rechsteiner/Parchment#439]
I just tested it with the latest master and it still doesn't seem to work.
pagingViewController.select(index: 3) -> go to index 4
But in viewDidAppear it works fine.

_Originally posted by @Haeuncs in https://github.com/rechsteiner/Parchment/issues/435#issuecomment-595556062_

**Comment by rocxteady** [comment]
Can you share the code? I have just tested and it works fine.

**Comment by rocxteady** [comment]
I agree. I couldn't face the issue on my sample app but it did not work on our real app. It went to next page like you mentioned.

**Comment by rechsteiner** [comment]
Ah okay, thanks. Could you share a bit more about your implementation? I haven't been able to reproduce any issues with just the example targets

**Comment by Haeuncs** [comment]
I think I found the cause of this bug.
You can see this problem by calling reloadData() before the initial selection.

    pagingViewController.reloadData()
    pagingViewController.select(index: 3)

**Comment by rechsteiner** [comment]
Great, thanks! I'll get that fixed as soon as possible 🙂

**Comment by rechsteiner** [comment]
Should be fixed in #440 now! @Haeuncs can you verify that it works for you as well?

**Comment by rocxteady** [comment]
Mine works. Thank you @rechsteiner .

**Comment by Haeuncs** [comment]
It works perfectly!
Thank you. 😀
