### ISSUE TITLE
[Question] track current selected viewController

### ISSUE THREAD

**Issue by AYastrebov** [rechsteiner/Parchment#44]
Hello @rechsteiner !

Is there a way to track the index of currently selected viewController, when using `FixedPagingViewController `?

**Comment by rechsteiner** [comment]
Hi! It's currently not possible, but I will add this to the next release. I'm planning on adding a delegate that looks like this:

```Swift
public protocol FixedPagingViewControllerDelegate : class   {
  func fixedPagingViewController(
    fixedPagingViewController: FixedPagingViewController,
    willScrollToItem: ViewControllerItem,
    atIndex index: Int)
  
  func fixedPagingViewController(
    fixedPagingViewController: FixedPagingViewController,
    didScrollToItem: ViewControllerItem,
    atIndex index: Int)
}
```

**Comment by rechsteiner** [comment]
Added in #46. This lets you set a `FixedPagingViewControllerDelegate` on the `itemDelegate` property, which gives you a `ViewControllerItem` struct that contains the selected view controller ✌️
