### ISSUE TITLE
Paging Indicator not scrolling when customized Paging Item Width

### ISSUE THREAD

**Issue by devjkkim** [rechsteiner/Parchment#446]
Thank you for providing awesome library.

func pagingViewController(_ pagingViewController: PagingViewController, widthForPagingItem pagingItem: PagingItem, isSelected: Bool) -> CGFloat {
    guard let item = pagingItem as? PagingIndexItem else { return 0 }
    
    let insets = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
    let size = CGSize(width: CGFloat.greatestFiniteMagnitude, height: pagingViewController.options.menuItemSize.height)
    let attributes = [NSAttributedString.Key.font: pagingViewController.options.font]
    
    let rect = item.title.boundingRect(with: size,
                                       options: .usesLineFragmentOrigin,
                                       attributes: attributes,
                                       context: nil)
    
    let width = ceil(rect.width) + insets.left + insets.right
    
    if isSelected {
      return width * 1.5
    } else {
      return width
    }
  }

Paging Indicator scrolls properly along the viewController scrolling with the above code.
But when I change the inset UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20) to UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 10) or any other value, paging indicator does not scroll but jump to the selected item without scrolling.
What is the problem with me?

Thank you.

**Comment by rechsteiner** [comment]
Hi @devjkkim! This should be fixed in the latest `master` branch. Will release a new version soon!

**Comment by devjkkim** [comment]
I got it. thank you :)
