### ISSUE TITLE
pagingViewController.select(index: 1) not working

### ISSUE THREAD

**Issue by srgrbth** [rechsteiner/Parchment#447]
Hi, I'm poor in english.
I appreciate your library.

I modify my project source from v.1.7.0 to v2.0.1

pagingViewController.select(index: 1) work on v.1.7.0.
but, is not work on v.2.0.1.

So, I experiment some cases.

When I print("index: \(index)") in func pagingViewController(_: PagingViewController, viewControllerAt index: Int),

my project print like below.

index: 0
index: 1
index: 1
index: 1
index: 0
index: 1

but, example(Header Example) project print like this.

index: 1
index: 0
index: 2

My project has also three tabs.

Is this cause select(index: 1) not work?
Thanks a lot!

**Comment by rechsteiner** [comment]
Hi @srgrbth! Can you target the master branch and see if it works there? I’ll release the fixes with a new version soon!

**Comment by rptoma** [comment]
It is solved now! Awesome, thanks! Looking forward to the new release.

**Comment by srgrbth** [comment]
@rechsteiner Hi, in master branch, it is work. I also looking forward to new release. Thanks a lot!

**Comment by rechsteiner** [comment]
Great! The new version was just released now: https://github.com/rechsteiner/Parchment/releases/tag/v2.1.0
