### ISSUE TITLE
How to get list of all view controllers added in PagingViewController ?

### ISSUE THREAD

**Issue by MiteshiOS** [rechsteiner/Parchment#451]
I wants to get list of all added view controllers in PagingViewController. Can you please let me know method name.

**Comment by rechsteiner** [comment]
Hi @MiteshiOS! There's not method for getting all the view controllers. You can get the currently selected view controller from `pageViewController.selectedViewController`, or you could keep track of which view controller are initialised using the `viewControllerAt ` data source method.

**Comment by MiteshiOS** [comment]
Okay. Thank you for the information. But here there is one another thing is, paging controller doesn't allow go back to specific page.

[Test.zip](https://github.com/rechsteiner/Parchment/files/4324250/Test.zip)

Please check this attached demo. I am hiding my navigation bar on 3rd controller. Now on 3rd controller i have an previous button to go back at 2nd controller. But it is not moving by using below function.
`func select(index: Int, animated: Bool = false)`

Also after tap on previous button if you do swipe then it goes back to correct view controller but index is wrong on collection view added in navigation bar.

**Comment by rechsteiner** [comment]
Thanks, will take a look. Which version of Parchment are you using?

**Comment by MiteshiOS** [comment]
Latest one. Just downloaded master branch code from here and added module of Parchment into code.

**Comment by rechsteiner** [comment]
Hmm, it looks calling `setNavigationBarHidden` while scrolling seems to cause some weird issues with the page view controller. I tried with the native `UIPageViewController` as well and it's the same issue. The page view controller seem to get out of sync. I'm not sure that this is something I can fix inside Parchment, but I found a way to solve it for you app. When calling the `setNavigationBarHidden`, make sure it executes on the next run loop: 

```Swift
DispatchQueue.main.async {
  if pi.index == 2 {
      self.navigationController?.setNavigationBarHidden(true, animated: true)
  } else{
      self.navigationController?.setNavigationBarHidden(false, animated: true)
  }
}
```

That should fix it 🙂

**Comment by MiteshiOS** [comment]
Thank you for the information. But what about index is not going back ? 
Have you seen third view controller button click for going back to previous ?

**Comment by rechsteiner** [comment]
That worked fine when I recreated your setup. Are you sure the button @IBAction of the button is hooked up properly?

**Comment by MiteshiOS** [comment]
Yes it hooked up properly. Can you please check same into my demo. 
<img width="907" alt="Screenshot 2020-03-13 at 2 09 53 PM" src="https://user-images.githubusercontent.com/17427703/76604242-6545cf00-6534-11ea-9489-082ccbc01263.png">

**Comment by MiteshiOS** [comment]
Did you get the issue in my demo ? Where navigation bar is hidden for 3rd controller and we are trying to go back with `select(index:)` method, it is not going back.
Otherwise if it works well at your end as you said you recreated my demo, then i request you to please share that code so i can identify my mistake. Thank you
