### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by rechsteiner** [rechsteiner/Parchment#452]
The next major version of Parchment aims to include the following features:

- [x] **SwiftUI support** (#460)
It would be nice to provide a SwiftUI wrapper for Parchment. Need to figure out the API for this, but it looks like it should be possible without too many changes.

- [x] **Self-sizing cells** (#461)
Today, if you want the menu items to be based on the cell's content you need to implement the `widthForPagingItem` delegate method and manually calculate the size (See [SizeDelegateViewController.swift](https://github.com/rechsteiner/Parchment/blob/master/Example/Examples/SizeDelegate/SizeDelegateViewController.swift)). With self-sizing cells the menu item size would be automatically  calculated based on the constraints of your cells.

- [x] **Custom PageViewController** (#468)
Parchment has been using [`EMPageViewController`](https://github.com/emalyak/EMPageViewController) as a replacement for `UIPageViewController` to get better delegate methods. This has been working great, but it's a bit hard to make changes and improvements to the implementation. There's also been a few issues that would be nice to get fixed:
 
    * Appearance transitions sometimes gets called out of order (#426)
    * Overrides the native `isPagingEnabled` bounce when scrolling fast to next page ([link](https://github.com/rechsteiner/Parchment/blob/master/Parchment/Classes/EMPageViewController.swift#L662)).
    * No support for RTL languages (#161)
    * ~No support for spacing between pages (#197)~ Spacing between pages will probably not be part of the 3.0 release.
    &nbsp;

    Making our own PageViewController would make it easier to add additional features and write tests to ensure that it's behaving correctly. It would also be nice to remove any third-party dependencies from Parchment. 

- [x] **RTL language support** (#468)
Parchment currently doesn't support right-to-left languages. There's a few ways to work around this (#161), but it should be supported out-of-the-box. The new page view controller implementation should make this possible.

**Comment by rechsteiner** [comment]
Decided to remove vertical layouts from the 3.0 release. A pre-release of 3.0 is now available: https://github.com/rechsteiner/Parchment/releases/tag/v3.0.0-beta. Please let me know if anyone finds any issues

**Comment by sgmtal** [comment]
I have tried this new version and I get 2 errors ... any ideas?
<img width="1051" alt="Captura de pantalla 2020-09-27 a las 18 27 51" src="https://user-images.githubusercontent.com/20724496/94370269-53520500-00ef-11eb-8069-fb3e0a267ebb.png">
<img width="1060" alt="Captura de pantalla 2020-09-27 a las 18 28 01" src="https://user-images.githubusercontent.com/20724496/94370277-5947e600-00ef-11eb-8c8a-82cc0be66bd7.png">

**Comment by rechsteiner** [comment]
Thanks for letting me know @sgmtal! There's a new beta release out now called `3.0.0-beta2`: https://github.com/rechsteiner/Parchment/releases/tag/v3.0.0-beta2

**Comment by rocxteady** [comment]
<img width="846" alt="Screen Shot 2020-09-29 at 13 22 14" src="https://user-images.githubusercontent.com/3393424/94546638-d93c9000-0256-11eb-9713-63d799532571.png">

I am getting this errors. Can you help?

**Comment by rechsteiner** [comment]
Hi @rocxteady! I'm not able to reproduce that error you are seeing. I've tried setting up multiple fresh projects, but all the different ways of installing seems fine. Could you share a bit more on your setup?

**Comment by rechsteiner** [comment]
New version is out now! https://github.com/rechsteiner/Parchment/releases/tag/v3.0.0
