### ISSUE TITLE
The example does not work on iOS 13

### ISSUE THREAD

**Issue by davidhsu1115** [rechsteiner/Parchment#454]
I've downloaded the example project. It works perfectly on iOS 12, however when I switch to iOS 13, the example app always crash with the following message:

dyld: Library not loaded: @rpath/Parchment.framework/Parchment
  Referenced from: /private/var/containers/Bundle/Application/998EF613-DC4F-4A0F-972A-249D5D84349A/Example.app/Example
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/998EF613-DC4F-4A0F-972A-249D5D84349A/Example.app/Frameworks/Parchment.framework/Parchment: code signature invalid for '/private/var/containers/Bundle/Application/998EF613-DC4F-4A0F-972A-249D5D84349A/Example.app/Frameworks/Parchment.framework/Parchment'

**Comment by rechsteiner** [comment]
Hmm, it’s working fine here. Are you using the latest beta or something?

**Comment by davidhsu1115** [comment]
Follow up: It turns out if i use person signing certificate it will cause the crash.
I change it to my team signing certificate every thing works perfectly fine.
