### ISSUE TITLE
Stretch Header Example

### ISSUE THREAD

**Issue by faizannaseem96** [rechsteiner/Parchment#463]
![New Mockup 1](https://user-images.githubusercontent.com/43570403/77843316-48a4ca80-71b5-11ea-9d41-dec77ac0013f.png)
I have to design this type of screen where i have image as header, some title and description and bottom i have page menu where i can swipe between sections. When i scroll the page menu's table view whole content of screen should scroll.  Stretch Header example project is not working in this scenario. What other possible approach?

**Comment by rechsteiner** [comment]
Hi! It depends a bit on the behavior you need. If the entire screen should scroll, including the menu, you don’t really need Parchment. You could just use UIPageViewController directly, where each UIViewController has their own header, menu and table view. Is that what you’re trying to achieve?

**Comment by faizannaseem96** [comment]
You can assume that this is a restaurant detail page screen where we have static restaurant image, its title and description and below we have categories in menu (.i.e. Lunch, Dinner, Breakfast) and below there is a tableview where we have menu item list. I could not use UIPageViewController directly where each UIViewController has only listing. what i want is to scroll list whole content on screen should scroll.

**Comment by rechsteiner** [comment]
Ahh sorry, I think I misunderstood you. You just want the image on top to scroll with the rest of content? Here’s how to achieve that:

- Subclass PagingView
- Add the header image, title, description _and_ menu to a container UIView that you position above the page view controller.
- When scrolling in the table view, adjust the the top constraints of the container view based on the content offset
