### ISSUE TITLE
“_” parameter problems in delegate methods

### ISSUE THREAD

**Issue by qcasxy** [rechsteiner/Parchment#464]
I found that you ignored almost all the PagingViewController parameters in the delegate methods, which made it impossible for me to determine which pagingView triggered the delegate method when multiple PagingViewController delegate were set to the same ViewController.
For example:
`func pagingViewController(_: Parchment.PagingViewController, viewControllerAt index: Int) -> UIViewController`
I want you to set a parameter name for the PagingViewController.
Like this:
`func pagingViewController(_ pagingView: Parchment.PagingViewController, viewControllerAt index: Int) -> UIViewController`

**Comment by rechsteiner** [comment]
Hi @qcasxy! You can just add the extra parameter name in your app and it will still conform to the data source

**Comment by qcasxy** [comment]
> Hi @qcasxy! You can just add the extra parameter name in your app and it will still conform to the data source

Yes, it works. Thank you for your reply!
