### ISSUE TITLE
Is there any way to change titles of page items ?

### ISSUE THREAD

**Issue by MiteshiOS** [rechsteiner/Parchment#467]
I integrated pagingview controller in navigationbar. I wants to change titles of my page after initial load.
Let's say on successful run there are two page => View 1, View 2
Now on button click i wants to change name of `View 2` to `View 3`.
Let me know if possible

**Comment by rechsteiner** [comment]
Hi @MiteshiOS! By default, Parchment uses the title of the view controllers so you can set any title that you like. If you want a different title from the view controller you need to setup your own data source like [here](https://github.com/rechsteiner/Parchment/blob/master/Documentation/data-source.md) 🙂

**Comment by rechsteiner** [comment]
Oh sorry, saw that you updated the comment. You can call `reloadMenu` if you need to update the titles of the menu. If you also need to change the view controllers you can call `reloadData`

**Comment by MiteshiOS** [comment]
Yes but i used storyboard. In storyboard i set titles.

       let disVC = kMainStoryBoard.instantiateViewController(withIdentifier: "DiscoverVC")
       let myFeedVC = kMainStoryBoard.instantiateViewController(withIdentifier: "MyFeedVC")
       pagingViewController = CustomPagingViewController(viewControllers: [
            disVC,
            myFeedVC,
           
        ])

So how can i change titles ?

**Comment by rechsteiner** [comment]
Changing the title property on the view controllers and call reloadMenu should work 🙂

**Comment by MiteshiOS** [comment]
Okay thank you for the information. 
Also can you please let me know how can i use this datasource method along with storyboard.

    func pagingViewController(_: PagingViewController, viewControllerAt index: Int) -> UIViewController {
        return CityViewController(city: cities[index])
    }

Here how should i return my controller as my XIB is in storyboard ?

**Comment by rechsteiner** [comment]
You can initialise them the same way that you did before, you just need to initialise them based on the given index:

```Swift
func pagingViewController(_: PagingViewController, viewControllerAt index: Int) -> UIViewController {
    switch index {
    case 0:
        return storyboard.instantiateViewController(withIdentifier: "FirstViewController")
    ...
    }
}
```

**Comment by rechsteiner** [comment]
Alternatively you put them all in an array when the view loads, and returns the view controller based on the index in the array.

**Comment by MiteshiOS** [comment]
@rechsteiner Thank you for the information and support.

**Comment by afrade** [comment]
Change your controllers title, then reloadMenu:

`pagingViewController.reloadMenu()`

It worked for me
