### ISSUE TITLE
issue in calendar

### ISSUE THREAD

**Issue by waelhameed2** [rechsteiner/Parchment#471]
hey I just have a problem when I use calendar so for example when I select 5-4-2020 date ContentViewController print 6-4-2020

**Comment by rechsteiner** [comment]
Hi @waelhameed2! Which version are you using? Seems to be working fine in the example project

**Comment by waelhameed2** [comment]
I used last version and I tray to copy example project file and check it and I faced the same problem , thank you for help

**Comment by waelhameed2** [comment]
and also selectedBackgroundColor not work in calendar EXP when I add this line nothing change 
pagingViewController.selectedBackgroundColor = .red

**Comment by rechsteiner** [comment]
Can you try running the Calendar example directly and see if the same problem is there? 

Regarding `selectedBackgroundColor`, that property is only applied when using the default `PagingTitleCell`. When using a custom cell you need to handle that specifically by reading from the `PagingOptions` you receive in `setPagingItem`.

**Comment by rechsteiner** [comment]
@waelhameed2 did you get a change to look more into this?
