### ISSUE TITLE
Changes for version 2

### ISSUE THREAD

**Issue by prsolucoes** [rechsteiner/Parchment#472]
Hi,

Im migrating to version 2.

Before version 2 i need use:
```
pagingViewController.menuItemSource = .class(type: NewsChannelPagingCell.self)
```

What i need use now?

**Comment by Antonyyy13** [comment]
Hey,

Have a look : https://github.com/rechsteiner/Parchment/releases/tag/v2.0.0

So yep, it seems correct :)

**Comment by rechsteiner** [comment]
Yep, that's correct 🙂
