### ISSUE TITLE
How do i use navigationController in the child viewController embedded in PagingViewController?

### ISSUE THREAD

**Issue by AndyWu050411** [rechsteiner/Parchment#473]
Hello,
I embedded the PagingViewController in a navigationController with storyboard.
I use the function viewControllerAt of PagingViewControllerDataSource to setup my viewControllers, but I can't use navigationController in my viewControllers.

How do i use navigationController in my viewControllers?

**Comment by rechsteiner** [comment]
Hi @AndyWu050411! Why can't you use navigation controllers? I don't why that should not work, although it seems a bit weird to have the navigation controller inside the page view controller. Usually, you would put it around the PagingViewController.

**Comment by AndyWu050411** [comment]
Thanks for your reply. I already have solved this issue by just setting a delegate for my own view controllers. Actually I want to use the navigation controller whose root controller is PagingViewController for my own view controllers. Not setup a navigation for each my view controller.

**Comment by derens99** [comment]
I actually am having this problem too. How did you solve it? I have child view controllers in my class, and want to push a view controller when an element is clicked. I'm having a hard time accessing my navigation controller in parent classes.

**Comment by AndyWu050411** [comment]
Hello @derens99 , I wrote a protocol for the paging view controller, and set a delegate for each child view controller. It looks like:
`
protocol ParentDelegate {
    func push(vc: UIViewController)
}
ParentVC: ParentDelegate {
    func push(vc: UIViewController) {
        navigationController?.pushViewController(vc, animated: true)
    }

    func pagingViewController(_: PagingViewController, viewControllerAt index: Int) -> UIViewController {
        switch index {
        case 0:
            let a = A()
            a.delegate = self
            return a
        }
    }
}
`
You can call `delegate?.push(destinationVC)` in your child view controller to push a new view controller.

**Comment by AndyWu050411** [comment]
Hello @derens99 , I wrote a protocol for the paging view controller, and set a delegate for each child view controller. It looks like:

```swift
protocol ParentDelegate {
    func push(vc: UIViewController)
}

ParentViewController: ParentDelegate {
    func push(vc: UIViewController) {
        navigationController?.pushViewController(vc, animated: true)
    }
    func pagingViewController(_: PagingViewController, viewControllerAt index: Int) -> UIViewController {
        switch index {
        case 0:
            let aChild = UIViewController()
            aChild.delegate = self
            return aChild 
        }
    }
}
```

You can call `delegate?.push(destinationViewController)` in your child view controller to push another view controller.
