### ISSUE TITLE
SearchView

### ISSUE THREAD

**Issue by shakhzodurinboev** [rechsteiner/Parchment#475]
I have one question. I have pagingViewController which root views are tableViewControllers. 
I want to add search bar to bottom of pagingviewcontroller not to tableview header 
and use in parent view

Has anybody added searchbar to PagingViewController

**Comment by rechsteiner** [comment]
Hi @shakhzodurinboev! You can create a custom `PagingView` subclass where you add the search bar. Check out the [Header example](https://github.com/rechsteiner/Parchment/blob/cc6b08b1747d0c75cb35fc907591a5e259bd0a32/Example/Examples/Header/HeaderViewController.swift) for instance. Does that work for you?
