### ISSUE TITLE
PagingTitleCell fixed label constraints

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [rechsteiner/Parchment#479]
Hi, 

Thank you for great repo. 

I'm using it and constraints below (_"H:|-20-[label]-20-|"_) is not suitable for my project. 

I can create pull request for this. Would you mind if I make this constraint parametric (like menuItemLabelSpacing)?

https://github.com/rechsteiner/Parchment/blob/f44eb430bb3688ed39ca6893c0e85d56610fc3df/Parchment/Classes/PagingTitleCell.swift#L45-L49

**Comment by rechsteiner** [comment]
Thanks for fixing this! Will release a new version soon

**Comment by alperkayabasi** [comment]
@rechsteiner Hello, we are using Parchment in our project and this fix is highly important for us. When are you planning to release a new release?

**Comment by rechsteiner** [comment]
Hi @alperkayabasi! I dont have any ETA at the moment, but if it’s very urgent you can just copy the PagingTitleCell implementation here and register it as a custom cell: https://github.com/rechsteiner/Parchment/blob/master/README.md#custom-cells
