### ISSUE TITLE
How can i use swiftUI do unsplashView

### ISSUE THREAD

**Issue by c941010623** [rechsteiner/Parchment#481]
I want use unsplashView
How can i do it in swiftUI ?

**Comment by rechsteiner** [comment]
Hi @c941010623! It's currently not possible to get the same behaviour as the Unsplash example with the built-in `PageView` wrapper. I'm looking in to adding support for registering custom cells when using SwiftUI and it will be part of the `3.0` release. The scrolling behaviour in the Unsplash where the images stretch while scrolling is also not possible with the built-in wrapper.

That said, you can build your own wrapper that supports all this. Just copy the code inside [PageView](https://github.com/rechsteiner/Parchment/blob/master/Parchment/Structs/PageView.swift) and modify it to match the Unsplash example.

**Comment by rechsteiner** [comment]
Here's an example of someone implementing the Calendar example using SwiftUI: https://gist.github.com/mnightingale/d5a214f8eae1ec4111d6b2008f5a69f9
