### ISSUE TITLE
reopen: UIScreenEdgePanGesture has no effect with Parchment

### ISSUE THREAD

**Issue by wwwdotfa** [rechsteiner/Parchment#484]
@rechsteiner I encountered a similar problem with @qiaqiaxian, u used horizontal scrollview to contain pages, so `scrollView.panGestureRecognizer.require(toFail: recognizer)` never failed. This seems to be a very common problem. I hook the problem temporarily using the following method:

```
extension UIScrollView: UIGestureRecognizerDelegate {
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer is UIPanGestureRecognizer {
            return true
        }
        return false
    }
}

extension EMPageViewController: UIGestureRecognizerDelegate {
    override open func viewDidLoad() {
        super.viewDidLoad()
        self.scrollView.delegate = self
        self.view.addSubview(self.scrollView)
        scrollView.panGestureRecognizer.delegate = scrollView
    }
}
```

I think it would be more elegant to use a custom view inherit ScrollView in EMPageViewController, because the delegate of panGestureRecognizer is only allowed to be scrollView self. 

Thanks.

_Originally posted by @wwwdotfa in https://github.com/rechsteiner/Parchment/issues/148#issuecomment-619977479_

**Comment by rechsteiner** [comment]
Thanks for the report! I'm working on completely new page view controller implementation for the `3.0` release and I'll consider making this change for that. I need to look a bit more into this first though. I'm a bit worried about moving the scroll view as it could break a lot of existing apps. 

Can you explain a bit more how to reproduce this issue? When I've been testing it's been working fine using the back-swipe gesture. Is this only a problem when setting you your own custom UIScreenEdgePanGesture?

**Comment by rechsteiner** [comment]
@wwwdotfa do you have any more details on this?
