### ISSUE TITLE
init with viewControllers don't work

### ISSUE THREAD

**Issue by KrzysztofGuz** [rechsteiner/Parchment#488]
` public convenience init(
    options: PagingOptions = PagingOptions(),
    viewControllers: [UIViewController]) {
    self.init(options: options)
    configureDataSource(for: viewControllers)
  }
`

its that function was remove from PagingViewController? if I get it from cocapod its not shown

**Comment by rechsteiner** [comment]
Hi @KrzysztofGuz! I just tested with a clean project using CocoaPods now and it seems to work just fine. Which version of Parchment are you using? Can you try to clean the cache from CocoaPods?
