### ISSUE TITLE
menuItemLabelSpacing was removed?

### ISSUE THREAD

**Issue by zhuangxq** [rechsteiner/Parchment#489]
I want to change the PagingTitleCell.label's leading and trailing constant, I found menuItemLabelSpacing in the document,  but menuItemLabelSpacing is not appear in the project. Version 2.3.0

**Comment by ibrahimyilmaz7** [comment]
It's not released yet. You can use master branch.

**Comment by rechsteiner** [comment]
Sorry for the delay. This is available in the `2.4.0` release now 🙂

**Comment by zhuangxq** [comment]
Thank you very much. this is a concise, powerful, nice design project.  thanks😁
