### ISSUE TITLE
SwiftUI NavigationView appear even if is hidden

### ISSUE THREAD

**Issue by louischeminant** [rechsteiner/Parchment#490]
When adding a NavigationView above PageView and hide the navigation bar, and you try a switch from one index to another but you stay in the same view, the navigation bar appear. If I replace in the code below by  `navigationBarTitle("")`, no text appear but you can still see that the view get an unexpected top padding.

What's happening (Video):

![Screen Recording 2020-05-29 at 9 10 49 AM](https://user-images.githubusercontent.com/16012869/83264179-b9ed0380-a18d-11ea-984d-8a3aea964b82.gif)

https://www.icloud.com/iclouddrive/0dU-HmGtmqcWfB9xSbSjnXghg#Screen_Recording_2020-05-29_at_9.10.49_AM

Source code:

```
struct ContentView: View {
    var body: some View {
        NavigationView {
            PageView(items: [
                PagingIndexItem(index: 0, title: "View 0"),
                PagingIndexItem(index: 1, title: "View 1"),
                PagingIndexItem(index: 2, title: "View 2"),
                PagingIndexItem(index: 3, title: "View 3")
            ]) { item in
                NavigationLink(destination: Text("Detail"), label: {
                    Text(item.title)
                    .font(.largeTitle)
                    .foregroundColor(.gray)
                })
            }
            .navigationBarTitle("Test")
            .navigationBarHidden(true)
        }
    }
}

**Comment by rechsteiner** [comment]
That's very strange! Given the state of SwiftUI I wouldn't be surprised of this is just a bug there. I'll look a bit more into it, but I'm quite busy with the 3.0 release at the moment so it might take some time before I can prioritize this. If you figure out what might be causing this please let me know.

**Comment by rechsteiner** [comment]
@louischeminant did you figure out any solution to this? Have you tried with the latest Xcode beta?

**Comment by louischeminant** [comment]
I haven't had time to work on it these last few weeks, but I notice that the bug is still persistent on Xcode 12.

**Comment by louischeminant** [comment]
![Untitled2](https://user-images.githubusercontent.com/16012869/86539648-45179280-becc-11ea-828c-17d5e02f4b5e.gif)
Now the navigation title seems to appear right after you return to the front page.

**Comment by piaozhx** [comment]
I found a simple solution for this problem:

add 
```
pagingViewController.navigationController?.setNavigationBarHidden(true, animated: false)
```
in `func makeUIViewController` and `func updateUIViewController` of `PageView`

By the way, SwiftUI has many strange results of `NavigationBarHidden`, I also think it is bug.
