### ISSUE TITLE
Menu scrolling broken 2.4.0

### ISSUE THREAD

**Issue by simonzwicker** [rechsteiner/Parchment#493]
Hey Guys, since I update from 2.3.0 to 2.4.0 the Scrolling of the Parchment Menu is not working anymore. Is there something what I should to or is this a bug in this version?

**Comment by rechsteiner** [comment]
That sounds like a bug. I'll look into getting that fixes as soon as possible 🙂

**Comment by rechsteiner** [comment]
Hmm, I'm not able to reproduce this. Can you share a bit more about your setup and if you have any ways to reproduce the issue?

**Comment by rechsteiner** [comment]
@simonzwicker any updates on this?

**Comment by simonzwicker** [comment]
Hey, will check it today again.

**Comment by simonzwicker** [comment]
So i checked again and scrolling not working here some details:

Properties:
`fileprivate let assets = [
	  "A",
	  "B",
	  "C",
	  "D",
	  "E",
	  "F",
	  "G",
	  "H",
	  "I",
	  "J",
	  "K",
	  "L",
	  "M"
	]

	var pagingViewController = PagingViewController()
	var pagingViewControllerSelectedIndex = 0

	public var controllers = [Int: UIViewController]()`

In ViewDidLoad:
`pagingViewController.dataSource = self
		pagingViewController.sizeDelegate = self
		pagingViewController.delegate = self
		pagingViewController.backgroundColor = UIColor(named: "finNavBar") ?? .blue
		pagingViewController.textColor = UIColor(named: "finMenuInactive") ?? .blue
		pagingViewController.borderColor = UIColor(named: "finGray") ?? .lightGray
		pagingViewController.indicatorColor = UIColor(named: "finRed") ?? .red
		pagingViewController.selectedTextColor = .white
		pagingViewController.menuBackgroundColor = UIColor(named: "finNavBar") ?? .blue
		pagingViewController.selectedBackgroundColor = UIColor(named: "finNavBar") ?? .blue
		pagingViewController.menuInteraction = .none

		// Add the paging view controller as a child view controller and
		// contrain it to all edges.
		addChild(pagingViewController)
		view.addSubview(pagingViewController.view)
		pagingViewController.view.snp.makeConstraints { (make) in

			make.edges.equalToSuperview()
		}
		pagingViewController.didMove(toParent: self)`

And then implementing the DataSource, Size, Delegate is implemented like it should

works on 2.3.0 but not on 2.4.0

**Comment by rechsteiner** [comment]
Hi @simonzwicker! I finally got a new version of Parchment out now: https://github.com/rechsteiner/Parchment/releases/tag/v3.0.0. Could you check if this is still a problem?
