### ISSUE TITLE
Crash on EMPageViewController.scrollViewDidScroll(_:) line 631

### ISSUE THREAD

**Issue by ankit0812** [rechsteiner/Parchment#494]
Crashed: com.apple.main-thread
EXC_BREAKPOINT 0x000000010332c848
EMPageViewController.scrollViewDidScroll(_:)

![Screenshot 2020-06-03 at 3 23 31 PM](https://user-images.githubusercontent.com/21132111/83622902-3a589d80-a5ae-11ea-92fc-29d3c7af9477.png)

EMPageViewController.swift - Line 631
EMPageViewController.scrollViewDidScroll(_:) + 631

My Scenario is that I am using PagingViewController<PagingIndexItem>() in a ViewController which is embedded in a UIContainerView. My ViewController is on fixed Landscape mode. First of all in the beginning only 1 out of two items shows up. Upon swiping right the second item shows up or the application crashes to the above mentioned lines.

**Comment by rechsteiner** [comment]
Thanks for the report! I've been working on a new version that doesn't use EMPageViewController. Can you try targeting the `3.0` and see if the crash also happens there?

**Comment by ankit0812** [comment]
I will try to update the dependency in the coming release and let you know. For the time being any workaround ?

**Comment by rechsteiner** [comment]
I haven't seen this crash before, so I don't have any workaround at the moment. Will need to look into it and get back to you on that

**Comment by ankit0812** [comment]
Cool.

**Comment by rechsteiner** [comment]
Version 3.0 is now available as a pre-release: https://github.com/rechsteiner/Parchment/releases/tag/v3.0.0-beta. It should be stable enough to use, but please let me know if you find any issues.

**Comment by sgmtal** [comment]
I have tried this new version with iOS 14 and I get 2 errors ... any ideas? I think it would be solved by adding import UIKit..

<img width="1051" alt="Captura de pantalla 2020-09-27 a las 18 27 51" src="https://user-images.githubusercontent.com/20724496/94370480-92cd2100-00f0-11eb-9e09-901e740ad2f9.png">
<img width="1060" alt="Captura de pantalla 2020-09-27 a las 18 28 01" src="https://user-images.githubusercontent.com/20724496/94370483-9660a800-00f0-11eb-9a9d-020191d2cd79.png">
