### ISSUE TITLE
Different gesture recognizer for first page

### ISSUE THREAD

**Issue by Wistas23** [rechsteiner/Parchment#495]
Can I create and use UIScreenEdgePanGestureRecognizer to change scroll behaviour only on first page?
I need to interact with chart on that page, so scroll to second page needed to recongnised only from the edge of screen.

**Comment by rechsteiner** [comment]
Hi @Wistas23! That should be possible. The UIScrollView for the content view controllers is available on the `pageViewController.scrollView` property. You can use that to override the behaviour with your own gesture recogniser
