### ISSUE TITLE
Collectionview Background Color

### ISSUE THREAD

**Issue by coobing17** [rechsteiner/Parchment#497]
i have change collecltionview background color to black, but it still white. What should i do? 

<img width="548" alt="Screen Shot 2020-06-09 at 12 10 43" src="https://user-images.githubusercontent.com/22907007/84108748-251abd80-aa4b-11ea-91f4-32ee729b3cb7.png">

**Comment by coobing17** [comment]
this happens if i use menuItemSize = .selfSizing

**Comment by chaserunner** [comment]
Did you change `menuBackgroundColor` to black as well?

**Comment by coobing17** [comment]
Thanks @chaserunner , its work.
