### ISSUE TITLE
Could I to add some viewController dynamically?

### ISSUE THREAD

**Issue by kfoau9h39** [rechsteiner/Parchment#499]
Hey!
I would like appending controllers(pages) on receive message from backend.
I found fixed initialiser for it.

How I can to add it?

**Comment by rechsteiner** [comment]
Hey @kfoau9h39! You need to setup your own data source to dynamically add pages. See [Using the data source](https://github.com/rechsteiner/Parchment/blob/master/Documentation/data-source.md). Once you receive your message from the backend you can call `reloadData` and the new view controller will be added.
