### ISSUE TITLE
Self-sizing and infiniteDataSource

### ISSUE THREAD

**Issue by ageevvalentin** [rechsteiner/Parchment#503]
I am trying to use the new self-sizing api, but it does not work with the infinity data source, cell width always 0. Is it bug or by design?

**Comment by rechsteiner** [comment]
Hi @ageevvalentin! I just tried using self-sizing with the infinite data source and it seems to be working fine. Are you sure you have setup the correct constraints on you cell?

**Comment by ageevvalentin** [comment]
I will check it when I have a little more time.

**Comment by pratikgajbhiye222** [comment]
@ageevvalentin do you achieve that
