### ISSUE TITLE
How do I access viewControllers now? 

### ISSUE THREAD

**Issue by garciaish** [rechsteiner/Parchment#505]
The last version we've used is 1.6.0, and at that time we can do pagingViewController.viewControllers to get the view controllers' reference. 

We updated to 2.4.0, conformed to the changes (FixedPagingViewController being obsoleted, generics removed), but now pagingViewController.childen return only a single EMPagingViewController, and I can't use pagingViewController.viewControllers. How do I access the viewControllers now?

**Comment by MikeDonahue** [comment]
I'm also seeing this issue updating an old inherited project. I'm digging through versions and releases/tags and am not finding anything

**Comment by rechsteiner** [comment]
Hey! That's true, the viewControllers property is no longer available. But since you're already passing the view controllers into Parchment you already have a reference to them. Any reason you need to read it from PagingViewController?
