### ISSUE TITLE
[Header above menu] When HeaderView uses UIView instead of UIImageVIew can not scroll

### ISSUE THREAD

**Issue by LuckyRoc** [rechsteiner/Parchment#506]
![image](https://user-images.githubusercontent.com/10631829/86535842-c1829380-bf15-11ea-912e-3e693e7ec830.png)

**Comment by rechsteiner** [comment]
Hey @LuckyRoc! I'm not sure I understand exactly the issue your facing. You can't scroll in the table view or in the menu? This isn't really something specific to Parchment. Could it be that the header view you've added covers the scroll views?

**Comment by yermukhanbet** [comment]
I am trying to implement something similar. In my case, I used Parchment as a subview in UIViewController, and put it in the middle of the view. On top of it, I put UIView, with images and labels inside of it. So my point was to make it scrollable together with UITableViews(which are inside of the parchment). I have tried using your example header, but the result was the same with my current situation. Is there any way to do it? I really love this library, so do not want to change it. I can send you my code if you want to as well.
![Screen Shot 2020-08-26 at 5 22 39 PM](https://user-images.githubusercontent.com/46320390/91279907-0e217700-e7c1-11ea-8426-a0249128778d.png)

**Comment by rechsteiner** [comment]
@yermukhanbet this sounds like an issues specific to your app and not really related to the original issue. I would take another look at the example targets and see how it differs from your own implementation. If you think that it's an issue with Parchment itself, please open a new issue with more details 🙂
