### ISSUE TITLE
Crash in color transition when I use UIColor(patternImage:)

### ISSUE THREAD

**Issue by Scyano** [rechsteiner/Parchment#507]
I set my item.backgroundColor with API  UIColor(patternImage:), and when I scroll items, the color transition will invoke  function:

```
// UIColor+interpolation.wift
func components() -> (CGFloat, CGFloat, CGFloat, CGFloat) {
    guard let c = cgColor.components else { return (0, 0, 0, 1) }
    if (cgColor.numberOfComponents == 2) {
      return (c[0], c[0], c[0], c[1])
    } else {
      return (c[0], c[1], c[2], c[3])
    }
  }
```

and I find out that UIColor made with UIColor(patternImage:) only contains one CGColor component,  and cause crash.

```
let color = UIColor(patternImage: UIImage(named: "some")!)
let components = color.cgColor.components
// components.count is 1
```

**Comment by rechsteiner** [comment]
Thanks for reporting! I'll look into getting this fixed soon

**Comment by rechsteiner** [comment]
Hi @Scyano! I started looking into this, but I'm not really sure how to handle it. You could initialize a color using any type of image, so I don't really know the color here. I'm thinking of defaulting to black in this case, just so we prevent it from crashing at least. What do you think?

**Comment by Scyano** [comment]
It's fine! When someone use patternImage, he do not need color transition actually
