### ISSUE TITLE
Using menu as standalone view.

### ISSUE THREAD

**Issue by davidhsu1115** [rechsteiner/Parchment#508]
Hey, I've been trying to use the menu in a view controller. 
I believe this feature was added in Version 2.0, however I am struggling with finding any guideline using it.
Is there any example for us to implement this feature?

Thx.

**Comment by rechsteiner** [comment]
Hey @davidhsu1115! There's not really any good documentation for this at the moment. I can try to write up something pretty soon, but in the meantime I suggest looking at the `PagingViewController` implementation. It uses the `PagingMenu` internally.
