### ISSUE TITLE
如果能支持 自定义swith就好了

### ISSUE THREAD

**Issue by LZRight123** [rechsteiner/Parchment#510]
如果能支持 自定义swith就好了

**Comment by rechsteiner** [comment]
Hey @LZRight123! Could you explain in English what the issue is? I tried translating it, but I don't really understand

**Comment by Flybor** [comment]
maybe you can use the protocol of PagingViewControllerSizeDelegate

**Comment by rechsteiner** [comment]
@LZRight123 closing this for now, but let me know if you're still having some issues
