### ISSUE TITLE
Use of unresolved identifier 'FixedPagingViewController'

### ISSUE THREAD

**Issue by Sofia92f** [rechsteiner/Parchment#511]
Hi to all!
I have to work on a project developed by others. 

The project use Parchment.
But after updated and installed pods, it isn't build anymore.

In particular it's showing this message
`Use of unresolved identifier 'FixedPagingViewController'`

How I can fix it?

On the podfile there isn't any specific version, only` pod 'Parchment'`.

Thank you all!

**Comment by rechsteiner** [comment]
Hey @Sofia92f! `FixedPagingViewController` was renamed to just `PagingViewController` in v2.0.0: https://github.com/rechsteiner/Parchment/releases/tag/v2.0.0
