### ISSUE TITLE
Is it possible to hide separator between menu and view?

### ISSUE THREAD

**Issue by lygon55555** [rechsteiner/Parchment#516]
Hi, thank you for amazing library!
I really appreciate it 😀
But I' like to know whether it's possible to hide separator between menu and view.

**Comment by rishabhntl17** [comment]
Try this:
parchmentView?.borderOptions = PagingBorderOptions.hidden

**Comment by lygon55555** [comment]
@rishabhntl17 Thank you so much!
It worked!
