### ISSUE TITLE
Is there a way to avoid delay call on setPagingItem, when tapping on a tab?

### ISSUE THREAD

**Issue by yccheok** [rechsteiner/Parchment#517]
Thank you for creating such a useful and high quality scrollable tab library.

I notice that, when I tap on a tap, it will delay some time, till multiple calls on `setPagingItem` being triggered.

I wish to avoid the delay, as I would like the highlight background & foreground on selected tab, to happen immediately.

First, I though bottom indicator animation, is the reason of why such delay is required.

I tried to turn off bottom indicator by

    let pagingViewController = PagingViewController()
    ...
    pagingViewController.indicatorOptions = .hidden

Still, `setPagingItem` doesn't happen immediately, when I tap on a tab.

Is there any way, for `setPagingItem` to run immediately when I tap on a tab? Or, is there any way, for me to change the selected tab background & foreground immediately, when I tap on it?

Note, I do not modify the properties of `selectedTextColor` and `selectedBackgroundColor` in `PagingViewController`. Reason is that, every tab will have their very own selected text color and selected background color.

Hence, my changes are made based on `PagingTitleCell` comes with the example

```
open class PagingTitleCell: PagingCell {
  ...
  
  open override func setPagingItem(_ pagingItem: PagingItem, selected: Bool, options: PagingOptions) {
    print("setPagingItem called")
    
    if let titleItem = pagingItem as? PagingIndexItem {
      viewModel = PagingTitleCellViewModel(
        title: titleItem.title,
        selected: selected,
        options: options)
    }
       
    if selected {
        // TODO: selected color will come from pagingItem.
        contentView.backgroundColor = UIColor.red
    } else {
        contentView.backgroundColor = UIColor.green
    }
    
    configureTitleLabel()
    configureAccessibility()
  }
   
```
     
Thanks.

**Comment by rechsteiner** [comment]
Hi @yccheok! Sorry for the late response. I'm not sure it's possible to make this change to Parchment without substantially changing the internal implementation. One option is to override `apply(layoutAttibutes:)` and gradually fade in the selected color while the menu is scrolling. E.g:

```Swift
override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
    super.apply(layoutAttributes)
    if let attributes = layoutAttributes as? PagingCellLayoutAttributes {
        contentView.backgroundColor = UIColor.interpolate(
            from: .green,
            to: .red,
            with: attributes.progress)
    }
  }
```

It's also possible to immediately update the selected cell by implementing the `PagingViewControllerDelegate`:

```Swift
extension ViewController: PagingViewControllerDelegate {
    func pagingViewController(_ pagingViewController: PagingViewController, didSelectItem pagingItem: PagingItem) {
        // Reset all the visible cells
        for cell in pagingViewController.collectionView.visibleCells {
            cell.contentView.backgroundColor = .green
        }
        // Set the background color for the upcoming cell
        if let indexPath = pagingViewController.visibleItems.indexPath(for: pagingItem),
            let cell = pagingViewController.collectionView.cellForItem(at: indexPath) {
            cell.contentView.backgroundColor = .red
        }
    }
}
```

You can get the selected color from the PagingItem like you mentioned in your example as well.
