### ISSUE TITLE
Error when register cell with Nib

### ISSUE THREAD

**Issue by htnha** [rechsteiner/Parchment#521]
Hi,

I got this error: 
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<NSObject 0x280a2fc00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key canvasView.'

My code:
```swift
        let pagingViewController = PagingViewController()
        pagingViewController.register(UINib(nibName: "LetterPagingCell", bundle: nil), for: LetterItem.self)
        pagingViewController.menuItemSize = .fixed(width: 50, height: 50)
        pagingViewController.dataSource = self
        pagingViewController.contentInteraction = .none
```

class with xib:
```swift
class LetterPagingCell: PagingCell {
  @IBOutlet weak var canvasView: CanvasView!
...
}
```

class LetterItem:
```swift
struct LetterItem: PagingItem, Hashable, Comparable {
  let letter: String
  let index: Int
  
    init(letter: String, index: Int) {
    self.letter = letter
        self.index = index
  }
  
  static func < (lhs: LetterItem, rhs: LetterItem) -> Bool {
    return lhs.index < rhs.index
  }
}
```

**Comment by htnha** [comment]
Please help me!

**Comment by rechsteiner** [comment]
Hi @htnha! This looks like an issue with how you're outlets have been configured in you xib/storyboard. Check this for more details: https://stackoverflow.com/questions/3088059/xcode-how-to-fix-nsunknownkeyexception-reason-this-class-is-not-key-valu
