### ISSUE TITLE
protocol witness for PagingViewControllerDataSource.pagingViewController(_:viewControllerAt:) in conformance crash

### ISSUE THREAD

**Issue by AashimaAnand** [rechsteiner/Parchment#524]
closure #1 in PagingViewController.configureDataSource() + 534 (PagingViewController.swift:534)

Lines:
 dataSource.viewControllerForIndex = { [unowned self] in
      return self.dataSource?.pagingViewController(self, viewControllerAt: $0)
    }

**Comment by rechsteiner** [comment]
Hi @AashimaAnand! Do you have any way of reproducing this crash?
