### ISSUE TITLE
Disable a single item

### ISSUE THREAD

**Issue by marinofaggiana** [rechsteiner/Parchment#528]
It's possible disable a single index ? 

Thanks

**Comment by rechsteiner** [comment]
Hi @marinofaggiana! There's no build-in way of disabling an item. For the menu it should be possible to disable selections by overriding the `didSelectIndexPath` method on `PagingViewController`:

```swift
class CustomPagingViewController: PagingViewController {
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if indexPath.item == 2 {
            return
        }
        super.collectionView(collectionView, didSelectItemAt: indexPath)
    }
}
```

You can visually style the disabled menu item by making your own `PagingCell` subclass. But for the page view controller I'm not really sure how it should work. What should happen if you try to swipe the view controllers towards a disable item? One way of getting around this is to just disable the swiping altogether by setting `contentInteraction = .none`

**Comment by marinofaggiana** [comment]
good thank a lot

**Comment by marinofaggiana** [comment]
@rechsteiner only a little speed help for a custom PagingCell for change only the title colors.

thx
