### ISSUE TITLE
How to scroll weekly CalendarPagingCell when scroll ?

### ISSUE THREAD

**Issue by dobiho5** [rechsteiner/Parchment#529]
Thanks for sharing great code, first of all. 

I'd like to make daily calendar view using Calendar example. 

CalendarPagingCell of Calendar example behave like this. 

<Img src="https://camo.githubusercontent.com/8419a34bf656fa5fa2bcf2d4fbe2f15c2e06f419/68747470733a2f2f72656368737465696e65722d70617263686d656e742e73332e65752d63656e7472616c2d312e616d617a6f6e6177732e636f6d2f70617263686d656e742d63616c656e6461722e676966">

But I want to do these like any Calendar app's behaviors.  

1. I want to scroll week menu bar by weekly when scrolling it  

2.How to fix menu bar by weekly when left and right scrolling page. 

I have considered using Calendar library like fsCalendar, but I think Parchment's Calendar is simple and good to PageViewController. 

Thanks in advances

**Comment by olegtatarciuc** [comment]
Hi.
Don't forget, that each `date` in the calendar is a `UICollectionViewCell`. It is not possible to scroll multiple cells by 1 swipe. 
Maybe you can create your own version of the calendar using Parchment.
Let your MenuItem be the width of the screen, in that Item you would type 7 dates (representing a week), and when you would scroll, it would scroll weekly.

**Comment by hasankamrul** [comment]
> Thanks for sharing great code, first of all.
> 
> I'd like to make daily calendar view using Calendar example.
> 
> CalendarPagingCell of Calendar example behave like this.
> 
> ![](https://camo.githubusercontent.com/8419a34bf656fa5fa2bcf2d4fbe2f15c2e06f419/68747470733a2f2f72656368737465696e65722d70617263686d656e742e73332e65752d63656e7472616c2d312e616d617a6f6e6177732e636f6d2f70617263686d656e742d63616c656e6461722e676966)
> 
> But I want to do these like any Calendar app's behaviors.
> 
> 1. I want to scroll week menu bar by weekly when scrolling it
> 
> 2.How to fix menu bar by weekly when left and right scrolling page.
> 
> I have considered using Calendar library like fsCalendar, but I think Parchment's Calendar is simple and good to PageViewController.
> 
> Thanks in advances

just go to CalendarViewController.swift in example project and paste the bellow code 
func pagingViewController(_: PagingViewController, itemAfter pagingItem: PagingItem) -> PagingItem? {
        let calendarItem = pagingItem as! CalendarItem
        var futureMonth = Calendar.current.date(byAdding: .month, value: 1, to: calendarItem.date)!
        return CalendarItem(date: futureMonth)
    }

    func pagingViewController(_: PagingViewController, itemBefore pagingItem: PagingItem) -> PagingItem? {
        let calendarItem = pagingItem as! CalendarItem
        var previousMonth = Calendar.current.date(byAdding: .month, value: -1, to: calendarItem.date)!
        return CalendarItem(date: previousMonth)
    }

**Comment by rechsteiner** [comment]
@dobiho5 is the solution @hasankamrul mentioned what you're looking for? Or are you thinking of showing one day at the time, but only scrolling in the header when you move to the next week (e.g. the Calendar app on iOS)?
