### ISSUE TITLE
Swift 4 migration

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#53]
Hello Martin,

Any plans for swift 4.
Even though Swift 3.x and Swift 4 are interchangeable, it would be great if there were a Swift 4 version! 

Thank you! 😄

**Comment by rechsteiner** [comment]
Hey! Just merged an upgrade to Swift 4: #54 . Releasing a new version now ✌️

**Comment by IVANKRUPSKI** [comment]
Great! Thanks!

**Comment by rechsteiner** [comment]
New version should be out now 💫
