### ISSUE TITLE
Have a UISegmentedControl as the menu?

### ISSUE THREAD

**Issue by olegtatarciuc** [rechsteiner/Parchment#531]
I would like to have a UISegmentedControl as the menu.
How would I do that?
I have the idea of replacing the UICollectionView that is representing the menu now, and use the UISegmentedControl, but to be honest, not sure where to start. Or, maybe have the collectionView with only 1 cell with the width equal to the screen width, and add as a subview the UISegmentedControl, and selecting segments based on the scroll delegates from Parchment.
Any ideas would be very welcome.

**Comment by rechsteiner** [comment]
Hi @olegtatarciuc! I don't think you really need Parchment for this. It would probably be better to use `UIPageViewController` directly with a `UISegmentedControl` on top. If you need detailed delegate methods for the page view controller (which is really buggy with `UIPageViewController`), you could use only the `PageViewController` class in Parchment. Hope that helps!
