### ISSUE TITLE
Reusing view controller for dataSource

### ISSUE THREAD

**Issue by galblank** [rechsteiner/Parchment#535]
Trying to reuse class member viewController will fail to display properly and messes up pagination
```
class TestVC: UIViewController {
  let pagingVC = ProfileSectionsTableViewController()
}

extension TestVC: PagingViewControllerDataSource {
func pagingViewController(_ pagingViewController: PagingViewController, viewControllerAt index: Int) -> UIViewController {
        return pagingVC
 }
}
```

why do I need to instantiate new controller every time I change page ?
thank you

**Comment by rechsteiner** [comment]
Hi @galblank! It's not possible to display two instances of the same view controller in UIKit, so when you swipe to the next screen it needs to be a different instance. This is the exact same behaviour as `UIPageViewController` etc. If you want to display the exact same view controller, you either need to initialize it in the data source method or create a new instance by running `.copy()` on it.

**Comment by galblank** [comment]
I guess my issue is that it should refresh it , rather than keep trying to add it to the stack. @rechsteiner 
I guess this isn't what I'm looking for, for my needs. I just need a paging menu that I can hookup to and do X when a menu item is being tapped. 
By X I mean refreshing an existing ViewController rather than keep adding it to the stackView.
I assumed that since there is an initialization function that takes a list of ViewController, those controller are being reused here.

**Comment by rechsteiner** [comment]
Ah, I see. Yeah, then you don't really need the page view controller part. You could use the menu as a standalone view using the `PagingMenu` class. When selecting the items you could then just update your view controller.
