### ISSUE TITLE
PagingViewController shows last page after init and select(at: index) doesn't work.

### ISSUE THREAD

**Issue by alperkayabasi** [rechsteiner/Parchment#540]
I'm using this code for nearly one year and it was working fine.
After version 3.0.0 released, my code isn't working anymore, something is broken.
I create my `PagingViewController` with the code below. It only shows `secondViewController` on screen.
I tried selecting first item or first index manually after init but it didn't work. I tried calling `select` after a minor delay, that didn't work either.
Only manually tapping the first `menuItem` changes selection.

`self.pagingViewController = PagingViewController(viewControllers: [
          firstViewController,
          secondViewController
        ])`

        `guard let pagingVC = self.pagingViewController else { return }
        setParchmentUI(pagingVC)
        addChild(pagingVC)
        viewParchment.addSubview(pagingVC.view)
        pagingViewController?.didMove(toParent: self)
        pagingViewController?.view.translatesAutoresizingMaskIntoConstraints = false
        setParchmentConstraints(pagingVC)`

**Comment by shaj04** [comment]
I've met the same problem, the reason may be in the following codes

```
// PagingViewController.swift 
  func layoutViews(for viewControllers: [UIViewController], keepContentOffset: Bool) {
    let viewControllers = isRightToLeft ? viewControllers.reversed() : viewControllers

    // add this line could fix the problem 
    // scrollView.frame = view.bounds 
    
    for (index, viewController) in viewControllers.enumerated() {
      switch options.contentNavigationOrientation {
      case .horizontal:
```

I guess because  `view.constrainToEdges(scrollView)`  in `ViewDidLoad` doesn't make sense at such cases

**Comment by mnfro** [comment]
Same issue here! after updating to 3.0.0, `PagingViewController` shows always the last page as first, `select(index:0)` has no effect and a physical tapping on the `menu item` is required to go back to the first page.

**Comment by Hastingou** [comment]
I got some similar bug in version 3.0.0.
When my viewControllers datasource changed, I need rebuild a new PagingViewController, but the page of new PagingViewController doesn't show the first page. 
Found a solution. After PagingViewController rebuild, firstly use reloadData func.

>     func refreshWith(tagList: [HotpointModel]) {
        if pagingViewController != nil {
            pagingViewController.willMove(toParent: nil)
            pagingViewController.view.removeFromSuperview()
            pagingViewController.removeFromParent()
            pagingViewController = nil
        }
        subVCs = tagList.map({NewTimeFallViewController(tagName: $0.tname)})
        pagingViewController = PagingViewController(viewControllers: subVCs)
        addChild(pagingViewController)
        view.addSubview(pagingViewController.view)
        pagingViewController.didMove(toParent: self)
        pagingViewController.view.translatesAutoresizingMaskIntoConstraints = false
        pagingViewController.reloadData()
    }

**Comment by rechsteiner** [comment]
Thanks for reporting! I'm looking into this right now, but I'm struggling to reproduce it. Is there anything you could think of that is different from the example targets in your setup?

**Comment by Hastingou** [comment]
> Thanks for reporting! I'm looking into this right now, but I'm struggling to reproduce it. Is there anything you could think of that is different from the example targets in your setup?

I make a simple demo to show the bug. 
[https://github.com/Hastingou/ParchmentTest](url)

**Comment by rechsteiner** [comment]
Thanks 🙌 I'll get that fixed soon

**Comment by rechsteiner** [comment]
A new version is out now (v3.0.1) which should fix these issues. Please let me know if you are still seeing any issues
