### ISSUE TITLE
Autolayout go wrong on 3.0.0

### ISSUE THREAD

**Issue by toptomsk** [rechsteiner/Parchment#541]
On childViewController i add a subview constraint with bottomlayoutGuide, and when first time I push to pagingVC it's seem that subview frame go wrong, it below the egde of screen, but when i scroll to other page then back, everything back to normal. Or at viewdidAppear of pagingVC i call pagingViewController.reloadData() its flash to apprear at right position
It's only happened on version 3.0.0, i try go back to 2.4.0 everything working great.

**Comment by RomanTysiachnik** [comment]
I confirm that I've also faced some weird behavior on the 3.0.0.

The flow looked like this:
- Pushed a screen that has a paging view controller as a child and his top constraint aligned to the top with 250.0 offset
- After some action, I switch 250.0 offset to 0 

Expected: paging screen aligns to the top safe area and fills the entire screen
Achieved: paging screen aligns to the top safe area but the bottom of the screen is cut off at 250.0pt.

**Comment by rechsteiner** [comment]
Thanks for reporting! This should be fixed now in v3.0.1. Let me know if you are still seeing any issue

**Comment by RomanTysiachnik** [comment]
In my case, the issue is not fixed in 3.0.1 =\

**Comment by RomanTysiachnik** [comment]
@rechsteiner any progress on that?

**Comment by rechsteiner** [comment]
Hmm, need to look a bit more into this

**Comment by rechsteiner** [comment]
@RomanTysiachnik could you share some details on your implementation? Are you able to reproduce this in one of the examples? I'm not able to reproduce it myself

**Comment by firetrap** [comment]
Still happening in 3.1.0

**Comment by rechsteiner** [comment]
This should be fixed now #623
