### ISSUE TITLE
Swipe to delete on a tableView that is inside a PagingViewController

### ISSUE THREAD

**Issue by estebanmons** [rechsteiner/Parchment#542]
When I slide the delete action into a TableView cell it doesn't work. Switch to the other ViewController in Paging:

func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
        
        let deleteAction = UIContextualAction(style: .destructive, title: nil) { (_, _, _) in
              //Action
        }

        deleteAction.image = #imageLiteral(resourceName: "ic_trash_clear")
        deleteAction.backgroundColor = .red
        let configuration = UISwipeActionsConfiguration(actions: [deleteAction])
        configuration.performsFirstActionWithFullSwipe = true
        return configuration
    }

Please some help!

**Comment by rechsteiner** [comment]
Hey @estebanmons! Do you want to support both swipe actions and swiping between pages? From a UX perspective it sounds a bit like you should disable the page swiping using `contentInteraction = .none`. If you really want to support both swiping gestures at the same time you need to cancel the gesture recognizer for the `pageViewController.scrollView` when starting to the table view swipe. Take look at the documentation here on how to cancel gesture recognizers: https://developer.apple.com/documentation/uikit/uigesturerecognizer/1624203-requiregesturerecognizertofail
