### ISSUE TITLE
Hi, What should I do if I want to hide the menu when there is only one element in pagingvc ?

### ISSUE THREAD

**Issue by DanielYK** [rechsteiner/Parchment#546]
I tried to hide the menu dynamically, but the layout is wrong when I switch back and forth

**Comment by rechsteiner** [comment]
Hi @DanielYK! How are you hiding the menu? It should be possible to hide it by setting the height to zero for the `menuItemSize` property. See this discussion for more details: https://github.com/rechsteiner/Parchment/issues/378
