### ISSUE TITLE
Scroll View on child views

### ISSUE THREAD

**Issue by CharlemagneVI** [rechsteiner/Parchment#553]
![image](https://user-images.githubusercontent.com/7468260/107879350-51be8900-6ea6-11eb-93e0-f4f53a160780.png)

Is it possible to add UIScrollViews to view controllers within a PagingViewController? It appears that the paging scroll view takes interaction priority over the child scroll views. I'm looking to add a scroll view that allows for vertical scrolling for the view in the above screenshot.

Is there any recommendation on how this should be implemented that I might have missed that doesn't involve using a Table/Collection View?

**Comment by rechsteiner** [comment]
Hi @CharlemagneVI! That should definitely be possible. Both the Header and LargeTitle examples have vertical scrolling in the  content view controllers, so you can take a look at them for implementation details. The concept should be the same of a plain UIScrollView
