### ISSUE TITLE
Detail Page error

### ISSUE THREAD

**Issue by GuriSarao** [rechsteiner/Parchment#554]
I am using contentViewController in which i am showing a list from array. but when I am click on any index to get its detail(newViewController) it showing me wrong data as there is always next contentViewController loaded when I swipe to change viewController. How can I get the data only for visible contentViewController? so when i click on a list to show its detail in will get a exact index of list array.

**Comment by rechsteiner** [comment]
Hi @GuriSarao! You can get the data for a given view controller by using the delegate: https://github.com/rechsteiner/Parchment#delegate. If you need the currently selected view controller, you can also access it on `pagingViewController.pageViewController. selectedViewController `
