### ISSUE TITLE
Example codes Error

### ISSUE THREAD

**Issue by Odyflame** [rechsteiner/Parchment#555]
there's some error in Example -> Header -> HeaderView.

i don't analyze deeply, but i build example app and run, app runs well except headerview.

when i click header above menu, the view is show. after then, i touch any cells, the above photo is dismissed suddenly. just one time, others is fine.

i move back to first Examples tableview, and touch Header above menu, touch any cell. the issue that suddenly above photo is dismissed is still exsited,

please fix it for me! thanks.

**Comment by rechsteiner** [comment]
> please fix it for me!

This is just an example of what you can do with Parchment, and not part of the actual library. I will look into improving the examples, but you have to implement your own app yourself

**Comment by chinghoi** [comment]
实际上我认为属于库的一部分, 因为我运行了 Demo 在不同的设备上.
其中 Header abaove menu 在系统版本为 12.5.5 的 iPhone 6 上为预期显示正确,
然而在系统版本为 15.2 的 iPhone X 上, 显示的第一个 tableviewCell 被 menu 遮挡, headerView 没有显示出来, 滑动的时候才会正常.
![IMG_D11AEC3B0003-1](https://user-images.githubusercontent.com/20352401/154017689-07d56f45-f918-4ebf-a782-bfaabf4c90ba.jpeg)

所以我觉得是一个需要适配的地方
