### ISSUE TITLE
In root view controller on infinity mode, when present a landscape view controller then dismiss, the infinity tab bar is shown the wrong tab.

### ISSUE THREAD

**Issue by tridorje** [rechsteiner/Parchment#556]

**Comment by tridorje** [comment]
In root view controller on infinity mode, when present a landscape view controller then dismiss, the infinity tab bar is shown the wrong tab.
I have the error video capture
Please help me.

**Comment by rechsteiner** [comment]
Hi @tridorje! It's a bit hard say what the issue is based on just the video. Could you share some details on your implementation?
