### ISSUE TITLE
SPM Warning

### ISSUE THREAD

**Issue by marinofaggiana** [rechsteiner/Parchment#557]
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.

**Comment by rechsteiner** [comment]
Hi @marinofaggiana! Where do you see the "supported deployment target versions"? From what I can see both IPHONEOS_DEPLOYMENT_TARGET and Package.swift is set to 8.2

**Comment by rechsteiner** [comment]
Looks like Xcode 12 doesn't support building for iOS 8 anymore. I guess we need to drop iOS 8 support then 😅

**Comment by rechsteiner** [comment]
Dropped #568. Will release a new version soon!
