### ISSUE TITLE
is there any way to make menu corner radius without custom cell?

### ISSUE THREAD

**Issue by yildirimatcioglu** [rechsteiner/Parchment#560]
Hello,
I just want to make menu view itself(not menu items) with corner radius without custom cells. Here is the sample design:
<img width="226" alt="Screen Shot 2021-03-11 at 23 35 10" src="https://user-images.githubusercontent.com/17345325/110851709-71d54280-82c2-11eb-8912-2ec23233cca6.png">

**Comment by rechsteiner** [comment]
Hi @yildirimatcioglu! There's no way to do this without a custom cell, but it really shouldn't be that many lines of code. The easiest way is probably to subclass `PagingCell` and apply the corner radius in `setPagingItem` based on the index.

I'm not that keen on adding this directly to Parchment, as I'm trying to keep it pretty generic. The library quickly gets messy if we add support for all kinds of custom designs.
