### ISSUE TITLE
Rotating resets the current index

### ISSUE THREAD

**Issue by machorro** [rechsteiner/Parchment#562]
Hi, I'm having an issue with rotation on 2 different cases

when I load the pages and select an index, then rotate, the `PagingViewController` goes back to the index 0

The 2nd issue here is if I push a new view controller and rotate, coming back triggers this weird bug (plus goes back to index 0 if index 1 was selected)
![Screen Shot 2021-03-16 at 3 55 56 PM](https://user-images.githubusercontent.com/6884643/111373551-64c5a400-8672-11eb-8c73-ff893b35c9e3.png)

I was able to replicate it using the `BasicViewController` from the example, hope this works 🙂 

thanks

```
class BasicViewController: UIViewController {
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let viewControllers = [
      ContentViewController(index: 0),
      ContentViewController(index: 1),
    ]
    
    let pagingViewController = PagingViewController(viewControllers: viewControllers)
    
    // Make sure you add the PagingViewController as a child view
    // controller and constrain it to the edges of the view.
    addChild(pagingViewController)
    view.addSubview(pagingViewController.view)
    view.constrainToEdges(pagingViewController.view)
    pagingViewController.didMove(toParent: self)

    pagingViewController.select(index: 1)

    navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(push))
  }

    @objc func push() {
        let vc = UIViewController()
        vc.view.backgroundColor = .red
        self.navigationController?.pushViewController(vc, animated: true)
    }
  
}
```

**Comment by rechsteiner** [comment]
Hi @machorro! This sounds like an issue that was fixed some time ago. Which version are you using?

**Comment by rechsteiner** [comment]
I tried running your example locally with version 3.0.1 and it seems to work fine

**Comment by rechsteiner** [comment]
Closing for now, but let me know if this is still an issue in the latest version
