### ISSUE TITLE
Unable to set frame with navigation Bar

### ISSUE THREAD

**Issue by PavanMaddineni** [rechsteiner/Parchment#565]
Hi,

Please resolve this issue. Unable to set frame. Menu bar hiding in Navigationbar

**Comment by rechsteiner** [comment]
Hi @PavanMaddineni. Check out the NavigationBar example for how to do this: https://github.com/rechsteiner/Parchment/blob/master/Example/Examples/NavigationBar/NavigationBarViewController.swift
