### ISSUE TITLE
How to get all controllers?

### ISSUE THREAD

**Issue by PavanMaddineni** [rechsteiner/Parchment#566]
I need to all controllers in any screen inside Page menu

**Comment by rechsteiner** [comment]
Hi @PavanMaddineni! Parchment only shows the view controllers that you tell it to show, so you should already have access to all the controllers. For instance, if you are using `init(viewControllers:)` initializer you have the view controllers there. If you are using `dataSource`, you either need initialize all your view controllers up-front or add them to a property when the view controller methods are being called. It depends a bit on your app 🙂
