### ISSUE TITLE
ImageViewController without tableview cells

### ISSUE THREAD

**Issue by yasuntimure** [rechsteiner/Parchment#570]
Hi , I'm trying to make a menu collectionView with icons at the top and under that I need to scroll my viewControllers synchronously. I checked your "Images" folder. It's kind of same but its using the tableViews. Is there any way to make it  with viewControllers which's are designed in storyboard.

**Comment by rechsteiner** [comment]
Hi @yasuntimure! Yes, you can use storyboards by getting the view controllers and passing it into the `init(viewController:)` initialiser. Check out the Storyboard example here: https://github.com/rechsteiner/Parchment/blob/master/Example/Examples/Storyboard/StoryboardViewController.swift

**Comment by yasuntimure** [comment]
Yeah, I saw it but I couldn't combine them. My another question is how we are going to scroll to another viewcontroller programmatically. I mean when I clicked my button with an IBAction I would like scroll next page. I used delagates but it didn't work .

**Comment by rechsteiner** [comment]
Check out this one: https://github.com/rechsteiner/Parchment#selecting-items
