### ISSUE TITLE
Crash on observe contentOffset version 3.0.1

### ISSUE THREAD

**Issue by toptomsk** [rechsteiner/Parchment#577]
Recently firebase report a lot of crash on this version about observe UIScrollView contentOffset

> Fatal Exception: NSInternalInconsistencyException
> An instance 0x1037dea00 of class UICollectionView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x170c32d20> ( <NSKeyValueObservance 0x171244e00: Observer: 0x171244440, Key path: contentOffset, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170a4def0> )

PagingView.swift - Line 0
@objc PagingView.__ivar_destroyer

Can u guy fix it ?

**Comment by rechsteiner** [comment]
Hi @toptomsk. It's hard to say without being able to reproduce it. It's the first time I'm seeing this crash. Could there be something specific to your app? Are you doing some key-value observing?
