### ISSUE TITLE
No view controller exist for PagingItem: file Parchment/PagingFiniteDataSource.swift

### ISSUE THREAD

**Issue by sukrukahraman** [rechsteiner/Parchment#579]
In application sometimes throw crash in paging.reloadData(). But i cant take on this crash, i always see in crashlytics log.
No view controller exist for PagingItem: file Parchment/PagingFiniteDataSource.swift

How can i solve it?

**Comment by rechsteiner** [comment]
Hi @sukrukahraman! I haven't seen any crashes like this myself. Could you share a bit more details on your setup? Are you using the `init(viewControllers:)` initialiser or setting up your own data source?

**Comment by rechsteiner** [comment]
Closing this for now, but let me know if you have any more details and I can re-open it 🙂
