### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AdAvAn** [rechsteiner/Parchment#58]
**If you build  Parchment (r.0.5.0)  with the "leak checker" tool, you can see a memory leak, if I'm not mistaken, the method is:**

` override open func layoutAttributesForElements (in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {}`

![screenshot at sep 26 15-13-36](https://user-images.githubusercontent.com/13752342/30859662-4d044ce0-a2cd-11e7-925e-79b6469c88d8.png)

### I may be wrong, but I think the problem is to use self when initializing an array.

![screenshot at sep 26 15-21-03](https://user-images.githubusercontent.com/13752342/30860007-79a90e1a-a2ce-11e7-86b4-c23d16588a47.png)

### One solution would be to use unowned self as follows.

```
  lazy var layoutAttributesValues: [UICollectionViewLayoutAttributes] = { [unowned self] in
        return Array(self.layoutAttributes.values)
  }()
    
  override open func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {

    var layoutAttributes: [UICollectionViewLayoutAttributes] = layoutAttributesValues
    
    for attributes in layoutAttributes {
      if let pagingAttributes = attributes as? PagingCellLayoutAttributes {
        pagingAttributes.progress = progressForItem(at: attributes.indexPath)
      }
    }
    
    let indicatorAttributes = layoutAttributesForDecorationView(
      ofKind: PagingIndicatorView.reuseIdentifier,
      at: IndexPath(item: 0, section: 0))
    
    let borderAttributes = layoutAttributesForDecorationView(
      ofKind: PagingBorderView.reuseIdentifier,
      at: IndexPath(item: 1, section: 0))
    
    if let indicatorAttributes = indicatorAttributes {
      layoutAttributes.append(indicatorAttributes)
    }
    
    if let borderAttributes = borderAttributes {
      layoutAttributes.append(borderAttributes)
    }
    
    return layoutAttributes
  }
```

"I will be grateful to you ... if you correct this issue as soon as possible.
Thank you

**Comment by rechsteiner** [comment]
Hi! I don’t see how that would cause a memory leak. I’m struggling to produce a memory leak at all, but I will investigate a bit more 👍

**Comment by IVANKRUPSKI** [comment]
Hey Martin!

Have you found this bug?

**Comment by rechsteiner** [comment]
Hey! I still haven't been able to re-produce it. Are you seeing the same in your project?

@AdAvAn are you getting the same results every time you run the Leaks debugger, or do you have any other ways of re-reproducing it?

**Comment by AdAvAn** [comment]
To reproduce the leak, I use your sample code example. I download it from the link https://github.com/rechsteiner/Parchment/archive/v0.5.0.zip.
I make a choice of an example, then I press "Command + I", I select "Leaks".

<img width="434" alt="screenshot at oct 18 01-49-10" src="https://user-images.githubusercontent.com/13752342/31693484-8bff545e-b3a7-11e7-82f3-0a864dfcbf84.png">

<img width="596" alt="screenshot at oct 18 01-52-33" src="https://user-images.githubusercontent.com/13752342/31693489-924f8be4-b3a7-11e7-9b5c-f94b03195c7b.png">


<img width="327" alt="screenshot at oct 18 01-50-22" src="https://user-images.githubusercontent.com/13752342/31693497-9bcf3ab6-b3a7-11e7-87df-202c833b7124.png">


I do not perform any actions with simulators and already in the first seconds I get a leak. Leakage is observed at each start.

**Comment by rechsteiner** [comment]
I’ve been looking some more into this and I really can’t find the any memory leaks. Have you managed to get the same results when profiling against an actual device? The simulator doesn’t behave in the same way as real devices as they run on completely different hardware.

**Comment by AdAvAn** [comment]
OK, I will check on the real device.

**Comment by AdAvAn** [comment]
I did a test on a real device using iOS 11 and Parchment v0.7.0.
Yes, I do not see a memory leak, maybe the problem was in v.0.5.0.
This is no longer relevant.
Thank you!

**Comment by rechsteiner** [comment]
Awesome, thanks for checking!
