### ISSUE TITLE
How to implement pushViewController with Large Navigation Ttile

### ISSUE THREAD

**Issue by kou-yamamoto** [rechsteiner/Parchment#580]
- In example, present method is used for screen transition with  large navigation title.
- So, there are no ways to implement pushViewController with Large Navigation title?  if anyone knows, let me know.

**Comment by rechsteiner** [comment]
Yeah, it's possible but the view controller before also needs to have large navigation title. Check out this for more details: https://www.hackingwithswift.com/example-code/uikit/how-to-enable-large-titles-in-your-navigation-bar
