### ISSUE TITLE
Stacked Parchment

### ISSUE THREAD

**Issue by eren-celik** [rechsteiner/Parchment#582]
hi, I want to add nested in your package but the child view controller is not showing.
The situation I want to do is available in the screenshot below, 

![fca769cc-6ed4-4fea-8a08-3c62708605dd](https://user-images.githubusercontent.com/63004133/127325130-d3052055-dc88-4b85-8ac2-ad1afb1a6716.jpg)
Is such a situation possible?

**Comment by rechsteiner** [comment]
Yeah, that should be possible. What's the problem you're having?
