### ISSUE TITLE
SwiftUI image not found on older iOS versions.

### ISSUE THREAD

**Issue by tkirby** [rechsteiner/Parchment#583]
dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /var/containers/Bundle/Application/MyApp.app/MyApp
  Reason: image not found
  
  I worked around this by adding:
  
     -weak_framework SwiftUI
     
   to the Other Linter Flags in the Parchment build as suggested by Apple in the iOS 13 release notes:
   
   https://developer.apple.com/documentation/ios-ipados-release-notes/ios-13-release-notes

**Comment by Starsky89** [comment]
I am having the same crash when trying to run on a iPhone Xs simulator with iOS 12.0.
Found this thread explaining the same as @tkirby wrote above.
@rechsteiner can this fix be implemented in a future update please?

**Comment by rechsteiner** [comment]
Hi! Could you check if this is still a problem with the `v3.1.0` release?

**Comment by torburg** [comment]
But we don't commit Pods.xcodeproj, and then how can I save `-weak_framework SwiftUI` code changes?

**Comment by Starsky89** [comment]
@torburg 
Here is a nice post install code you put at the bottom of your Podfile, which will do this every time you run `pod install`.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Parchment'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_LDFLAGS'] = '-weak_framework SwiftUI'
      end
    end
  end
end
```

**Comment by rechsteiner** [comment]
This should be fixed in the master branch now thanks to @kambala-decapitator 🙌 Will release a new version soon
