### ISSUE TITLE
Paging header collection view is at the status bar

### ISSUE THREAD

**Issue by jvigneshcs** [rechsteiner/Parchment#585]
I just tried a sample application with this library. Link [here](https://github.com/jvigneshcs/DinDinnFoodDelivery)
I have created a view controller named ShoppingDashboardViewController.swift using SelfSizingViewController as my reference.
When I run the app, I'm getting the header collection starting from the status bar, instead being below the navigation bar.
Please find the screenshot below for reference.
![Simulator Screen Shot - iPhone 12 - 2021-08-09 at 17 32 35](https://user-images.githubusercontent.com/1597360/128704865-6b427f2d-366d-46cc-bea2-489ac5adcb44.png)

**Comment by rechsteiner** [comment]
I’ve updated the default behaviour to constrain the menu to the safe area guide now #673. You can try it out in the 4.0-beta release
