### ISSUE TITLE
Paging menu items are not centered initially

### ISSUE THREAD

**Issue by helloimtony** [rechsteiner/Parchment#59]
I initialized a FixedPagingViewController with two controllers, both with icons. I setup everything inside of viewDidLoad but then I noticed that they are not centered correctly. They only are properly centered after clicking on the other icon or swiping to the other tab. Is this possible a bug? or am I just using it incorrectly

**How it looks Initially**
<img width="272" alt="screen shot 2017-09-26 at 4 48 36 pm" src="https://user-images.githubusercontent.com/8811750/30883664-e7ee0798-a2da-11e7-8fd5-1ece5e1790f0.png">

**After switching to another tab**
<img width="267" alt="screen shot 2017-09-26 at 4 48 43 pm" src="https://user-images.githubusercontent.com/8811750/30883666-e8005cf4-a2da-11e7-858c-0a01103b3bc0.png">

**Now you can see it is properly centered**
<img width="274" alt="screen shot 2017-09-26 at 4 53 13 pm" src="https://user-images.githubusercontent.com/8811750/30883766-3c05c30c-a2db-11e7-8c46-9eae11278450.png">

Thanks!

**Comment by rechsteiner** [comment]
Hmm, seems to work just fine here. What options are you using?

**Comment by helloimtony** [comment]
here's my options 

```
struct CustomPagingMenuTheme: PagingTheme {
    let font: UIFont = Constants.ThemeColors.tabBarFont!
    let textColor: UIColor = Constants.ThemeColors.tabBarColor
    let selectedTextColor: UIColor = Constants.ThemeColors.tabBarColorActive
    let backgroundColor: UIColor = .white
    let headerBackgroundColor: UIColor = .white
    let indicatorColor: UIColor = Constants.ThemeColors.tabBarColorActive
    let borderColor: UIColor = .clear
}

struct HomePagingMenuOptions: PagingOptions {
    var menuItemClass: PagingCell.Type {
        return IconPagingCell.self
    }
    
    var menuItemSize: PagingMenuItemSize {
        return .fixed(width: 150, height: 50)
    }
    
    var menuHorizontalAlignment: PagingMenuHorizontalAlignment {
        return .center
    }

    var menuInteraction: PagingMenuInteraction {
        return .none
    }

    let theme: PagingTheme = CustomPagingMenuTheme()
}
```

here's how I use it 

```
override func viewDidLoad() {
        super.viewDidLoad()
        let first = PresetsViewController.instance()
        let second = ActiveClassViewController.instance()
        
        pagingMenuVC = FixedPagingViewController(viewControllers: [
            first,
            second], options: HomePagingMenuOptions())
        
        addChildViewController(pagingMenuVC)
        view.addSubview(pagingMenuVC.view)
        view.constrainToEdges(pagingMenuVC.view)
        pagingMenuVC.didMove(toParentViewController: self)
    }
```

**Comment by rechsteiner** [comment]
Weird, just tried it out with exactly those options and it still works. Which version of Parchment and iOS are you using?

**Comment by helloimtony** [comment]
iOS 11 and i'm using the latest version. Could it be because I'm possibly using a custom tab bar controller ? where the first tab is pretty much this paging menu controller? It seems to be working when I switch to another tab (i have other tabs that are using this library, they seem to be working but not on the first tab).

**Comment by rechsteiner** [comment]
Just tried to wrap this in a `UITabBarController`, but it still works just fine. Are you doing anything else that might affect how the view is displayed?

**Comment by helloimtony** [comment]
Unfortunately no, that's the entire code pretty much that I posted (aside from the custom tab bar). All I do is initialize the the paging menu controller and in the child view controllers they have zero logic in them at all. Basically just a view with text in the middle.

**Comment by rechsteiner** [comment]
Sure, that might be helpful

**Comment by helloimtony** [comment]
Thanks for the quick replies, here's my code below for the custom tab bar maybe it is the cause of all of it, however, i'm not sure why.
```

class CustomTabBarController: UIViewController {
    
    @IBOutlet weak var contentView: UIView!
    
    @IBOutlet var tabButtons: [UIButton]!
    
    @IBOutlet var tabActiveBorder: [UIView]!
    
    var tabControllers: [UIViewController]!
    var selectedIndex: Int = 0

    class func instance()->UIViewController{
        let controller = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "TabBarController")
        return controller
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        tabControllers = [
            HomeViewController.instance(),
            StatsViewController.instance(),
            ScheduleViewController.instance(),
            ClassesViewController.instance(),
            MoreViewController.instance()
        ]
        
        setButtonSelected(button: tabButtons[selectedIndex], bar: tabActiveBorder[selectedIndex])
        didPressTab(tabButtons[selectedIndex])
      
    }
    
    @IBAction func didPressTab(_ sender: UIButton) {
        let previousIndex = selectedIndex
        selectedIndex = sender.tag
        
        setButtonUnselected(button: tabButtons[previousIndex], bar: tabActiveBorder[previousIndex])
        let previousVC = tabControllers[previousIndex]
        previousVC.willMove(toParentViewController: nil)
        previousVC.view.removeFromSuperview()
        previousVC.removeFromParentViewController()
        
        setButtonSelected(button: sender, bar: tabActiveBorder[selectedIndex])
        
        let currentVC = tabControllers[selectedIndex]
        addChildViewController(currentVC)
        currentVC.view.frame = contentView.bounds
        contentView.addSubview(currentVC.view)
        currentVC.didMove(toParentViewController: self)
    }
    
    
    func setButtonSelected(button: UIButton, bar: UIView) {
        button.isSelected = true
        button.tintColor = Constants.ThemeColors.bottomNavBarIconActive
        button.isUserInteractionEnabled = false
        
        bar.isHidden = false
    }
    
    func setButtonUnselected(button: UIButton, bar: UIView) {
        button.isSelected = false
        button.tintColor = Constants.ThemeColors.bottomNavBarIcon
        button.isUserInteractionEnabled = true
        
        bar.isHidden = true
    }
    
}
```


i left out some small bits of code, but nothing related to changing views

**Comment by rechsteiner** [comment]
When you call `didPressTab:` from `viewDidLoad` the `contentView` bounds will be `.zero`.  Could it have something to do with the frame not being configured correctly? Are you setting the frame somewhere else as well?

**Comment by helloimtony** [comment]
That might be it, I tried moving the call to `didPressTab` to `viewDidAppear` instead and the tabs were centered correctly but I can't put it in viewDidAppear because then they views inside that need to draw themselves will be drawn late and the user will see it being transitioned from incorrect to correct. Not sure what's the best solution here, what do you recommend? Thanks!

**Comment by rechsteiner** [comment]
I would try to constrain the view using auto layout. That way the frame will be correct when the view appears, and it will also support transitioning to other sizes. Another option is to store the currently visible view as a property and set the frame in `viewWillLayoutSubviews`.

**Comment by helloimtony** [comment]
I decided to constrain it to the edges instead like you said, seems to have worked but now for some reason the first page in the Parch page controller frame seems to be wrong and only seems to be correct when I leave the page and come back. I printed out the frame of the page in `viewDidAppear` to ensure that I was properly getting the frame and I got `(750.0, 0.0, 375.0, 667.0)` and then after I went to another tab and came back i got `(0.0, 0.0, 375.0, 503.0)`. So all views that in that first page are not properly set because of the different frame. Why is it a different frame randomly?

**Comment by rechsteiner** [comment]
Is it one of the views inside `FixedPagingViewController` or `pagingMenuVC.view` that has the wrong frame? And are the initial menu items layout out correctly now?

You can select other items by calling `selectPagingItem:` with the item that you want to select. The items are available in the `items` property on `FixedPagingViewController`. Let's say you want to select the last one you could do:

```Swift
if let lastItem = pagingMenuVC.items.last {
    pagingMenuVC.selectPagingItem(lastItem)
}
```

**Comment by helloimtony** [comment]
One of the views inside of `FixedPagingViewController` to be more specific here is my code once again that shows how I initialize 

```
let first = PresetsViewController.instance()
        let second = ActiveClassViewController.instance()
        
        pagingMenuVC = FixedPagingViewController(viewControllers: [
            first,
            second], options: HomePagingMenuOptions())
        
        addChildViewController(pagingMenuVC)
        containerView.addSubview(pagingMenuVC.view)
        containerView.constrainToEdges(pagingMenuVC.view)
        pagingMenuVC.didMove(toParentViewController: self)
```

inside of `PresetsViewController` I print out the frame in `viewDidAppear` and the frame is incorrect initially

also thanks for the code for switching to another item! Appreciate it a lot

**Comment by rechsteiner** [comment]
Hmm, that's odd. Is the view for `pagingMenuVC.view` correct?

**Comment by helloimtony** [comment]
Not sure, how would I go about making sure that it's correct?

**Comment by rechsteiner** [comment]
You can just print out `pagingMenuVC.view.frame` like you did with the other views. Just curious to see if the `FixedPagingViewController` itself is displayed correctly.

**Comment by helloimtony** [comment]
I printed out the frame in `viewDidAppear` in the view controller I initialized it in and I got `(0.0, 0.0, 375.0, 553.0)` it seems to be correct. the `viewDidAppear` for `PresetsViewController` runs before the `viewDidAppear` where I print out the frames of `pagingMenuVC`. Not sure if that helps or not

**Comment by rechsteiner** [comment]
Sorry, I'm struggling to get this reproduced and it's not really obvious to me what would cause this. Are you doing anything inside `PresetsViewController`?

**Comment by TonyPNguyen** [comment]
I was finally able to fix it. I initialized it in `viewWillLayoutSubviews` instead of `viewDidLoad` and `viewDidAppear`. It's working perfectly now in iOS11 but for some reason it's not working in iOS9. It's having the same sort of effect. (will be testing it in iOS10 shortly)

**Comment by rechsteiner** [comment]
Hi! Sorry for the late response. Are you still seeing the bug with iOS 9? If that's the case, are you able to create a minimal bug report that re-reproduces the issue?

**Comment by rechsteiner** [comment]
Closing this for now, but feel free to open if you're able to reproduce this!
