### ISSUE TITLE
Package.swift must be updated if it's installed via Swift Package Manager

### ISSUE THREAD

**Issue by pot8os** [rechsteiner/Parchment#594]
Hello, let me report an issue and a temporary workaround for it.

## Environment

- Xcode 13 RC
- Parchment [master as of now](https://github.com/rechsteiner/Parchment/tree/60b4096e68e83c5eb9c8979ce2580a7e32e8ffba)

## How to reproduce

1. Install Parchment via Swift PM
2. Add it as a dependency of an app
3. Make an archive

## What's the issue

Compile fails even though the codebase has `#if canImport(...)` barrier. **It only happens when archiving as far as I see.**

<img width="559" alt="Screen Shot 2021-09-15 at 21 53 15" src="https://user-images.githubusercontent.com/5249113/133437194-9d61a994-abbb-4758-b081-0882ae33d6ad.png">

<img width="1128" alt="Screen Shot 2021-09-15 at 21 53 35" src="https://user-images.githubusercontent.com/5249113/133437208-865c1bc7-78bc-40f6-a527-e60ada8cdda1.png">

## (Temporary) Workaround

As explained [here](https://stackoverflow.com/a/58276883/5459180), I had to folk the repo and specify platform versions for all products. See also the below diff.

https://github.com/rechsteiner/Parchment/compare/master...pot8os:spm-archive?expand=1

All errors had gone when I switch to my branch above in the Swift PM settings.

## Consideration

Although it's a valid workaround, it bumps the minimum supported version of the library so I don't think it's an acceptable solution. The best option is that Xcode addresses the issue but I'm not sure when it becomes real. I'd be happy if you could share some thoughts.

Thanks!

**Comment by rechsteiner** [comment]
Thanks for the detailed report! It would definitely be a shame to drop support for that many versions. I'll see if I can find some other workaround.

**Comment by jerrylin1002** [comment]
I have the same issue, since xcode and macos updated this morning

**Comment by dendude** [comment]
I have the same issue

**Comment by luesp15** [comment]
> Hello, let me report an issue and a temporary workaround for it.
> 
> ## Environment
> * Xcode 13 RC
> * Parchment [master as of now](https://github.com/rechsteiner/Parchment/tree/60b4096e68e83c5eb9c8979ce2580a7e32e8ffba)
> 
> ## How to reproduce
> 1. Install Parchment via Swift PM
> 2. Add it as a dependency of an app
> 3. Make an archive
> 
> ## What's the issue
> Compile fails even though the codebase has `#if canImport(...)` barrier. **It only happens when archiving as far as I see.**
> 
> <img alt="Screen Shot 2021-09-15 at 21 53 15" width="559" src="https://user-images.githubusercontent.com/5249113/133437194-9d61a994-abbb-4758-b081-0882ae33d6ad.png">
> 
> <img alt="Screen Shot 2021-09-15 at 21 53 35" width="1128" src="https://user-images.githubusercontent.com/5249113/133437208-865c1bc7-78bc-40f6-a527-e60ada8cdda1.png">
> 
> ## (Temporary) Workaround
> As explained [here](https://stackoverflow.com/a/58276883/5459180), I had to folk the repo and specify platform versions for all products. See also the below diff.
> 
> https://github.com/rechsteiner/Parchment/compare/master...pot8os:spm-archive?expand=1
> 
> All errors had gone when I switch to my branch above in the Swift PM settings.
> 
> ## Consideration
> Although it's a valid workaround, it bumps the minimum supported version of the library so I don't think it's an acceptable solution. The best option is that Xcode addresses the issue but I'm not sure when it becomes real. I'd be happy if you could share some thoughts.
> 
> Thanks!

I tried but it doesn't work for me

**Comment by subzero3000** [comment]
Alternative Solution :
Instead of forking the repo please install using Cocoa Pods instead of Swift PM (remove from Package Dependencies if already installed). Then simply unlock the file PageView.swift for editing.
Change the line #if canImport(SwiftUI) && canImport(Combine) to #if !arch(arm), should archive without any issues.
<img width="837" alt="Screen Shot 2021-09-23 at 2 28 53 am" src="https://user-images.githubusercontent.com/66933126/134384071-26c00f57-7e8f-46b8-983c-705199f03446.png">

**Comment by sidneivl** [comment]
Not work for me, any solution to use this library?

**Comment by subzero3000** [comment]
Alternative Solution :
Instead of forking the repo please install using Cocoa Pods instead of Swift PM (remove from Package Dependencies if already installed and Don't forget to clean build folder). Then simply unlock the file PageView.swift for editing.
Change the line #if canImport(SwiftUI) && canImport(Combine) to #if !arch(arm), should archive without any issues.
Basically put all the swift UI code between #if !arch(arm) / #endif
<img width="859" alt="Screen Shot 2021-09-23 at 2 29 51 am" src="https://user-images.githubusercontent.com/66933126/134386425-2b3385a8-a862-4e2a-b81c-92341a991bb0.png">

**Comment by subzero3000** [comment]
> Not work for me, any solution to use this library?

Please try alternative solution

**Comment by rechsteiner** [comment]
This seems to be a known issue in Xcode 13: 

> Swift libraries may fail to build for iOS targets that use armv7. (74120874)
Workaround: Increase the platform dependency of the package to v12 or later.

From: https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes

Hopefully it will be fixed before the official release, but for now I've created a `xcode-13` branch that sets the deployment target to iOS 12 which fixes the issue.

**Comment by rechsteiner** [comment]
A new version `v3.1.0` is available now that should fix this issue 🥳 Let me know if anyone is still having issue
