### ISSUE TITLE
Selecting an item in menu to scroll to a specified viewController  will block pageViewController scroll animation。

### ISSUE THREAD

**Issue by MrKang** [rechsteiner/Parchment#608]
Parchment version: 3.0.1
xcode: 13.0
device：iPhone 12 iOS 15.0
There are some viewControllers have auto-scroll infinite loop scrollView。 If I scroll pageViewController to left or right by swipe that will be fine.But if I select an item in menu to scroll to a specified viewController ,  that will block view。If I stop timer schedule of infinite loop scrollView before selecting an item， the scroll animation will be fine。

**Comment by rechsteiner** [comment]
Hi @MrKang. Sorry for the late response. I hope you managed to find a solution for this. If you still think it's a bug with Parchment, let make know and I can re-open. If you have any ways of reproducing this it would be great.
