### ISSUE TITLE
UIFont has no member weight

### ISSUE THREAD

**Issue by Blaze349** [rechsteiner/Parchment#61]
<img width="270" alt="screen shot 2017-09-28 at 8 01 14 pm" src="https://user-images.githubusercontent.com/16263611/30962146-d7955794-a487-11e7-9de0-568f55a5fa85.png">
It is strange because it still exists in the UIKit documentation. I've tried using it in  Playground but it refuses to work.

**Comment by rechsteiner** [comment]
This was changed when updating to Swift 4. Are you using the latest version of Xcode?

**Comment by Blaze349** [comment]
I believe so.

**Comment by Blaze349** [comment]
I'm reinstalling Xcode at the moment

**Comment by rechsteiner** [comment]
Okay, let me know if that fixes it!

**Comment by rechsteiner** [comment]
Did you manage to get it working?

**Comment by Blaze349** [comment]
Parchment successfully compiles now

**Comment by rechsteiner** [comment]
Awesome 👌
