### ISSUE TITLE
When clicking the left-side menu item, the page scrolls in the wrong direction. Not solved.

### ISSUE THREAD

**Issue by ZaVyLoN** [rechsteiner/Parchment#611]
@rechsteiner the problem is not solved yet. 
Conditions:
Add a PagingItem to the end of the array.

`let items: [PagingItem] = [
        PagingIndexItem(index: 1, title: "TODO"),
        PagingIndexItem(index: 2, title: "In Progress"),
        PagingIndexItem(index: 3, title: "Archive"),
        PagingIndexItem(index: 4, title: "Other"),
        IconItem(icon: "earth", index: 0) // in example this is first line
    ]`
    
Result:
Swipe - ok
Tap at item: bug when tap icon tab (https://imgur.com/a/eZcs5i4)

Version 3.1.0
_Originally posted by @ZaVyLoN in https://github.com/rechsteiner/Parchment/issues/550#issuecomment-966482205_

**Comment by rechsteiner** [comment]
Hi @ZaVyLoN! Sorry for the late response. I've added a new `PagingIndexable` protocol now that addresses this issue #678. PagingIndexItem now implements this protocol and any custom protocol can conform to this to ensure that they animate correctly. It's available in the 4.0 branch and will be released soon. Thanks for the bug report 🙌
