### ISSUE TITLE
Can the menu work like WheelPicker?

### ISSUE THREAD

**Issue by i-tengfei** [rechsteiner/Parchment#612]
Now after scrolling the menu, you still need to click on one of them. Can you make it work like a WheelPicker and automatically select the middle?

**Comment by i-tengfei** [comment]
In ordinary `UICollectionView`, I can use `UICollectionViewLayout.targetContentOffset(forProposedContentOffset:withScrollingVelocity:)` or `UIScrollViewDelegate.scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>)` to modify the value of pointee.
But I see that the content of Parchment is dynamically updated after `scrollViewDidScroll`, so the targetContentOffset obtained is always 0 (left) or bounds.width (right).
Is there any other way to achieve it?

**Comment by i-tengfei** [comment]
Now use `scrollViewDidEndDecelerating` and `scrollViewDidEndDragging` to manually select after scrolling ends, but it is not smooth, and we look forward to a better solution.

**Comment by rechsteiner** [comment]
Hi @i-tengfei! Sorry for the late reply. I've now added support for a new menuInteraction called `.wheel` #679. It's available in the 4.0 branch and will be released soon. You can check out an example here https://github.com/rechsteiner/Parchment/blob/4.0/Example/Examples/Wheel/WheelViewController.swift.
