### ISSUE TITLE
After using PagingViewControllerInfiniteDataSource  reloadData, the menu is displayed to the wrong position.

### ISSUE THREAD

**Issue by i-tengfei** [rechsteiner/Parchment#616]
After using PagingViewControllerInfiniteDataSource  reloadData, the menu is displayed to the wrong position.
collectionView contentOffset is zero.

**Comment by beilusen** [comment]
请问这个问题解决了吗？怎样处理的？我的是每次reloadData 之后，菜单无法回到最开始的index

**Comment by i-tengfei** [comment]
> 请问这个问题解决了吗？怎样处理的？我的是每次reloadData 之后，菜单无法回到最开始的index

在 `reloadData(around pagingItem: PagingItem)` 之后调用 `pagingController.viewAppeared()` 可解决。

**Comment by rechsteiner** [comment]
Hi @i-tengfei @beilusen! Sorry for the late response. When using PagingViewControllerInfiniteDataSource, you need to call `reloadData(around pagingItem:)` instead of just `reloadData` (see [docs](https://github.com/rechsteiner/Parchment#reloading-data)).
