### ISSUE TITLE
Should didSelectItem method be called before selection?

### ISSUE THREAD

**Issue by Bartson** [rechsteiner/Parchment#617]
Hi,
I have a doubt if the didSelectItem method should be called before the actual selection. This is most evident when the selection with animation is selected. ViewController is assigned as selected after the animation is over. Interestingly, this situation did not always look this way. Is there a method that fires after the actual selection?

**Comment by Bartson** [comment]
What's more, the didScrollToItem method should ensure that when it is called, the selectedViewController is set to the latest. But it **is not**

**Comment by rechsteiner** [comment]
Hey! Sorry for the long wait. This should be fixed now in the 4.0 branch (#676).
