### ISSUE TITLE
Parchment does not work with navigation bars

### ISSUE THREAD

**Issue by Blaze349** [rechsteiner/Parchment#62]
I'm sorry to bother you yet again but I found this problem.
I had a viewcontroller embed in a uinavigationcontroller and in a uitabbarcontroller. 

I compiled the example project you listed and it worked. Then I embed it within a navigation bar but it becomes hidden under the bar. I'm confused because your examples render it correctly.

<img width="414" alt="screen shot 2017-09-29 at 5 21 25 pm" src="https://user-images.githubusercontent.com/16263611/31006140-a9a0e0ac-a53a-11e7-8c8c-97bf6266073f.png">

Also, constrain to edges doesn't work in Swift 4.

**Comment by rechsteiner** [comment]
Hi! The default behaviour on iOS is that the content appear underneath the navigation bar. You can set `edgesForExtendedLayout = []` in your view controller to prevent this, or if you're using Storyboard you can disable the `Extend edges: Under Top Bars` option. With iOS 11, you can constrain the view to the `safeAreaLayoutGuide` instead, which is recommended by Apple:

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621515-edgesforextendedlayout

The `constrainToEdges` is not part of UIKit, but rather an extension that I made to make it easier to setup the constraints. You copy over the source from `UIView+constraints.swift` if you want the same function in your app.

**Comment by Blaze349** [comment]
Thank you so much. I won't bother you anymore. :)

**Comment by Blaze349** [comment]
My actual solution to the problem was to manually constrain the childViewController below the statusBar and navBar. This retained the translucent effect
