### ISSUE TITLE
Prevent Scrolling While The Delegate Was Called

### ISSUE THREAD

**Issue by dijfgowr** [rechsteiner/Parchment#624]
Is it possible to add a new delegate function, that will ask the delegate if the paging view should scroll or not, while the scroll related delegate was called. 
Such as `textViewShouldBeginEditing(_ textView: UITextView) -> Bool` that we could return a bool to let it know if the textview should begin editing or not.

Thank you!

**Comment by rechsteiner** [comment]
Hi @dijfgowr! Might be a bit late, but you should be able to handle this by implementing UIGestureRecognizerDelegate and cancelling the gesture there.
