### ISSUE TITLE
Crash on iOS <13

### ISSUE THREAD

**Issue by jannemecek** [rechsteiner/Parchment#626]
Opening the app on latest version of iOS 12 crashes with

```
dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /private/var/containers/Bundle/Application/86CA77AF-50E7-4164-A2F3-03C1C25F2451/[REDACTED].app/Frameworks/Parchment.framework/Parchment
  Reason: image not found
```

Reverting to 3.0.1 fixes this.

I'll try to investigate some more and submit a PR. SwiftUI imports seems to be the same between both versions.

**Comment by ageevvalentin** [comment]
Check master. #583

**Comment by jannemecek** [comment]
Thanks, gonna close this issue then.

**Comment by rechsteiner** [comment]
Sorry, will release a new version soon!

**Comment by ankit0812** [comment]
@rechsteiner Please release the new version asap. 🙏

**Comment by rechsteiner** [comment]
@ankit0812 you can just target the master branch in the meantime

**Comment by ankit0812** [comment]
Cool, thanks. Please update us when a release is rolled out for this.

**Comment by HHMedic** [comment]
XCode 13.2.1 also crash, what can I do to resovle this problem?

**Comment by ankit0812** [comment]
For the being replace this on your podfile
  <pod 'Parchment', :git => 'https://github.com/rechsteiner/Parchment.git', :branch => 'master'>
hit pod install/update and you are done.

**Comment by rechsteiner** [comment]
New version is out now: https://github.com/rechsteiner/Parchment/releases/tag/v3.2.0
