### ISSUE TITLE
viewDidAppear is not getting called

### ISSUE THREAD

**Issue by sakshigidwani93** [rechsteiner/Parchment#628]
In the child controller the viewdidAppear method is not getting called for iOS 15. In earlier iOS versions it was getting called and worked properly. Using Parchment (3.1.0) pod version.

**Comment by rechsteiner** [comment]
Hi @sakshigidwani93! Sorry for the late response. Do you have any tips on how to reproduce this? I'm not seeing this behaviour myself.
