### ISSUE TITLE
SPM: Compile project error

### ISSUE THREAD

**Issue by devshamzi** [rechsteiner/Parchment#634]
Hello, I am using Swift Package Manager using the URL "https://github.com/rechsteiner/Parchment" (Project > Project > Swift Packages). 

Dependency Rule: Exact Version - 3.2.0
Add to Project: 'MyProject'

When compiling I get an error

> The package product 'Parchment' cannot be used as a dependency of this target because it uses unsafe build flags.

Thanks for the help in advance.

**Comment by andre719mv** [comment]
I have the same issue when use xcodeproj file. It does not fail with xcworkspace file, but sopport of running from xcodeproj file is required in my project.

**Comment by devshamzi** [comment]
@andre719mv You added via CocoaPod or SPM?

**Comment by andre719mv** [comment]
SPM. Issue is gone when I revert to 3.1.0

**Comment by ageevvalentin** [comment]
I have the same error. I found:
https://forums.swift.org/t/override-for-unsafeflags-in-swift-package-manager/45273
https://forums.swift.org/t/confused-by-unsafe-flags-being-disallowed-in-dependencies/27359

So far, the workaround is to use a specific commit hash (7773785da86e1a2840a32837798b9d7e570a8324) for dependency.

**Comment by CleSmartwave** [comment]
Hi @ageevvalentin, I'm on Xcode 12 and encountered the same issue but the workaround (use a specific commit hash (7773785da86e1a2840a32837798b9d7e570a8324) for dependency) does not work for me. Any ideas?

**Comment by benjohn-ee** [comment]
I'm seeing this same error with the latest Xcode – 13.4.1 (13F100). Is seems to have started with the official release that downloaded over the weekend; I didn't see it with the release candidate. 

It happens with both Parchment 3.1.0 (which we're currently using) and 3.2.0 (which I could update to). 

I don't think I can use a commit hash because in this case the dependency is owned and managed by an Xcode project in a "<ProjectName>.workspace/xcshareddata/swiftpm/Package.resolved" file, not an SPM Package file. I tried remove the package version and leave the hash, but it seems Xcode put the package version back in.

**Comment by ageevvalentin** [comment]
> I'm seeing this same error with the latest Xcode – 13.4.1 (13F100). It seems to have started with the official release that downloaded over the weekend; I didn't see it with the release candidate.
> 
> It happens with both Parchment 3.1.0 (which we're currently using) and 3.2.0 (which I could update to).
> 
> I don't think I can use a commit hash because in this case the dependency is owned and managed by an Xcode project in a ".workspace/xcshareddata/swiftpm/Package.resolved" file, not an SPM Package file. I tried remove the package version and leave the hash, but it seems Xcode put the package version back in.

I'm on the 13.4. I will check it tomorrow on the 13.4.1.
You can set a commit hash via Xcode 'Project settings -> Package dependencies' or set it directly to the 'Package.resolved'

<details>
    <summary>Xcode</summary>
    <img width="483" alt="Screenshot 2022-06-06 at 22 21 53" src="https://user-images.githubusercontent.com/8999553/172234118-e8398154-b532-4fad-85ea-f2281e136ec4.png">
</details>
<details>
    <summary>Package.resolved (Maybe need to close Xcode and clear DerivedData)</summary>
    <img width="592" alt="Screenshot 2022-06-06 at 22 22 57" src="https://user-images.githubusercontent.com/8999553/172234134-fd95c359-cf36-490c-804d-7387f64a148e.png">
</details>

**Comment by mpoimer** [comment]
I'm seeing the same with Xcode 13.4, where it only happens if I'm trying to use 3.2.0. 
When choosing exact "3.1.0" it does not show an error

**Comment by SmartHbdev** [comment]
> I'm seeing the same with Xcode 13.4, where it only happens if I'm trying to use 3.2.0. When choosing exact "3.1.0" it does not show an error

Thanks !

Xcode 13.4.1 and 3.1.0 is OK.
Something in the code between 3.1.0 and 3.2.0 need a fix for SPM

**Comment by sugitatestblue** [comment]
spm not supported?

**Comment by amir-hormozi** [comment]
The same error occurred to me too via SPM. Could you please fix it?

**Comment by mohan-kurera** [comment]
I have the same issue. 
Xcode 14.2
parchment 3.2.0 (SPM)

Does anyone know how to fix this issue?

**Comment by rechsteiner** [comment]
Sorry for the late update. I decided to just remove the unsafe compiler flags, so this should be fixed now #662. As the PR explains, this will probably break some other apps, but it's more important to get this issue fixed. This fix is available in version `3.2.1`
