### ISSUE TITLE
Crash on iOS 12.5.4 (libswift_Concurrency.dylib (which was built for iOS 13.0)) with ver. 3.2.0

### ISSUE THREAD

**Issue by Medef** [rechsteiner/Parchment#636]
I still have an error on version 3.2.0 of the framework. Here is what is output to the console, I will be glad for any help

dyld: Symbol not found: ___chkstk_darwin
  Referenced from: /private/var/containers/Bundle/Application/UUID/AppName.app/Frameworks/libswift_Concurrency.dylib (which was built for iOS 13.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/var/containers/Bundle/Application/UUID/AppName.app/Frameworks/libswift_Concurrency.dylib
(lldb)

**Comment by rechsteiner** [comment]
Hi @Medef! Parchment is not using any of the Swift concurrency features, so this seems like an issue specific to your app.
