### ISSUE TITLE
Table view inside the paging viewcontroller not scrolling.

### ISSUE THREAD

**Issue by vishnupxminds** [rechsteiner/Parchment#637]
Does anyone have any idea on how to bring up the scroll of the table view which is inside the paging view controller?

**Comment by Medef** [comment]
> Does anyone have any idea on how to bring up the scroll of the table view which is inside the paging view controller?

Everything works correctly, check if scrolling is disabled for the TableView

**Comment by vishnupxminds** [comment]
I have checked that but scrolling is enabled

**Comment by vishnupxminds** [comment]
Sorry for the trouble user interaction was disabled on my TableView. Now things are working accordingly
