### ISSUE TITLE
When hiding the animation of the select function, send crash in iPhone5s

### ISSUE THREAD

**Issue by lilong-git** [rechsteiner/Parchment#639]
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/15997769/168198283-b101b340-3950-4804-9433-77118cae3eaf.png">

**Comment by rechsteiner** [comment]
Hi @lilong-git! Sorry for the late response. Are you still seeing this issue? If so, could you share some more details about your implementation and how to reproduce this?
