### ISSUE TITLE
(Question) swipe menu with button

### ISSUE THREAD

**Issue by miguelalvescosta** [rechsteiner/Parchment#64]
its possible navigate to next menu tab with button in storyboard?

**Comment by rechsteiner** [comment]
Yes, you can change to another item using `selectPagingItem`. You can get the item you want to select from the `items` property on `FixedPagingViewController`. Let's say you want to select the second item in the list you could do something like this:

```Swift
pagingViewController.selectPagingItem(pagingViewController.items[1])
```

If you always want to select the next item, you have to manually keep track of the current index and select the upcoming item based on that. You can implement the `FixedPagingViewControllerDelegate` to keep track of the currently selected index:

```Swift
public protocol FixedPagingViewControllerDelegate : class   {
  func fixedPagingViewController(
    fixedPagingViewController: FixedPagingViewController,
    willScrollToItem: ViewControllerItem,
    atIndex index: Int)
  
  func fixedPagingViewController(
    fixedPagingViewController: FixedPagingViewController,
    didScrollToItem: ViewControllerItem,
    atIndex index: Int)
}
```

Hope that helps!

**Comment by rechsteiner** [comment]
Did you get it working?

**Comment by miguelalvescosta** [comment]
yes, ty for support :)

**Comment by miguelalvescosta** [comment]
Hi again, i have 2 controller one for my storyboard and another too my menu, how i can access to my menu to change page in my viewcontroller associate to my storyboard? is possible?

**Comment by miguelalvescosta** [comment]
hum, i think i found a solution, with delegate created at my viewcontroller menu. is a good solution?
