### ISSUE TITLE
Swipe in cell does not work

### ISSUE THREAD

**Issue by thierrybucco** [rechsteiner/Parchment#643]
Hi,

My embedded view controller has a tableview. Cell need to react to swipe gesture.
Unfortunately when I swipe left on the cell, paging take the gesture.
Is there a way to determine disable paging scroll when I am swiping on the cell?

Thanks a lot.

**Comment by Viet20021476** [comment]
have u found the solution?

**Comment by rechsteiner** [comment]
Hey! Check out this comment on how this can be solved: https://github.com/rechsteiner/Parchment/issues/542#issuecomment-745526231.
