### ISSUE TITLE
PageView does not work in ScrollView

### ISSUE THREAD

**Issue by canozt** [rechsteiner/Parchment#647]
I am using version 3.1.0. In swiftui, Pageview does not work when you put it in ScrollView. Probably it is related to nested scrollviews issue. It works when you set frame but the content of the pageview will be dynamic. Is there any trick to solve that issue ?
```
ScrollView {
      PageView(options: getOptions(), items: items, selectedIndex: $selectedIndex) { item in
           VStack {
                   ForEach(0..<100) { i in
                        Text("\(i)")
                   }
               }
            }
}
```

**Comment by lasodashutosh** [comment]
@canozt were you able to find the solution to this?

**Comment by canozt** [comment]
@lasodashutosh  Not really. Firstly i tried to calculate the height of the inner scroll and set the frame height with that value. It works but then i did not like that solution. Then i remove the upper ScrollView, and put it into PageView.
