### ISSUE TITLE
Issue on Index

### ISSUE THREAD

**Issue by ignatiojulian** [rechsteiner/Parchment#650]
Hi, I have a problem when shifting tabs
when I swipe right (next tab) and swipe left (previous tab) it doesn't get an accurate index accordingly
Any solution / answer would be appreciated
Thank you

Example:
Current Position: 5, Swipe Left: 2, Swipe Right: 3

Here's my code:
    `func numberOfViewControllers(in pagingViewController: Parchment.PagingViewController) -> Int {
        return categoryMenuLevelOneTitle.count
     }
    
    func pagingViewController(_: Parchment.PagingViewController, viewControllerAt index: Int) -> UIViewController {
        return NewCategoryLevelTwoViewController(index: index, content: categoryMenuLevelTwoTitle)
    }
    
    func pagingViewController(_: Parchment.PagingViewController, pagingItemAt index: Int) -> Parchment.PagingItem {
        return PagingIndexItem(index: index, title: categoryMenuLevelOneTitle[index])
    }`

**Comment by rechsteiner** [comment]
Hi @ignatiojulian! I’m not able to reproduce this myself. Are you able to reproduce it in one of the other example apps? Could there be something wrong with your data source?
