### ISSUE TITLE
My app crash when tap to page item.

### ISSUE THREAD

**Issue by st-tringuyen2** [rechsteiner/Parchment#657]
On v3.2.0: When I tap into a tap it crash because it call layoutSubviews and it force my children view call layoutSubviews before my parent viewcontroller appear.
On v2.3.0: It OK no problem

**Comment by rechsteiner** [comment]
Hi @st-tringuyen2! Thanks for the bug report. Do you have any ways I can reproduce this? I haven't been able to see any crashes when tapping items.

**Comment by rechsteiner** [comment]
I'm pretty sure this should be fixed with #680. It's available in the 4.0 branch and will be released soon. Let me know if you're still having any issues with this and I'll re-open this.

**Comment by rechsteiner** [comment]
Right, probably should have done that instead of tying it to 4.0 😬 Ran into some issues with the new SwiftUI API, so wanted to have it beta for some time to make sure it's solid. I think everything is looking good, so I'll prepare a new release this week

**Comment by rechsteiner** [comment]
Version 4.0 is now released 🥳
