### ISSUE TITLE
Swipe in last item bug

### ISSUE THREAD

**Issue by miguelalvescosta** [rechsteiner/Parchment#66]
Hi :),
i think i found a bug, example: if u are in the last menu item on the left or right and swipe to left or right, after swipe u cant select menu items

**Comment by rechsteiner** [comment]
Hey! This was supposed to be fixed in [v0.6.0](https://github.com/rechsteiner/Parchment/releases/tag/v0.6.0). Which version are you using?

**Comment by miguelalvescosta** [comment]
oh ok, thanks :). is good now
