### ISSUE TITLE
how to make collectionview rounded and add shadow to collectionview

### ISSUE THREAD

**Issue by NikhilGangurde** [rechsteiner/Parchment#682]
<img width="838" alt="Screenshot 2023-04-19 at 9 33 02 PM" src="https://user-images.githubusercontent.com/46920378/233134194-d63e51e2-75b8-44af-a157-a788e3e7dd10.png">

how can i make this view 

here is what I tried and not working:
```
class RoundedPagingCell: PagingTitleCell {

   open override func setPagingItem(_ pagingItem: PagingItem, selected: Bool, options: PagingOptions) {
    super.setPagingItem(pagingItem, selected: selected, options: options)
       guard let item = pagingItem as? PagingIndexItem else { return }
    
    // Apply shadow to content view

    if item.index == 0 {
        contentView.dropShadow(offsetX: 0, offsetY: 0, color: .lightGray, opacity: 0.5, radius: 10)
    } else if item.index == 2 {
        contentView.dropShadow(offsetX: 0, offsetY: 0, color: .lightGray, opacity: 0.5, radius: 10)
    }
    
  }
    
}
```

**Comment by rechsteiner** [comment]
Hi @NikhilGangurde! It's a bit hard to say why that is not working based you just your example. In general, it should be possible to apply the corner radius inside the cell, based on the index of the item. Another option would be to apply the corner radius on the `pagingController.collectionView` itself. You can provide your own `PagingView` subclass where you can completely customize the layout and size of the collection view as well.
