### ISSUE TITLE
outdated code error in PagingSizeCache

### ISSUE THREAD

**Issue by iosdev4rnd** [rechsteiner/Parchment#685]
Hi, 
i am getting this outdated code error when i checkout the code. i dont want to edit the files. so am i fetching wrong branch ? or what. if someone can help me out please.

'didEnterBackgroundNotification' has been renamed to 'NSNotification.Name.UIApplicationDidEnterBackground'

in PagingTitleCell
Reference to member 'selected' cannot be resolved without a contextual type
Reference to member 'tabBar' cannot be resolved without a contextual type
Reference to member 'tabBar' cannot be resolved without a contextual type

**Comment by rechsteiner** [comment]
Hey! Which version are you using? Could you try referencing the 4.0 branch?

**Comment by iZeDeveloper** [comment]
ok i tried with the said branch. and i still have error in

'didReceiveMemoryWarningNotification' has been renamed to 'NSNotification.Name.UIApplicationDidReceiveMemoryWarning'

PagingSizeCache

and

Reference to member 'selected' cannot be resolved without a contextual type

on PagingTitleCell

**Comment by rechsteiner** [comment]
Which version of Xcode are you using?
