### ISSUE TITLE
Position of tableview is reset after tab change in header above menu example

### ISSUE THREAD

**Issue by SubvertDev** [rechsteiner/Parchment#688]
After swiping the tab in header above menu example, previous tableview offset is reset to the top instead of keeping it, reproducible both on 3.2.1 and 4.0.0

https://github.com/rechsteiner/Parchment/assets/59670026/5df6c408-7b27-4d39-9c2b-ffd8983ad5b0

**Comment by rechsteiner** [comment]
Hi @SubvertDev! These examples are just meant to show what you can do with Parchment, and not really an issue with Parchment itself. You can change this behaviour in your app if you wanted to. Let me know if you run into any limitation with Parchment itself when trying to implement this though
