### ISSUE TITLE
Using UIAlertController in per Item

### ISSUE THREAD

**Issue by r0otx** [rechsteiner/Parchment#689]
If I use UIAlertController and call his, I'm show message in console:

`[Presentation] Presenting view controller <UIAlertController: 0x125840a00> from detached view controller <_TtGC5example13StatsVCCS_19StatsViewImpl_: 0x1255390f0> is discouraged.`

If I call AlertController 4-5 times on different views then my app crashes:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally a view controller <UIAlertController: 0x12585f800> that is already being presented by <Parchment.PagingViewController: 0x12704f000>.'`

Many thanks in advance for your help, this is a great plugin that solves my problem!

**Comment by rechsteiner** [comment]
Hi @r0otx! I'm not sure this is related to Parchment. It sounds like this is something specific to your app, so maybe you can look into reducing bug into a minimal reproduction case.

**Comment by r0otx** [comment]
I'm use Coordinator pattern in my app, maybe it's crash my view controller.

**Comment by rechsteiner** [comment]
I'll close this issue for now, but let me know if you still think this is an issue with Parchment
