### ISSUE TITLE
Navigation bar disappear when presented in a sheet.

### ISSUE THREAD

**Issue by Scocher** [rechsteiner/Parchment#691]
If you present a ParchmentView in a NavigationView in a sheet for swiftUI, the navigation bar disappear when the first page title goes off screen.

In the ExampleApp. This is the code a used to reproduced the bug.
```
struct ExampleApp: App {
  @State var isPresentingDefault: Bool = false
  var body: some Scene {
    WindowGroup {
      NavigationView {
        List {
          Button("Default Sheet") { isPresentingDefault = true }
          NavigationLink("Default", destination: DefaultView())
          NavigationLink("Change selected index", destination: SelectedIndexView())
          NavigationLink("Lifecycle events", destination: LifecycleView())
          NavigationLink("Change items", destination: ChangeItemsView())
        }
        .navigationBarTitleDisplayMode(.inline)
        .sheet(isPresented: $isPresentingDefault, content: {
          NavigationView(content: {
            ChangeItemsView()
              .navigationTitle("Default")
              .navigationBarTitleDisplayMode(.inline)
          })
        })
      }
    }
  }
}
```
![bug](https://github.com/rechsteiner/Parchment/assets/2694492/71213cf9-0698-405c-9da5-4290a48d6e61)

**Comment by rechsteiner** [comment]
Hi @Scocher! Thanks for reporting the issue. Which iOS and Parchment version are you using? Your example seems to work just fine when I'm running on iOS 17, so maybe it's a SwiftUI bug that has been fixed by Apple?

**Comment by Scocher** [comment]
I will close this, since it seems to be an apple bug.
