### ISSUE TITLE
About swiftUI PageView content scrollview automatically slides to the top

### ISSUE THREAD

**Issue by lijl** [rechsteiner/Parchment#692]
When I was using the swiftui. official demo, I nested the ScrollView in the pageview content. When I clicked the item to push to another page, the ScrollView automatically slid to the top. I don't know if this problem is an internal problem of the SDK.

![WX20231027-132807@2x](https://github.com/rechsteiner/Parchment/assets/2133154/c80ea051-b42e-4a56-a6d2-13f3b20011d9)

https://github.com/rechsteiner/Parchment/assets/2133154/63b96bd4-95af-42d2-9882-c902cc36867b

@rechsteiner

**Comment by rechsteiner** [comment]
Hi @lijl! Thanks for the report. Which version of Parchment are you using?

**Comment by lijl** [comment]
Hi @rechsteiner   I ran the latest version today and it seems to have been changed. Thank you so much
