### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by bactn** [rechsteiner/Parchment#694]
At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs will need to provide a privacy manifest.

Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our app releases to take this into account.

Apple News:

https://developer.apple.com/news/?id=r1henawx

Thank you

**Comment by rechsteiner** [comment]
Thanks for the reminder 🙌 I’ll look into what is needed and update as soon as possible.

**Comment by rechsteiner** [comment]
Hi @bactn! The privacy manifest is now available in the latest 3.3.0 version (#701)
