### ISSUE TITLE
Is it possible to change access for the method

### ISSUE THREAD

**Issue by AdAvAn** [rechsteiner/Parchment#71]
Is it possible to do an **open** method:
 
`public func em_pageViewController (_ pageViewController: EMPageViewController, willStartScrollingFrom startingViewController: UIViewController, destinationViewController: UIViewController) {}`

I would like to use his heirs class PaguingViivcontroller.

Many thanks.

**Comment by rechsteiner** [comment]
Hi! Not sure why that wasn't `open` like the other ones. Fixed in #72 and released in v0.7.0 👍
