### ISSUE TITLE
buggy scrolling in pageViewController on iOS 11 / iPhone X

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#74]
There is a buggy scrolling in pageViewController on iOS 11 / iPhone X. It scrolls in all directions.
Don't know why but this bug is present on all our devices with our project, and only on iPhone X with your example (icon Example)

![simulator screen shot - iphone x - 2017-11-08 at 02 52 34](https://user-images.githubusercontent.com/16180201/32527902-7a1b88a4-c430-11e7-9f5a-b55e302e9e0c.png)

Apparently, it's linked to this scrollview and to scrollview insets.

![screenshot at nov 08 02-53-01](https://user-images.githubusercontent.com/16180201/32527989-e16853ac-c430-11e7-9fa4-73bc9da0e3be.png)

In our project, actually by guess, I have solved this problem with this code, though I am not sure if that's the best solution.

`scrollView.contentInsetAdjustmentBehavior = .never`

**Comment by rechsteiner** [comment]
Hi! Looks like an issue with the new `safeAreaInsets`. Setting `contentInsetAdjustmentBehavior = .never` seems to fix the issue, but according to [this](https://twitter.com/smileyborg/status/910656113653116928) it's probably best to avoid using that with scroll views. Need to do a bit more testing to figure out if that's actually an issue here though.

**Comment by rechsteiner** [comment]
Seems to be working fine with `contentInsetAdjustmentBehavior = .never`. Will release a new version soon. Thanks for catching this!

**Comment by IVANKRUPSKI** [comment]
Ok. Welcome!
