### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by bozo4** [rechsteiner/Parchment#76]
why i got this error ?

`ld: warning: ignoring file /Users/bozo/Desktop/*****/Parchment.framework/Parchment, file was built for x86_64 which is not the architecture being linked (arm64): /Users/bozo/Desktop/*****/Parchment.framework/Parchment
ld: '/Users/bozo/Library/Developer/Xcode/DerivedData/*****-dhuanbzszeeilpdafoqmheorglne/Build/Products/Debug-iphoneos/Nimble/Nimble.framework/Nimble' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/bozo/Library/Developer/Xcode/DerivedData/******-dhuanbzszeeilpdafoqmheorglne/Build/Products/Debug-iphoneos/Nimble/Nimble.framework/Nimble' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by rechsteiner** [comment]
Hi! When are you getting this error? If you're trying to run the test suite you have to install the dependencies using `carthage bootstrap`.

**Comment by rechsteiner** [comment]
Closing this, but let me know if you still need any help!
