### ISSUE TITLE
willScrollToItem delegate method is not getting called.

### ISSUE THREAD

**Issue by mkelowna** [rechsteiner/Parchment#83]
`open class PagingViewController<T: PagingItem>:` 

is not declaring the optional function

        @objc  optional func em_pageViewController(_ pageViewController: EMPageViewController, willStartScrollingFrom startingViewController: UIViewController, destinationViewController:UIViewController)

Which require overriding the function in FixedPagingViewController:

    open override func em_pageViewController(_ pageViewController: EMPageViewController, didFinishScrollingFrom startingViewController: UIViewController?, destinationViewController: UIViewController, transitionSuccessful: Bool) `

only then will the delegate method willScrollToItem be called.

**Comment by rechsteiner** [comment]
Which version are you using? This should be fixed in #63 which was released in v0.7.0.
