### ISSUE TITLE
FixedPagingViewControllerDelegate does not recognize an aborted scroll

### ISSUE THREAD

**Issue by mkelowna** [rechsteiner/Parchment#84]
Currently FixedPagingViewControllerDelegate does not recognize an aborted scroll. Running the code as noted below increments the index even when a scroll is not completed.

    extension UIViewController: FixedPagingViewControllerDelegate{
    func fixedPagingViewController(fixedPagingViewController: FixedPagingViewController, willScrollToItem: ViewControllerItem, atIndex index: Int) {
        print("about to move to: \(index)")
    }
    
    func fixedPagingViewController(fixedPagingViewController: FixedPagingViewController, didScrollToItem: ViewControllerItem, atIndex index: Int) {
         Defaults[.vcIndex] = index
        print("Moved to: \(index)")
    }
    
    }

Suggest something similar to the following changes to FixedPagingViewController that sends destination index only on successful transition

`     // MARK: EMPageViewControllerDelegate
    
    open override func em_pageViewController(_ pageViewController: EMPageViewController, didFinishScrollingFrom startingViewController: UIViewController?, destinationViewController: UIViewController, transitionSuccessful: Bool) {
        super.em_pageViewController(pageViewController, didFinishScrollingFrom: startingViewController, destinationViewController: destinationViewController, transitionSuccessful: transitionSuccessful)
        
        if let index = items.index(where: { $0.viewController == destinationViewController }) {
            if let cIndex = currentIndex {
                itemDelegate?.fixedPagingViewController(
                    fixedPagingViewController: self,
                    didScrollToItem: items[index],
                    atIndex: transitionSuccessful ? index  : cIndex )
            }
        }
    }
    
    public override func em_pageViewController(_ pageViewController: EMPageViewController, willStartScrollingFrom startingViewController: UIViewController, destinationViewController: UIViewController) {
        if let cIndex = items.index(where: { $0.viewController == startingViewController }) {
            currentIndex = cIndex
        }
        if let index = items.index(where: { $0.viewController == destinationViewController }) {
            itemDelegate?.fixedPagingViewController(
                fixedPagingViewController: self,
                willScrollToItem: items[index],
                atIndex: index)
        }
    }`

**Comment by rechsteiner** [comment]
This should also be fixed in v0.7.0 👍
