### ISSUE TITLE
Is possible to have paging cell respond to touches for animation (touchesBegan, touchesEnded, ...)?

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#88]

**Comment by rechsteiner** [comment]
I'm not really sure, but I don't think that's possible. What are you trying to achieve?

**Comment by IVANKRUPSKI** [comment]
I am trying to achieve some touchDown, touchUp animation of text/ icon when touching the cell.

**Comment by rechsteiner** [comment]
Ah okay. If you create you're own `PagingCell` subclass, you can override the `isHighlighted` property which will be set whenever the cell is being pressed. Here's an example:

```Swift
class CustomPagingCell: PagingCell {
  
  override var isHighlighted: Bool {
    didSet {
      if isHighlighted {
        backgroundColor = .red
      } else {
        backgroundColor = .white
      }
    }
  }
  
}
```

Does that work for you?

**Comment by IVANKRUPSKI** [comment]
Cool!
It does work. Thanks!
