### ISSUE TITLE
Is it possible to limit switching between tabs only through the menu items?

### ISSUE THREAD

**Issue by TonyPNguyen** [rechsteiner/Parchment#89]
in other words, users can only switch between pagesthrough clicking on the tabs and not being able to switch in any other way (athough only other way I know right now is swiping between the pages themselves)

**Comment by rechsteiner** [comment]
Hi! Yes, you can disable user interaction on the page view controller like this:

```Swift
pagingViewController.pageViewController.view.isUserInteractionEnabled = false
```

**Comment by TonyPNguyen** [comment]
It works but the view controller it's showing can't interact with the user anymore. Any ideas what I could do?

**Comment by rechsteiner** [comment]
Oh yeah that's true. Disabling scrolling on the scroll view should work:

```Swift
pagingViewController.pageViewController.scrollView.isScrollEnabled = false
```

**Comment by TonyPNguyen** [comment]
works like a charm! thanks for the speedy reply as always

**Comment by rechsteiner** [comment]
No problem 🙂

**Comment by tikipatel** [comment]
Updating to reflect a better answer found in #178:

    pagingViewController.contentInteraction = .none
