### ISSUE TITLE
Reload Cell in Collectionview

### ISSUE THREAD

**Issue by phanvandinh** [rechsteiner/Parchment#92]
hi, i have a problem with lib, please help me, how to reload collectionView in pagingView? i try call pagingViewController.collectionView.reloadData() but not work.

**Comment by rechsteiner** [comment]
Hi! That should work just fine. Just tested using the Example target and it works as expected. Are you sure it’s acutally being called?

**Comment by phanvandinh** [comment]
yes, setPagingItem method have call from PagingCell, sorry i mistake.
i have class extend PagingViewControllerDataSource, i have to try change [pagingItem] model with new Values([PagingItem] = getNewArrayPagingItem()) and call pagingViewController.collectionView.reloadData() but pagingItem still have old values in method setPagingItem, please tell me how to update dataSource [pagingItem]

**Comment by rechsteiner** [comment]
Sorry, looks like this isn't actually possible with the current version. I added another method called `reloadData(around:)` in #94 that you can use to trigger a reload. Could you try this out and let me know if this works for you? I will release a new version soon, but you can also target the master branch directly if you want to use it right away.

**Comment by phanvandinh** [comment]
hi, thank your very much, method that ready woking for me.
